### PR TITLE
monitor desc default workspace

### PR DESCRIPTION
**Pull request by MightyPlaza**
allows default workspace to be set with monitor desc

### CODE REVIEW

**Review by vaxerski — APPROVED** [review]
k

**Comment by nwg-piotr** [comment]
Thanks again. I wish I could confirm it works, but the current -git version doesn't start for me.

**Comment by MightyPlaza** [comment]
Works for me, any error?

**Comment by nwg-piotr** [comment]
It turns out it only crashes with this workspaces config:

```text
# Generated by nwg-displays on 2023-07-11 at 01:55:14. Do not edit manually.

workspace=1,monitor:desc:AOC 2475WR F17H4QA000449
workspace=2,monitor:desc:AOC 2475WR F17H4QA000449
workspace=3,monitor:desc:AOC 2475WR F17H4QA000449
workspace=4,monitor:desc:AOC Q27V4G5 SMYNAHA007325
workspace=5,monitor:desc:AOC Q27V4G5 SMYNAHA007325
workspace=6,monitor:desc:AOC Q27V4G5 SMYNAHA007325
workspace=7,monitor:desc:AU Optronics 0xD0ED
workspace=8,monitor:desc:AU Optronics 0xD0ED
workspace=9,monitor:desc:AU Optronics 0xD0ED
workspace=10,monitor:desc:AU Optronics 0xD0ED
workspace=monitor:desc:AOC 2475WR F17H4QA000449,1
workspace=monitor:desc:AOC Q27V4G5 SMYNAHA007325,4
workspace=monitor:desc:AU Optronics 0xD0ED,7
```

This config does not crash Hyprland, but default workspaces per monitor remain unset:

```text
workspace=1,monitor:desc:AOC 2475WR F17H4QA000449,default=true
workspace=2,monitor:desc:AOC 2475WR F17H4QA000449
workspace=3,monitor:desc:AOC 2475WR F17H4QA000449
workspace=4,monitor:desc:AOC Q27V4G5 SMYNAHA007325,default=true
workspace=5,monitor:desc:AOC Q27V4G5 SMYNAHA007325
workspace=6,monitor:desc:AOC Q27V4G5 SMYNAHA007325
workspace=7,monitor:desc:AU Optronics 0xD0ED,default=true
workspace=8,monitor:desc:AU Optronics 0xD0ED
workspace=9,monitor:desc:AU Optronics 0xD0ED
workspace=10,monitor:desc:AU Optronics 0xD0ED
```

[Crash report](https://gist.github.com/nwg-piotr/1da10921232af41b2738efc8cd909fe4)

**Comment by MightyPlaza** [comment]
default:true

**Comment by nwg-piotr** [comment]
Stupid me.

**Comment by nwg-piotr** [comment]
However: it started crashing now.

**Comment by MightyPlaza** [comment]
can repro the crash

**Comment by nwg-piotr** [comment]
Config:

```text
workspace=1,monitor:desc:AOC 2475WR F17H4QA000449,default:true
workspace=2,monitor:desc:AOC 2475WR F17H4QA000449
workspace=3,monitor:desc:AOC 2475WR F17H4QA000449
workspace=4,monitor:desc:AOC Q27V4G5 SMYNAHA007325,default:true
workspace=5,monitor:desc:AOC Q27V4G5 SMYNAHA007325
workspace=6,monitor:desc:AOC Q27V4G5 SMYNAHA007325
workspace=7,monitor:desc:AU Optronics 0xD0ED,default:true
workspace=8,monitor:desc:AU Optronics 0xD0ED
workspace=9,monitor:desc:AU Optronics 0xD0ED
workspace=10,monitor:desc:AU Optronics 0xD0ED
```

Crash report:

```text
--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
All these computers...

Hyprland received signal 11 (Segmentation fault)

Version: 26579fa9627c46af851efea1381e910ea48e3e73
Tag: v0.26.0-107-g26579fa9

System info:
	System name: Linux
	Node name: msi
	Release: 6.4.2-arch1-1
	Version: #1 SMP PREEMPT_DYNAMIC Thu, 06 Jul 2023 18:35:54 +0000

GPU:
	07:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] [1002:15d8] (rev c1) (prog-if 00 [VGA controller])


os-release:
	NAME="Arch Linux"
	PRETTY_NAME="Arch Linux"
	ID=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://archlinux.org/"
	DOCUMENTATION_URL="https://wiki.archlinux.org/"
	SUPPORT_URL="https://bbs.archlinux.org/"
	BUG_REPORT_URL="https://bugs.archlinux.org/"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=archlinux-logo
	


Backtrace:
	#0 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x7f9) [0x55b66306a7a9]
		??
		??:0
	#1 | Hyprland(_Z25handleUnrecoverableSignali+0x44) [0x55b662ffeb14]
		??
		??:0
	#2 | /usr/lib/libc.so.6(+0x39ab0) [0x7f2792e4fab0]
		??
		??:0
	#3 | Hyprland(_ZN14CConfigManager22getDefaultWorkspaceForERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x238) [0x55b66303df78]
		??
		??:0
	#4 | Hyprland(_ZN8CMonitor14setupDefaultWSERK12SMonitorRule+0x68) [0x55b6630a2078]
		??
		??:0
	#5 | Hyprland(_ZN8CMonitor9onConnectEb+0x91a) [0x55b6630a3c3a]
		??
		??:0
	#6 | Hyprland(_ZN6Events18listener_newOutputEP11wl_listenerPv+0xd2) [0x55b663087382]
		??
		??:0
	#7 | /usr/lib/libwayland-server.so.0(wl_signal_emit_mutable+0x7e) [0x7f27937b301e]
		??
		??:0
	#8 | /usr/lib/libwayland-server.so.0(wl_signal_emit_mutable+0x7e) [0x7f27937b301e]
		??
		??:0
	#9 | /usr/lib/libwlroots.so.12032(+0x538eb) [0x7f279384f8eb]
		??
		??:0
	#10 | /usr/lib/libwlroots.so.12032(+0x50099) [0x7f279384c099]
		??
		??:0
	#11 | /usr/lib/libwlroots.so.12032(+0x5f196) [0x7f279385b196]
		??
		??:0
	#12 | Hyprland(_ZN11CCompositor15startCompositorEv+0x2ec) [0x55b66300cfbc]
		??
		??:0
	#13 | Hyprland(main+0x4c6) [0x55b662feec66]
		??
		??:0
	#14 | /usr/lib/libc.so.6(+0x23850) [0x7f2792e39850]
		??
		??:0
	#15 | /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f2792e3990a]
		??
		??:0
	#16 | Hyprland(_start+0x25) [0x55b662ffe9b5]
		??
		??:0


Log tail:
[LOG] Applied config to mouse logitech-logig-tkl-mkeyboard-2, sens 0.00
[LOG] Applied config to mouse 2.4g-mouse-1, sens 0.00
[LOG] Applied config to mouse 2.4g-mouse-consumer-control-1, sens 0.00
[LOG] Applied config to mouse elan2203:00-04f3:30fa-mouse, sens 0.00
[LOG] Applied config to mouse elan2203:00-04f3:30fa-touchpad, sens 0.00
[LOG] Registered signal for owner 55b6648a1eb0: 55b66489cde0 -> 55b6648a1f70 (owner: Mouse)
[LOG] New mouse created, pointer WLR: 55b66489cdc8
[LOG] Attached a keyboard with name AT Translated Set 2 keyboard
[LOG] Registered signal for owner 55b66489d920: 55b66489d530 -> 55b66489d928 (owner: Keyboard)
[LOG] Registered signal for owner 55b66489d920: 55b66489d520 -> 55b66489d990 (owner: Keyboard)
[LOG] Registered signal for owner 55b66489d920: 55b66489d400 -> 55b66489da60 (owner: Keyboard)
[LOG] Registered signal for owner 55b66489d920: 55b66489d540 -> 55b66489d9f8 (owner: Keyboard)
[LOG] ApplyConfigToKeyboard for "at-translated-set-2-keyboard", hasconfig: 0
[LOG] Attempting to create a keymap for layout pl with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to pl and variant to  for keyboard "AT Translated Set 2 keyboard"
[LOG] New keyboard created, pointers Hypr: 55b66489d920 and WLR: 55b66489d3e8
[LOG] Attached a mouse with name ETPS/2 Elantech Touchpad
[LOG] New mouse has libinput sens 0.00 (0.00) with accel profile 2 (2)
[LOG] Applied config to mouse logitech-logig-tkl-mkeyboard-2, sens 0.00
[LOG] Applied config to mouse 2.4g-mouse-1, sens 0.00
[LOG] Applied config to mouse 2.4g-mouse-consumer-control-1, sens 0.00
[LOG] Applied config to mouse elan2203:00-04f3:30fa-mouse, sens 0.00
[LOG] Applied config to mouse elan2203:00-04f3:30fa-touchpad, sens 0.00
[LOG] Applied config to mouse etps/2-elantech-touchpad, sens 0.00
[LOG] Registered signal for owner 55b6648dc230: 55b6648d69d0 -> 55b6648dc2f0 (owner: Mouse)
[LOG] New mouse created, pointer WLR: 55b6648d69b8
[LOG] Attached a keyboard with name MSI WMI hotkeys
[LOG] Registered signal for owner 55b6648d7510: 55b6648d7120 -> 55b6648d7518 (owner: Keyboard)
[LOG] Registered signal for owner 55b6648d7510: 55b6648d7110 -> 55b6648d7580 (owner: Keyboard)
[LOG] Registered signal for owner 55b6648d7510: 55b6648d6ff0 -> 55b6648d7650 (owner: Keyboard)
[LOG] Registered signal for owner 55b6648d7510: 55b6648d7130 -> 55b6648d75e8 (owner: Keyboard)
[LOG] ApplyConfigToKeyboard for "msi-wmi-hotkeys", hasconfig: 0
[LOG] Attempting to create a keymap for layout pl with variant  (rules: , model: , options: )
[LOG] Set the keyboard layout to pl and variant to  for keyboard "MSI WMI hotkeys"
[LOG] New keyboard created, pointers Hypr: 55b6648d7510 and WLR: 55b6648d6fd8
[LOG] Adding completely new monitor.
[LOG] Registered signal for owner 55b664910990: 55b664910770 -> 55b664910ba8 (owner: )
[LOG] Registered signal for owner 55b664910990: 55b664910800 -> 55b664910c10 (owner: )
[LOG] Registered signal for owner 55b664910990: 55b6649107f0 -> 55b664910c78 (owner: )
[LOG] Registered signal for owner 55b664910990: 55b664910780 -> 55b664910ce0 (owner: )
[LOG] Registered signal for owner 55b664910990: 55b664910790 -> 55b664910d48 (owner: )
[LOG] Registered signal for owner 55b664910990: 55b6649107b0 -> 55b664910db0 (owner: )
[LOG] Registered signal for owner 55b664910990: 55b6649107d0 -> 55b664910e18 (owner: )
[LOG] Applying monitor rule for eDP-1
[LOG] Monitor eDP-1: requested 1920x1080@120.113998, found available mode: 1920x1080@120114mHz, applying.
[LOG] Monitor eDP-1 -> destroyed all render data
[LOG] Monitor eDP-1 layers arranged: reserved: 0.000000 0.000000 0.000000 0.000000
[LOG] Monitor eDP-1 data dump: res 1920x1080@120.11Hz, scale 1.00, transform 0, pos 3760x415, 10b 0
[LOG] Overriding XWayland scale with 0.00
[LOG] Added new monitor with name eDP-1 at 3760,415 with size 1920x1080, pointer 55b664910620

```

**Comment by MightyPlaza** [comment]
seems to be due to putting workspace number in the end
not sure if this is a parsing error or should be allowed

**Comment by nwg-piotr** [comment]
What should the config look like according to you?

**Comment by MightyPlaza** [comment]
image
1st the workspace number/name then the rule
should give parsing error not crash though

**Comment by nwg-piotr** [comment]
Well, `workspace=1,monitor:desc:AOC 2475WR F17H4QA000449,default:true` looks like this, doesn't it?

**Comment by MightyPlaza** [comment]
looks like it's crashing when I use something other than "Wayland output" on a embedded session which is where I tested it

**Comment by nwg-piotr** [comment]
If I can help at testing, let me know.

**Comment by MightyPlaza** [comment]
can repro all issues, will try to get everything working and handle all issues and make a PR in the next 3 hours

**Comment by nwg-piotr** [comment]
Very well. I'll test as soon as I can, as it's 2:30 am in my place.

**Comment by nwg-piotr** [comment]
And I'm still here :D

**Comment by MightyPlaza** [comment]
found the cause
workspace=6, monitor:desc:LG Electronics LG FULL HD 0x000785DB (HDMI-A-2), default:true
unlike monitor conf it needs the port to be specified
will try to fix it now, but specifying it might fix the crashes and make it work for now

**Comment by nwg-piotr** [comment]
It'll be impossible to specify the port name for people that do need to use monitor names (Thunderbird and so on).

**Comment by MightyPlaza** [comment]
I know, I'm working on removing it but if you specify the port on curr version it should work

**Comment by nwg-piotr** [comment]
All right. Can't check, however, as I'm already in my bed. The alarm clock will ring in 3 hours. :)

**Comment by MightyPlaza** [comment]
actually working now https://github.com/hyprwm/Hyprland/pull/2678

**Pull request merged**
