### PR TITLE
build: Set cmake_minimum_required to version 3.30

### PR DESCRIPTION
**Pull request by davc0n**
ref. https://github.com/hyprwm/Hyprland/issues/7707

### CODE REVIEW

**Comment by vaxerski** [comment]
@fufexan for nix ci

**Comment by fufexan** [comment]
@vaxerski see the linked issue. There's nothing I can do until https://github.com/NixOS/nixpkgs/pull/328256.

**Comment by vaxerski** [comment]
I have read that. Can't nix patch cmakelists until that is merged and keep the old patch (adding `-std` to the cc)?

**Comment by fufexan** [comment]
Yeah I guess.

**Review by fufexan — APPROVED** [review]
LGTM. Can be merged after CI passes.

**Pull request merged**
