### PR TITLE
Hyprland-systemd.desktop improvements

### PR DESCRIPTION
**Pull request by izmyname**
#### Describe your PR, what does it fix/add?

Rename Hyprland to Hyprland (systemd session) to differentiate it from non-systemd Hyprland.desktop, add missing keywords.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)

No

#### Is it ready for merging, or does it need work?

Yes

### CODE REVIEW

**Review by fufexan — APPROVED** [review]

**Comment by b4shful** [comment]
Heads up, while I appreciate being able to tell the two desktop entries apart, it seems that this update breaks launching hyprland-systemd from [uwsm](https://github.com/Vladimir-csp/uwsm)

```
Nov 01 17:44:43 lobster-framework-arch systemd[1009]: Created slice User Background Tasks Slice.
Nov 01 17:44:43 lobster-framework-arch systemd[1009]: Starting Bind graphical session to PID 1130...
Nov 01 17:44:43 lobster-framework-arch systemd[1009]: Started Bind graphical session to PID 1130.
Nov 01 17:44:43 lobster-framework-arch systemd[1009]: Starting Environment preloader for Hyprland (systemd session), An intelligent dynamic tiling Wayland compositor...
Nov 01 17:44:43 lobster-framework-arch uwsm_env-preloader[1139]: Got malformed desktop names: "Hyprland (systemd session):systemctl"!
Nov 01 17:44:43 lobster-framework-arch systemd[1009]: wayland-wm-env@hyprland\x2dsystemd.desktop.service: Main process exited, code=exited, status=1/FAILURE
Nov 01 17:44:43 lobster-framework-arch systemd[1009]: wayland-wm-env@hyprland\x2dsystemd.desktop.service: Failed with result 'exit-code'.
Nov 01 17:44:43 lobster-framework-arch systemd[1009]: Failed to start Environment preloader for Hyprland (systemd session), An intelligent dynamic tiling Wayland compositor.
Nov 01 17:44:43 lobster-framework-arch systemd[1009]: Dependency failed for Preparation for session of hyprland-systemd.desktop Wayland compositor.
Nov 01 17:44:43 lobster-framework-arch systemd[1009]: Dependency failed for Main service for Hyprland (systemd session), An intelligent dynamic tiling Wayland compositor.
Nov 01 17:44:43 lobster-framework-arch systemd[1009]: Dependency failed for Session of hyprland-systemd.desktop Wayland compositor.
Nov 01 17:44:43 lobster-framework-arch systemd[1009]: wayland-session@hyprland\x2dsystemd.desktop.target: Job wayland-session@hyprland\x2dsystemd.desktop.target/start failed with result 'dependency'.
Nov 01 17:44:43 lobster-framework-arch systemd[1009]: wayland-wm@hyprland\x2dsystemd.desktop.service: Job wayland-wm@hyprland\x2dsystemd.desktop.service/start failed with result 'dependency'.
Nov 01 17:44:43 lobster-framework-arch systemd[1009]: wayland-wm@hyprland\x2dsystemd.desktop.service: Triggering OnFailure= dependencies.
Nov 01 17:44:43 lobster-framework-arch systemd[1009]: wayland-session-pre@hyprland\x2dsystemd.desktop.target: Job wayland-session-pre@hyprland\x2dsystemd.desktop.target/start failed with result 'dependency'.
Nov 01 17:44:43 lobster-framework-arch systemd[1009]: wayland-wm-env@hyprland\x2dsystemd.desktop.service: Triggering OnFailure= dependencies.
Nov 01 17:44:43 lobster-framework-arch systemd[1009]: Stopping Bind graphical session to PID 1130...
Nov 01 17:44:43 lobster-framework-arch systemd[1009]: Stopped Bind graphical session to PID 1130.
Nov 01 17:44:43 lobster-framework-arch systemd[1009]: wayland-session-bindpid@1130.service: Triggering OnSuccess= dependencies.
Nov 01 17:44:43 lobster-framework-arch systemd[1009]: Reached target Shutdown graphical session units.
Nov 01 17:44:43 lobster-framework-arch systemd[1009]: Stopped target Shutdown graphical session units.
```

I don't see anything in the desktop entry spec which would require no spaces in the name, so idk what's going on.

**Comment by fufexan** [comment]
Maybe it's a uwsm bug. If it turns out not to be, we can change the name.

**Comment by izmyname** [comment]
@b4shful  try renaming `DesktopNames=Hyprland (systemd session)` to `DesktopNames=Hyprland` in `/usr/share/wayland-sessions/hyprland-systemd.desktop`. Let me know if it works and how it affects the Hyprland entry's name. Ideally, it should still be named Hyprland (systemd session).

I can't test it myself, since I use neither uwsm nor a display manager.

**Comment by b4shful** [comment]
@izmyname Hi, apologies for the delay on my end, hadn't gotten round to this until now.

I renamed `DesktopNames=Hyprland (systemd session)` to `DesktopNames=Hyprland` and indeed uwsm began working again. 

Here's what shows when I run `uwsm select` after modifying the `hyprland-systemd.desktop` file:

image

Seems like the session name is still "Hyprland (systemd session)".

Also as @fufexan mentioned, this could be a UWSM bug, I'm not sure. DesktopNames is very poorly documented in the XDG spec, no idea if it's allowed to have spaces or not.

**Comment by fufexan** [comment]
@Vladimir-csp is this an issue on our end?

**Comment by Vladimir-csp** [comment]
It's not really about compatibility with uwsm or DMs. Judging purely by some [examples](https://wiki.archlinux.org/title/Environment_variables#Examples), dash is ok, at least Gnome does it. So `Hyprland-systemd` would be fine, although is it really needed?

`DesktopNames` key serves to fill `XDG_CURRENT_DESKTOP`, `XDG_SESSION_DESKTOP`. Primary consumers are autostart solutions, portals, and any apps that [have](https://specifications.freedesktop.org/mime-apps-spec/latest/file.html) to be session-aware (apps opening files in other apps). Values are used in, among other things, file paths. Having a `/home/username/.config/Hyprland (systemd session)-mimeapps.list` would be weird.

It is still Hyprland session, but effectively with a different autostart solution (systemd `xdg-desktop-autostart.target` instead of, say, dex). If a differentiation is needed it can be , use `Hyprland;Hyprland-systemd`. Or  `Hyprland-systemd;Hyprland` to put -systemd variant into more specific spot. Personally I would leave it just `Hyprland`.

**Comment by izmyname** [comment]
> `DesktopNames` key serves to fill `XDG_CURRENT_DESKTOP`, `XDG_SESSION_DESKTOP`

Hm. In this case, I suggest leave DesktopNames=Hyprland in https://github.com/hyprwm/Hyprland/pull/8351 to avoid any headaches with those variables. We can differentiate systemd and no-systemd desktop entry solely by their `Name= ` values. 

@fufexan, thoughts?

**Comment by fufexan** [comment]
Sure, let's do that then.

**Comment by b4shful** [comment]
@Vladimir-csp 
> BTW, starting it via uwsm makes little to no sense anyway.

What did you mean by this?

I was playing around with uwsm as I used to just start Hyprland from the standard tty, but if you exit Hyprland this way you get a bunch of segfaults and other mess. It seems like a nice alternative to login/display managers and helps in achieving the "real computer" feel, rather than just being dumped into the tty when you log in.

**Comment by izmyname** [comment]
Probably, @Vladimir-csp means, that starting hyprland-session.service via uwsm makes little sense, because uwsm already wraps Hyprland session into systemd units. This is the whole point.

**Comment by Vladimir-csp** [comment]
Starting this systemd session variant via uwsm makes no sense. Compositor unit will end up containing only `systemctl ...` process, real compositor will be in its own unit, proper stop sequence and login session bind will probably not work.

**Comment by b4shful** [comment]
Ah, I wasn't paying enough attention to this and have only just realised @Vladimir-csp is the author of uwsm :laughing: 

Since the desktop file is fixed anyways I should probably cease the discussion below this PR.

But just for clarification, in my case how should I launch Hyprland if using uwsm?

**Comment by Vladimir-csp** [comment]
> But just for clarification, in my case how should I launch Hyprland if using uwsm?

By starting `hyprland.desktop` or `Hyprland` in uwsm. https://github.com/Vladimir-csp/uwsm#where-to-launch-from

**Comment by b4shful** [comment]
Awesome, thanks so much to everyone for being so receptive and responsive to the feedback! <3

**Pull request merged**
