### PR TITLE
Remove nvidia patches

### PR DESCRIPTION
**Pull request by vaxerski**
Nvidia patches are no longer doing anything.

cc @fufexan I tried to fix nix but I don't know if I did it right :)

### CODE REVIEW

**Comment by fufexan** [comment]
You did a pretty good job there.

**Review by fufexan — APPROVED** [review]

**Comment by vaxerski** [comment]
thanks qt

**Comment by vaxerski** [comment]
because it wasn't doing anything anymore, and the logic it used to work based on is now implemented directly in hyprland

**Comment by Eclextic** [comment]
> because it wasn't doing anything anymore, and the logic it used to work based on is now implemented directly in hyprland

Does that mean NVIDIA is now implicitly supported by that logic?

**Comment by vaxerski** [comment]
no

**Pull request merged**
