### PR TITLE
Allow fullscreen/maximize in special workspace

### PR DESCRIPTION
**Pull request by thejch**
Closes https://github.com/hyprwm/Hyprland/issues/2173
Closes https://github.com/hyprwm/Hyprland/issues/1285

Briefly tested dwindle/master/floating, special/non-special, fullsreen/maximize

### CODE REVIEW

**Comment by vaxerski** [comment]
bugger: special fs don't lose deco

**Comment by thejch** [comment]
> bugger: special fs don't lose deco

Yea somehow missed that since I didn't have rounding. Should be fixed now

**Comment by vaxerski** [comment]
bugger: unfullscreening a window makes it maximized

**Comment by thejch** [comment]
> bugger: unfullscreening a window makes it maximized (regardless of workspace)

hmmm I can't reproduce that. I've been using this branch for a few days now and didn't see anything similar

**Comment by vaxerski** [comment]
ok dafoq the bug went away

**Review by vaxerski — APPROVED** [review]
oke thanks

**Comment by NickHackford** [comment]
Testing this and found an interesting edge case. When a special workspace has a fullscreen browser, toggling the space away, targeting a different screen and toggling the space on again draws an empty special workspace. The browser won't show on the second monitor until I return the special workspace to the original monitor it was full screened on and turn full screen off.

**Comment by vaxerski** [comment]
@thejch you up to fix that?

**Comment by thejch** [comment]
> @thejch you up to fix that?

Reproducible so I can probably take a look when i have time

**Pull request merged**
