### PR TITLE
Add bringWindowToTop function to IHyprLayout

### PR DESCRIPTION
**Pull request by outfoxxed**
#### Describe your PR, what does it fix/add?
Exposes window toplevel activate as a layout function.
Required for outfoxxed/hy3#7

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
No

#### Is it ready for merging, or does it need work?
Ready for merge

### CODE REVIEW

**Review by vaxerski — COMMENTED** [review]
this does not bring the window to the top. it only focuses it.

**Comment by outfoxxed** [comment]
Would `requestWindowFocus` be a better name?

**Comment by vaxerski** [comment]
ye

**Comment by outfoxxed** [comment]
Done

**Review by vaxerski — APPROVED** [review]
k

**Pull request merged**
