### PR TITLE
Enable explicit out fence in AQ

### PR DESCRIPTION
**Pull request by UjinT34**
#### Describe your PR, what does it fix/add?
Enables explicit out fences

#### Is it ready for merging, or does it need work?
Requires https://github.com/hyprwm/aquamarine/pull/105

### CODE REVIEW

**Comment by vaxerski** [comment]
@fufexan nix needs aq bump

**Review by vaxerski — APPROVED** [review]

**Comment by Fxzzi** [comment]
After this MR, osu!lazer is now locked to my screen refresh rate of 170Hz. Whilst previously it could go above to 340fps, it can no longer and it always stays below that.

**Comment by UjinT34** [comment]
https://github.com/hyprwm/Hyprland/issues/8482 kms explicit sync prevents tearing

**Comment by Fxzzi** [comment]
> #8482 kms explicit sync prevents tearing

Ty, is this intended behaviour? Id assume not

**Comment by UjinT34** [comment]
Not really. It is unclear how much of the explicit sync should be disabled and when. The issue comes from the explicit out fence support. It could be conditionally disabled when tearing is active but it doesn't feel right.

**Comment by ferrreo** [comment]
@UjinT34 kwin seems to handle this fine, it looks like it doesn't fence while tearing: https://invent.kde.org/plasma/kwin/-/merge_requests/4800/diffs

**Pull request merged**
