### PR TITLE
hyprpm: fix hyrpm sometimes returning 0 despite errors occuring

### PR DESCRIPTION
**Pull request by alba4k**
#### Describe your PR, what does it fix/add?
This PR changes `hyprpm`'s return codes in a couple of misusage situations, mainly when `hyprpm reload` fails because of headers being out of date. This, alongside with being a behavior most people would expect, as the command did not, in fact, execute successfully, makes some basic scripting like `hyprpm reload 2>&1 | grep "not up-to-date" && hyprpm update` easier (the example can be reduced to `hyprpm reload || hyprpm update`)

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
no.

#### Is it ready for merging, or does it need work?
should be good to go, as it doesn't really change anything significant. Still, lmk if you'd like anything to act differently

### CODE REVIEW

**Review by vaxerski — APPROVED** [review]
thanks!

**Comment by alba4k** [comment]
immagine
mhhhh wdym

**Comment by alba4k** [comment]
fixed. However, take a look at it. I changed it because it was horrible and inconsistent (literally the following lines use a different and more readable style). idk why clang-format wants that, it honestly sucks, but whatever. if you want clang-format to pass, it does now

**Review by vaxerski — APPROVED** [review]
lgtm thanks qt

also dont ping me it doesnt do shit

**Comment by alba4k** [comment]
sure

**Pull request merged**
