### PR TITLE
debug: fix ISDEBUG checking

### PR DESCRIPTION
**Pull request by alyanser**
#### Describe your PR, what does it fix/add?
`ISDEBUG` macro is always defined so checking it with `#ifdef` is a bug. Use `#if ISDEBUG` instead. 

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
No.

#### Is it ready for merging, or does it need work?
Ready to merge.

### CODE REVIEW

**Review by vaxerski — APPROVED** [review]
thanks!

**Comment by solopasha** [comment]
Please apply this again after force pushing 2a24a61126dcebd2e1f7862e5c21c105900110ac

**Comment by vaxerski** [comment]
oops shit my bad lmao

**Comment by vaxerski** [comment]
done

**Pull request merged**
