### PR TITLE
fix zsh completion in hyprctl

### PR DESCRIPTION
**Pull request by random2907**
#### Describe your PR, what does it fix/add?
it fixes hyprctl completion in zsh.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
No.

#### Is it ready for merging, or does it need work?
yes its ready.

### CODE REVIEW

**Comment by fufexan** [comment]
It works fine on my end though, what's not working properly?

**Comment by random2907** [comment]
> It works fine on my end though, what's not working properly?

its not working in zsh , i have to manually load it . this problem doesnt happen in hyprpm completion because there it is already defined but missing in hyprctl . It is a requirement for zsh-completion to load a completion function.

**Comment by random2907** [comment]
> > It works fine on my end though, what's not working properly?
> 
> It is a requirement for zsh-completion to autoload a completion function. same as this #5503. it got removed in #6380

**Comment by leon-erd** [comment]
Can confirm the issue. Its also not working on my end since these lines got removed.

**Review by fufexan — APPROVED** [review]
Forgot about this, sorry. LGTM

**Pull request merged**
