### PR TITLE
Nix: fix #2833 on stable NixOS

### LINKED ISSUE #2833: c36c30c breaks systems running on stable NixOS
### Hyprland Version

Hyprland, built from branch  at commit 2ea7d10d049e26c9829912da1d16f7f35f5b265d  (). Tag: ?  flags: (if any) debug

### Bug or Regression?

Regression

### Description

Commit c36c30c breaks my config. I'm running on the `nixos-23.05` channel where this option does not exist yet, resulting in an error. This could probably be fixed using version checks and `lib.mkIf`.

### How to reproduce

Try building a nixosConfiguration with the latest Hyprland NixOS module, using `nixos-23.05` as the `nixpkgs` channel or flake input. Example with flakes:

```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-23.05";
    hyprland.url = "github:hyprwm/Hyprland";
  };

  outputs = { nixpkgs, hyprland, ... }: {
    nixosConfigurations.default = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        # All of this is needed for `nix flake check` to pass in any case
        {
          fileSystems."/" = {
            device = "/dev/disk/by-label/nixos";
            fsType = "ext4";
          };

          boot.loader.grub.devices = [ "nodev" ];

          system.stateVersion = "23.05";
        }


        hyprland.nixosModules.default
        { programs.hyprland.enable = true; }
      ];
    };
  };
}
```
And run `nix flake check`.

### Crash reports, logs, images, videos
```
error:
       … while checking flake output 'nixosConfigurations'

         at /nix/store/dqz8hi4xci44cwd86i3lbr4flxkh9xs2-source/flake.nix:12:5:

           11|   outputs = { nixpkgs, hyprland, ... }: {
           12|     nixosConfigurations.default = nixpkgs.lib.nixosSystem {
             |     ^
           13|       system = "x86_64-linux";

       … while checking the NixOS configuration 'nixosConfigurations.default'

         at /nix/store/dqz8hi4xci44cwd86i3lbr4flxkh9xs2-source/flake.nix:12:5:

           11|   outputs = { nixpkgs, hyprland, ... }: {
           12|     nixosConfigurations.default = nixpkgs.lib.nixosSystem {
             |     ^
           13|       system = "x86_64-linux";

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: The option `fonts.enableDefaultPackages' does not exist. Definition values:
       - In `/nix/store/mf8fml0rgprprwxx86wq76b92pilr26l-source/flake.nix':
           {
             _type = "if";
             condition = true;
             content = {
               _type = "override";
           ...
```

### PR DESCRIPTION
**Pull request by CnTeng**
fix #2833 

I think it works, but need test. @fufexan

### CODE REVIEW

**Comment by CnTeng** [comment]
I have a mistake,
Maybe 

```nix
fonts =
  if versionOlder config.system.stateVersion "23.11"
  then {enableDefaultPackages = mkDefault true;}
  else {enableDefaultFonts = mkDefault true;};
```
works, but it is a little weird

**Comment by fufexan** [comment]
It should work. @CnTeng do you wish to continue with this PR?

**Comment by CnTeng** [comment]
@fufexan Ok, but I can't reopen this pr. Or, I open a new one ?

**Comment by fufexan** [comment]
You can reopen the PR by pushing new commits to this branch.
You can do `git reset HEAD^` and it will let you "edit" the latest commit. `git rebase -i HEAD` and choosing `edit` also works.

**Comment by gekoke** [comment]
> I have a mistake, Maybe
> 
> ```nix
> fonts =
>   if versionOlder config.system.stateVersion "23.11"
>   then {enableDefaultFonts = mkDefault true;}
>   else {enableDefaultPackages = mkDefault true;};
> ```
> 
> works, but it is a little weird

This is the correct solution, I believe. I think you can only use `mkRenamedOptionModule` in the module definition itself.

Shouldn't it be `versionOlder config.system.stateVersion "23.05"` or `versionAtLeast config.system.stateVersion "23.11"`, though?

**Comment by CnTeng** [comment]
> > I have a mistake, Maybe
> > ```nix
> > fonts =
> >   if versionOlder config.system.stateVersion "23.11"
> >   then {enableDefaultFonts = mkDefault true;}
> >   else {enableDefaultPackages = mkDefault true;};
> > ```
> > works, but it is a little weird
> 
> This is the correct solution, I believe. I think you can only use `mkRenamedOptionModule` in the module definition itself.
> 
> Shouldn't it be `versionOlder config.system.stateVersion "23.05"` or `versionAtLeast config.system.stateVersion "23.11"`, though?

I think `mkRenamedOptionModule` just can rename `enableDefaultFonts` to `enableDefaultPackages`, I have del the old brunch. 

@fufexan I think maybe you can have a better one.

**Pull request closed without merging**
