### PR TITLE
Move globalshortcuts impl

### PR DESCRIPTION
**Pull request by ikalco**
#### Describe your PR, what does it fix/add?
also removed wayland-scanner dep

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
cmake and meson both compile for me
but someone should double check them to make sure I didn't do something wrong

also khotkeys is gone soo.... idk how to test

#### Is it ready for merging, or does it need work?
prob yes ^

### CODE REVIEW

**Comment by vaxerski** [comment]
try mumble, that was my test case (it has a gs dbus MR)

**Comment by ikalco** [comment]
im about to got somewhere but will test when i get back

**Comment by ikalco** [comment]
that pr is broken on main too lol
somehow doesnt receive keypresses when setting shortcuts

**Comment by ikalco** [comment]
just tested and fixed the impl, also rebased to main and fixed the conflict
should be gtg

for future testing use [this](https://invent.kde.org/libraries/xdg-portal-test-kde) with Ex. `bind = SUPER,A,global,:AwesomeTrigger`
* compile and open xdg-portal-test-kde
* hit configure shortcuts
* use above keybinding (the `:AwesomeTrigger` is the trigger set by the app)
* it should say activated to the right of that button until you let go, then it will say deactivated

**Review by vaxerski — APPROVED** [review]
thanks!

**Pull request merged**
