### PR TITLE
Fix movefocus in special workspace sometimes moving the focus into the main workspace

### LINKED ISSUE #3624: Moving focus in special workspace sometimes moves the focus into the main workspace
### Hyprland Version

Hyprland, built from branch main at commit 386708563c3d9d85ffd60b4eeb6c767d29f948db dirty (workspacerules: search for special properly). Tag: v0.31.0-12-g38670856

### Bug or Regression?

Bug

### Description

Moving focus in special workspace sometimes moves the focus into the main workspace
Same for movewindow
Happens in both dwindle and master

### How to reproduce

Use the example config, but add this script to exec-once=path/to/test.sh
```bash
#!/bin/sh
# content of test.sh

sleep 3 ; kitty &
hyprctl keyword dwindle:default_split_ratio 0.9;
hyprctl dispatch layoutmsg preselect l;
sleep 1 ; kitty &
sleep 1 ; hyprctl dispatch togglespecialworkspace;
sleep 1 ; kitty &
hyprctl dispatch layoutmsg preselect l;
sleep 1 ; kitty &
sleep 1 ; hyprctl dispatch togglespecialworkspace;
sleep 1 ; hyprctl dispatch togglespecialworkspace;
sleep 1 ; hyprctl dispatch movefocus r;
sleep 1 ; hyprctl dispatch movefocus l;
sleep 1 ; hyprctl dispatch movefocus r;
sleep 1 ; hyprctl dispatch movefocus l;
sleep 1 ; hyprctl dispatch movefocus r;
sleep 1 ; hyprctl dispatch movefocus l
```
and you will see that the focus is moving between the special workspace and the main one

### Crash reports, logs, images, videos

_No response_

### PR DESCRIPTION
**Pull request by thejch**
#### Describe your PR, what does it fix/add?
Fix: movefocus in special workspace occasionally moves the focus into the main workspace
same for movewindow
Fixes #3624 

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
No

#### Is it ready for merging, or does it need work?
Ready

### CODE REVIEW

**Review by vaxerski — COMMENTED** [review]
why not just compare workspace ids directly

**Comment by thejch** [comment]
If you compare workspace IDs and only move within the same workspace, you won't be able to move between monitors, if that's what you mean

**Comment by vaxerski** [comment]
but you check for monitor equality

**Comment by thejch** [comment]
true, forgot about that

**Comment by thejch** [comment]
Changed

**Review by vaxerski — APPROVED** [review]
lgtm

**Pull request merged**
