### PR TITLE
Added clang format

### PR DESCRIPTION
**Pull request by vaxerski**
Added clang-format for future PRs, (and my sanity a bit) and formatted all files.

@fufexan do you know maybe if we can:
a)
`AlignConsecutiveDeclarations` across both empty lines and comments, tried to do it how clang's docs say:
```
AlignConsecutiveDeclarations:
  Enabled: true
  AcrossEmptyLines: true
  AcrossComments: true
````
but it would break the entire formatter in vs code (?)

b) 
make enum not wrap
```
BraceWrapping:
  AfterEnum: 'false'
```
doesn't seem to work, see
https://github.com/hyprwm/Hyprland/blob/63b2e1f138c5abf31890df51fa01af389f445904/src/debug/Log.hpp#L7-L15

### CODE REVIEW

**Comment by Dickby** [comment]
@vaxerski  
for the first alignment thing try setting AlignOperants to true.
the second thing might be solved by setting BreakBeforeBraces to 'custom'

**Comment by vaxerski** [comment]
both didn't work for me :/

**Comment by Dickby** [comment]
Your config is working for me if i add this:

BreakBeforeBraces: Custom
BraceWrapping:
    AfterEnum: false
    AfterStruct: false
    AfterUnion: false
    AfterControlStatement: false
    AfterFunction: false
   


The 'Enabled: true' could be the problem

**Comment by vaxerski** [comment]
it don't for me but oh well thats minor

**Comment by vaxerski** [comment]
I'll merge this and if someone finds a way to make it work, feel free to mr

**Pull request merged**
