### PR TITLE
Add support for linux-drm-syncobj-v1

### PR DESCRIPTION
**Pull request by lucasreis1**
#### Describe your PR, what does it fix/add?
Adds support for linux-drm-syncobj-v1, the new explicit sync protocol. 

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
This **stricitly depends** on the [wlroots MR](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4262). Also, I'm heavily copying Simon's implementation on sway (https://github.com/swaywm/sway/pull/8156).

#### Is it ready for merging, or does it need work?
Draft for now while I follow both wlroots and sway's implementation. Comments from mantainers welcome to ensure this code makes any sense :)

### CODE REVIEW

**Comment by vaxerski** [comment]
if only it was that easy. It absolutely won't work unfortunately as just like you said on discord "the heavy load seems to be done entirely on wlroots", but we don't use those modules of wlroots _at all_, so all the heavylifting needs to be implemented here separately :)

**Comment by lucasreis1** [comment]
> but we don't use those modules of wlroots at all

Do you mean the ones added by the new MR for explicit sync? This PR is done expecting these to be merged to hyprland's fork

**Comment by vaxerski** [comment]
the changes are done to scene, renderer, and render_pass, all of which are not used in hl

**Comment by lucasreis1** [comment]
Yeah, I see it now. Thanks for the input Vaxry

**Pull request closed without merging**
