### PR TITLE
Better naming

### PR DESCRIPTION
**Pull request by akane6704**
This PR fixes "bad" naming, substituting characters with words
The PR is ready for merging

### CODE REVIEW

**Comment by vaxerski** [comment]
please never touch a line of code again

**Comment by joshcancode** [comment]
> This PR fixes "bad" naming, substituting characters with words The PR is ready for merging

I can't believe I just read this. Do you know what an operator override is?

**Comment by akane6704** [comment]
oh wait.

**Comment by akane6704** [comment]
fix my drunkness

**Pull request closed without merging**
