### PR TITLE
type conversion to new types to avoid unsigned int rollover and signed int overflow

### PR DESCRIPTION
**Pull request by gulafaran**
unsigned int = -1 rolls over to unsigned int max, avoid rolling over by using the new typedefs WORKSPACEID/MONITORID/WINDOWID where this occured and also since we were rolling over getmonitorid() was passed a unsigned int max value and overflowed causing UB.

as a consequence of this turning on -Wshorten-64-to-32 revealed a few other mismatches related or close to same place where i changed the type to the correct  one when refactoring. still remains a few in other places but thats for a future PR.

the opengl changes im not sure about if they are correct, requires a keen eye what the intention behind the stencil calls were but same deal there, -1 to gluint rolls over to uint max.

### CODE REVIEW

**Review by vaxerski — COMMENTED** [review]
please do what I said with the typedefs just for the sake of having it done

**Comment by gulafaran** [comment]
> please do what I said with the typedefs just for the sake of having it done

any particular file you want those typedefs in

**Comment by vaxerski** [comment]
sharedDefs?

**Comment by gulafaran** [comment]
> sharedDefs?

onto it!

**Comment by vaxerski** [comment]
si

**Comment by gulafaran** [comment]
> si

unless i typoed something, something like this?

**Comment by vaxerski** [comment]
yeah

lmk when done

**Comment by gulafaran** [comment]
> yeah
> 
> lmk when done

ok this went rather overboard, changed a few types and more and more and more until WORKSPACEID/MONITORID/WINDOWID was done. turned on -Wshorten-64-to-32 and fixed the related warnings and while i was there the other ones not related.

**Comment by gulafaran** [comment]
> > yeah
> > lmk when done
> 
> ok this went rather overboard, changed a few types and more and more and more until WORKSPACEID/MONITORID/WINDOWID was done. turned on -Wshorten-64-to-32 and fixed the related warnings and while i was there the other ones not related.

there is still a few warnings remaining around -Wshorten-64-to-32 but thats for another PR cant catch it all in one sweep heh

**Comment by gulafaran** [comment]
yeah id call it ready for review

**Comment by vaxerski** [comment]
or would you?

**Review by vaxerski — COMMENTED** [review]
could we also get `MONITOR_INVALID` macros (like `WORKSPACE_INVALID`) for -1?

**Comment by gulafaran** [comment]
> could we also get `MONITOR_INVALID` macros (like `WORKSPACE_INVALID`) for -1?

When there's a will, there's a way — that way is code.

sure

**Comment by gulafaran** [comment]
> could we also get `MONITOR_INVALID` macros (like `WORKSPACE_INVALID`) for -1?

done

**Review by vaxerski — APPROVED** [review]
cheers, love ya

**Pull request merged**
