### PR TITLE
Scale the border size, revert the window scaling according to border

### PR DESCRIPTION
**Pull request by Dickby**
#### Describe your PR, what does it fix/add?
This reverts https://github.com/hyprwm/Hyprland/pull/727
and i hope it Fixes https://github.com/hyprwm/Hyprland/issues/731

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
Somebody should try it, apparently i'm not very smart!
#### Is it ready for merging, or does it need work?
Ready

### CODE REVIEW

**Comment by vaxerski** [comment]
@fufexan

**Comment by fufexan** [comment]
image
Idk if this looks fine or not.

**Comment by Dickby** [comment]
@fufexan that gap wasn't there before?

**Comment by Dickby** [comment]
border_size and monitor scale?

**Comment by fufexan** [comment]
@Dickby border_size 2 and scale 1.6.

**Comment by Dickby** [comment]
@fufexan can you check if that gap changes its size bigger by changing the border size?

**Comment by fufexan** [comment]
@Dickby seems like it's the same regardless of border size.

**Comment by Dickby** [comment]
@fufexan try an integer value please

**Comment by fufexan** [comment]
Yes actually. I've seen the gap there at 1.1, 1.2, 1.6, 1.9x scaling. Also it only happens at certain border sizes, like 2 and 7. Weird bug.

**Comment by Dickby** [comment]
That's good information.
I will check.

**Comment by Dickby** [comment]
@fufexan can you check if that gap is still there?

**Comment by Dickby** [comment]
@fufexan can you please check this, there is a good chance that this gap is fixed!

**Comment by fufexan** [comment]
@Dickby you're right, it's fixed! Sorry for the late response.

**Review by fufexan — APPROVED** [review]

**Comment by vaxerski** [comment]
ready to merge or still pending changes?

**Comment by Dickby** [comment]
Ready!

**Pull request merged**
