### PR TITLE
free more memory on destruction

### PR DESCRIPTION
**Pull request by gulafaran**
with these most direct leaks reported by asan should be handled, the only thing remaining is the shared/weakptr reports and a few indirect ones inside wlroots/libwayland which im not sure if its just false positives.

### CODE REVIEW

**Review by vaxerski — DISMISSED** [review]
thanks!

**Comment by vaxerski** [comment]
uhh clang format

**Comment by gulafaran** [comment]
> uhh clang format

Im trying to figure out what it needs, effing arch being outdated 🥺

**Comment by gulafaran** [comment]
"/__w/Hyprland/Hyprland/src/desktop/Popup.cpp:138:6: error: code should be clang-formatted [-Wclang-format-violations" i mean i didnt even touch that file lol

**Comment by gulafaran** [comment]
> uhh clang format

yeah i think it comes from this commit https://github.com/hyprwm/Hyprland/commit/155fe6f165f70ea69a44cbd6989fc01a473e6946 heh

**Comment by vaxerski** [comment]
just clang-format this and I'll merge it and we'll be done

**Review by vaxerski — APPROVED** [review]
tanks

**Pull request merged**
