### PR TITLE
Animation popout

### PR DESCRIPTION
**Pull request by littleblack111**
#### Describe your PR, what does it fix/add?
Adds a popout animation

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
Rn only for closing windows work

#### Is it ready for merging, or does it need work?
not ready

### CODE REVIEW

**Comment by littleblack111** [comment]
please tell me if this is a good idea or no?

**Comment by littleblack111** [comment]
ah shit based off the wrong branch..

**Comment by vaxerski** [comment]
whats the difference from popin?

**Comment by littleblack111** [comment]
it pops from the window original size to outer(display size etc specified by the %)

**Comment by vaxerski** [comment]
isnt that stupid

**Comment by littleblack111** [comment]
Elaborate pls?

**Comment by vaxerski** [comment]
I don't see the point

**Comment by littleblack111** [comment]
i mean.. its an animation, but alright

**Comment by littleblack111** [comment]
ngl, i still wanna add the animation. it'd look sth like this(idk how but i created it by accident via hyprctl when making a script): https://drive.google.com/file/d/1Y_WSlQPyFwqPo8IAc6Dc4wRbgWOGdAKd/view?usp=sharing

**Pull request closed without merging**
