### PR TITLE
flake.lock: update xdph

### PR DESCRIPTION
**Pull request by Gliczy**
#### Describe your PR, what does it fix/add?
Update xdph to v1.3.8

#### Is it ready for merging, or does it need work?
Ready

### CODE REVIEW

**Comment by fufexan** [comment]
Can you update xdph again? This time it should build.

**Comment by Gliczy** [comment]
Done, it build correctly now.

**Comment by Gliczy** [comment]
@fufexan This should be good to go. I removed the `nixpkgs` update since it has already been done in another PR.

**Review by fufexan — APPROVED** [review]
Oops, forgot about this. My bad.

LGTM

**Pull request merged**
