### PR TITLE
add mfact setting for master layout

### PR DESCRIPTION
**Pull request by hillyu**
#### Describe your PR, what does it fix/add?
add mfact setting to adjust the original window split ratio, default set to 0.55.

### CODE REVIEW

**Comment by vaxerski** [comment]
1) not formatted
2) why is it 0.55 and not 0.5

**Comment by hillyu** [comment]
> 

0.55 means slightly larger master. This is taken from dwm. Also it would make it easier to know which is the master when switching the "orientation"

**Comment by vaxerski** [comment]
something went wrong here and you pulled my commits? Please rebase against HEAD.

**Review by vaxerski — APPROVED** [review]
lgtm, thanks

**Pull request merged**
