### PR TITLE
Various constraint handling fixes

### PR DESCRIPTION
**Pull request by vaxerski**
Fixed:
 - InputManager using raw xwayland coords
 - InputManager using raw position hint
 - InputManager not scaling the regions if xwayland:force_zero_scale
 - InputManager not using scaled boundaries of the region

Notable for #3340 #3204

Should fix both, that's at least the goal.

If you are affected, let me know how it goes with this mr

### CODE REVIEW

**Review by fufexan — APPROVED** [review]

**Comment by vaxerski** [comment]
waiting for confirmation of fixing from any of the 2 issue members

**Comment by vaxerski** [comment]
#3204 confirmed fixed, waiting for #3340

**Comment by vaxerski** [comment]
well guy is away, will merge then anyways

**Comment by pshirshov** [comment]
@vaxerski : see https://github.com/hyprwm/Hyprland/issues/3340#issuecomment-1740035823

Things got lot better but the lock area geometry is still incorrect

**Pull request merged**
