### PR TITLE
fix: move to prev ws, moved to same mon

### PR DESCRIPTION
**Pull request by Truenya**
#### Describe your PR, what does it fix/add?
https://github.com/hyprwm/Hyprland/issues/6684

### CODE REVIEW

**Review by vaxerski — APPROVED** [review]
tanks

**Comment by leon-erd** [comment]
Does not fix the issue unfortunately.
I didn't have time yesterday evening to test this MR

**Comment by vaxerski** [comment]
me when I am too fast

**Comment by vaxerski** [comment]
I'll revert it then

**Comment by vaxerski** [comment]
done, nuked.

**Pull request merged**
