### PR TITLE
wp-fractional-scaling-v1 impl

### PR DESCRIPTION
**Pull request by vaxerski**
Implements the fractional scaling protocol.

Test clients can be found @ https://gitlab.freedesktop.org/kennylevinsen/fractional-scaling
You need to patch the repo with [patch.txt](https://github.com/hyprwm/Hyprland/files/10413691/patch.txt) then run `meson build/ && ninja -C build/`. There will be 3 executables you can test. Make them floating for best results, they don't like being resized.

@fufexan for nix/meson (fails cuz `fractional-scaling-v1-protocol.o` is not being linked probably)

Please test for any bugs _not only with the test clients_

### CODE REVIEW

**Comment by vaxerski** [comment]
havent heard complaints. @fufexan verified and ready?

**Comment by fufexan** [comment]
It does build but I haven't had time to test it yet. I'm not sure if I have time tonight, but tomorrow for sure.

**Comment by vaxerski** [comment]
approve the changes once you do that and find it working

**Review by fufexan — APPROVED** [review]
Firefox, Chromium and Electron work. The test clients also work properly.

**Comment by vaxerski** [comment]
fuck it we ball then

**Pull request merged**
