### PR TITLE
Fix crash in isWorkspaceVisible

### PR DESCRIPTION
**Pull request by thejch**
Fixes https://github.com/hyprwm/Hyprland/issues/5402

### CODE REVIEW

**Comment by vaxerski** [comment]
it'd be better to actually track down the root cause.

furthermore, use `valid(w)`

**Comment by thejch** [comment]
changed

**Comment by vaxerski** [comment]
I fixed it anyways in main with a more robust patch

**Comment by thejch** [comment]
cool

**Pull request closed without merging**
