### PR TITLE
Rewrite the subsurface tree

### PR DESCRIPTION
**Pull request by vaxerski**
Rewrites the entire subsurface tree system because it FUCKING SUCKED

and now it doesn't, or at least sucks less.

ref #4874 #4872

### CODE REVIEW

**Comment by AmirDahan** [comment]
Popups still suck :(
screenshot

**Comment by vaxerski** [comment]
if it's not a regression, it's unrelated.

**Comment by AmirDahan** [comment]
However flickering related issues seem to have been fixed

**Comment by outfoxxed** [comment]
Not seeing any regressions on subsurfaces

**Comment by vaxerski** [comment]
cool

**Comment by rurigk** [comment]
I'm still getting problems with this
Sometimes it works perfect, sometimes some context menus dont get updated when hovered (highlight)
Sometimes context menus works perfectly but extension popups in firefox dont update (hightlight and text cursor)

**Comment by vaxerski** [comment]
are you on latest git

**Comment by rurigk** [comment]
Im on [rewrite-constraints](https://github.com/hyprwm/Hyprland/tree/rewrite-constraints) which i assume you rebased
Im gonna test on main

**Comment by rurigk** [comment]
https://github.com/hyprwm/Hyprland/assets/6665402/3216fd5d-06c8-4c20-8924-037c35d6a5ea

**Comment by vaxerski** [comment]
oops

**Comment by vaxerski** [comment]
I get the same issue in firefox but not firefox developer edition (beta) 

maybe it's a ff bug?

**Comment by proycon** [comment]
We're running into an regression with wvkbd on the latest git main HEAD, which I think may be due to this merge. So I'll comment here (if you prefer a new issue, let me know). Keypresses on our virtual keyboard present a small popup which worked fine on Hyprland <= 0.36.0 (and other compositors) but now fail. 

Please see https://github.com/jjsullivan5196/wvkbd/issues/65 for further details.

**Comment by vaxerski** [comment]
wrong commit but ye

**Pull request merged**
