### PR TITLE
Allow vrr with vfr=false

### PR DESCRIPTION
**Pull request by UjinT34**
#### Describe your PR, what does it fix/add?
Allows VRR with `vfr = false` as a workaround for nvidia ghosting/tearing on aquamarine branch. With 
```
misc {
    vfr = false
    vrr = 2
}

experimental {
    explicit_sync = true
}

```
those issues will be present for some apps in fullscreen mode only.

#### Is it ready for merging, or does it need work?
Ready

### CODE REVIEW

**Comment by vaxerski** [comment]
it's not ready because half of the checks fail

**Comment by UjinT34** [comment]
> it's not ready because half of the checks fail

It's for aquamarine branch. main is ok without this feature.

**Comment by vaxerski** [comment]
isnt this a bug worth fixing, though? I mean, vfr off will come at a sizeable cpu/gpu hit

**Comment by UjinT34** [comment]
Any progress on this bug?
I don't understand why VRR requires `vfr = true`. Looks like these settings should be independent. This feature "auto enables" vfr when vrr is active.

**Comment by UjinT34** [comment]
I understand. That's why this feature till it properly fixed. I don't think anyone will miss `vfr = false` blocking VRR %)
Too much fuss about one line that doesn't break anything...

**Pull request closed without merging**
