### PR TITLE
optimize CBezierCurve::getYForPoint.

### PR DESCRIPTION
**Pull request by Dickby**
#### Describe your PR, what does it fix/add?
This seems to be much faster, at least on my end.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
This should be tested on other machines.

#### Is it ready for merging, or does it need work?
See above

### CODE REVIEW

**Comment by vaxerski** [comment]
0.13us -> 0.44us for me.

**Comment by Dickby** [comment]
Are you looking at `average calc time` or the baking time?
For me average calc went from 19u to 1u!
Did you try the release build?

**Comment by vaxerski** [comment]
debug, I'll try releas

**Comment by vaxerski** [comment]
release: 0.03us -> 0.03us

**Comment by vaxerski** [comment]
a bit suspiciously low.

**Comment by Dickby** [comment]
I'll check!

**Comment by Dickby** [comment]
You are right this was optimized out.

**Pull request closed without merging**
