### PR TITLE
add #945

### PR DESCRIPTION
**Pull request by jacekpoz**
#### Describe your PR, what does it fix/add?
it adds the feature requested in [#945](https://github.com/hyprwm/Hyprland/issues/945)

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
IDK first real PR so please check if it's ok

#### Is it ready for merging, or does it need work?
I think it's ready, works on my machine just fine but again check just to be sure

### CODE REVIEW

**Comment by jacekpoz** [comment]
also change the category and name it might not fit

**Comment by vaxerski** [comment]
not how it should be done in the slightest

**Comment by Froggo8311** [comment]
@vaxerski I was looking into having a floating option... Is there a better way it ought to be done? I am willing to reimplement it, assuming it wouldn't take any major changes to the compositor.

**Comment by vaxerski** [comment]
workspace rule allfloat

**Pull request closed without merging**
