### PR TITLE
refactor: unify changeworkspace dispatcher

### PR DESCRIPTION
**Pull request by memchr**
Refactor the workspace dispatcher to reduce repetitive code. 

Minor logic changes.

### CODE REVIEW

**Comment by memchr** [comment]
I think the following can also be removed as `changeWorkspace()` does the same thing
```cpp
        if (const auto PLASTWINDOW = pWorkspaceToChangeTo->getLastFocusedWindow(); PLASTWINDOW)
            g_pCompositor->focusWindow(PLASTWINDOW);
        else if (const auto PFIRSTWINDOW = g_pCompositor->getFirstWindowOnWorkspace(pWorkspaceToChangeTo->m_iID); PFIRSTWINDOW)
            g_pCompositor->focusWindow(PFIRSTWINDOW);
        else
            g_pCompositor->focusWindow(nullptr);
            ```

**Comment by memchr** [comment]
In addition, the current behaviour of `CMonitor::changeWorkspace()` is to focus on the last window. and the call to `CInputManager::simulateMouseMovement()` at the end of the dispatcher may betray this, so, shall we wrap the cursor to the middle of `pWorkspace->getLastFocusedWindow()` if `input:follow_mouse == 3` ?

**Comment by vaxerski** [comment]
yeah sounds like an okay idea

**Review by vaxerski — APPROVED** [review]
lgtm

**Pull request merged**
