### PR TITLE
{nix/default,meson}: add re2 dependency

### PR DESCRIPTION
**Pull request by khaneliman**
#### Describe your PR, what does it fix/add?

Just adding new dependency to nix and meson. 

#### Is it ready for merging, or does it need work?

Fixes nix build

### CODE REVIEW

**Comment by khaneliman** [comment]
Looks like we need to update xdph flake too

**Comment by vaxerski** [comment]
xdph is fucked idk why @fufexan said he'll do it later

**Review by vaxerski — APPROVED** [review]
thanks

**Comment by khaneliman** [comment]
> thanks

Created a PR in xdph to handle the nix error, after that is merged I can update the flake here so it resolves that check failing.

**Comment by fufexan** [comment]
Sorry for the wait, I fell asleep pretty early last evening. I've pushed the xdph fix and also updated the flake in here.

**Pull request merged**
