### PR TITLE
renderer: better lockscreen dead behavior

### PR DESCRIPTION
**Pull request by vaxerski**
Adds 2 textures for when locks die that look better than the red screen of death + give useful info if lock dies.

@fufexan please fix nix, I moved assets to `./assets/install/` and all the pngs inside should be install'd

and yes the pngs are made by me and are beautiful

### CODE REVIEW

**Comment by Eclextic** [comment]
Vaxry what are those drawings xd. Shits gonna be better than the Windows BSoD.

(Add a smiley, I dare ya xd)

**Comment by vaxerski** [comment]
you have a problem with them?

**Comment by fufexan** [comment]
I double dare ya to make those SVGs
yeeeaaa

**Comment by vaxerski** [comment]
no

**Pull request merged**
