### PR TITLE
Fix floating clipbox scale

### PR DESCRIPTION
**Pull request by thejch**
#### Describe your PR, what does it fix/add?
Fix floating clipbox scale. Should fix the window getting clipped incorrectly during workspace transition? Not 100% sure but works for me

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
No

#### Is it ready for merging, or does it need work?
Ready

### CODE REVIEW

**Comment by vaxerski** [comment]
you can use vecTransformedSize instead. It's the same.

**Comment by thejch** [comment]
> you can use vecTransformedSize instead. It's the same.

added

**Review by vaxerski — APPROVED** [review]
I told you long ago, on the road

**Comment by vaxerski** [comment]
wait, this needs to be rethinked.

**Comment by vaxerski** [comment]
why are we adding the entire monitor here?

We should just translate it by the workspace offset

oops

**Comment by thejch** [comment]
you can do it if you want. as long as the scale thing gets fixed lol

**Comment by vaxerski** [comment]
I can't repro so I can just suggest you try this:
```cpp
CRegion rg = pWindow->getFullWindowBoundingBox().translate(-pMonitor->vecPosition).scale(pMonitor->scale);
rg.add(CBox{0, 0, pMonitor->vecSize.x, pMonitor->vecSize.y});
```

into

```cpp
CRegion rg = pWindow->getFullWindowBoundingBox().translate(-pMonitor->vecPosition + PWORKSPACE->m_vRenderOffset.vec()).scale(pMonitor->scale);
```

**Comment by thejch** [comment]
yea seems to do it. I added that

**Review by vaxerski — APPROVED** [review]
top g thanks!

**Pull request merged**
