### PR TITLE
fixed a typo

### PR DESCRIPTION
**Pull request by jacekpoz**
#### Describe your PR, what does it fix/add?
it fixes a typo

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
I fixed a typo

#### Is it ready for merging, or does it need work?
it is ready

### CODE REVIEW

**Comment by NotAShelf** [comment]
based

**Comment by jacekpoz** [comment]
based on a typo

**Comment by vaxerski** [comment]
not a typo

**Comment by jacekpoz** [comment]
the other ones are capitalized
image

**Pull request closed without merging**
