### PR TITLE
Add count group flag in windowCount workspace selector prop

### LINKED ISSUE #5488: workspace rule selector like window counts, but for 'containers'
### Description

Some way to have the functionality of say, w[t2] but only count the number of 'containers' that are visible in the workspace. I guess just counting groups as a single window would work?

### PR DESCRIPTION
**Pull request by sungyoonc**
#### Describe your PR, what does it fix/add?
Adds the groupCount workspace selector prop.
The groupCount is the same as the windowCount but it counts groups instead of windows in a workspace.
Resolves #5488

Workspace rules can now do
```ini
workspace = g[t1], bordersize:10
```

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
A comment here shows an example using windowCount with range `0-4`. But this is invalid according to the code. Did you meant to make `0-4` a valid range or just typo in the comment?
```cpp
// w - windowCount: w[0-4] or w[1], optional flag t or f for tiled or floating, e.g. w[t0-1]
```
```cpp
if (to < from || to < 1 || from < 1) {
    Debug::log(LOG, "Invalid selector {}", selector);
    return false;
}
```

#### Is it ready for merging, or does it need work?
Ready, but wiki mr needed.

### CODE REVIEW

**Comment by vaxerski** [comment]
why not integrate it with w? `w[gt1-2]`

**Comment by sungyoonc** [comment]
> why not integrate it with w? `w[gt1-2]`

How about this?

**Comment by vaxerski** [comment]
okay, but I don't get why you're doing all that refactoring outside of what you are adding. I'd rather it wasn't there.

**Comment by sungyoonc** [comment]
Removed all the refactoring bits. Should I make a separate mr or just scrap it?

**Comment by vaxerski** [comment]
> Removed all the refactoring bits. Should I make a separate mr or just scrap it?

No, they are fine, just unrelated to this MR. Feel free to make it separately

**Comment by vaxerski** [comment]
can you make a wiki mr?

**Comment by sungyoonc** [comment]
Here hyprwm/hyprland-wiki#585

**Comment by zakk4223** [comment]
Hmm, coming back to this now that it is in...

Are there any sets of selectors I can use that match tiled(windows+groups) = <num>?

(I guess you can kinda do it with multiple workspace rules?)

**Comment by sungyoonc** [comment]
I think mixed counting flag(non grouped window + groups) need to be added to support that.

**Pull request merged**
