### PR TITLE
defaultConfig: improve default groupbar appearance

### PR DESCRIPTION
**Pull request by Aqa-Ib**
This is subjective of course (this is my personal config), but I feel like this would be better for new users than the current one (suggestions welcome).
Cheers

### CODE REVIEW

**Comment by vaxerski** [comment]
groupbar generally needs some improvements heh

**Comment by vaxerski** [comment]
idk imho its not much better, its almost the same

**Comment by Aqa-Ib** [comment]
Yeah it is not that great. Maybe some ricer on discord or something could help improving this, I will ask.

**Comment by Aqa-Ib** [comment]
I have created an issue to discuss this. Maybe rather than modifying the defaultConfig, would be better to change the default values for the involved variables when we settle on a good rice. https://github.com/hyprwm/Hyprland/issues/8375

**Pull request closed without merging**
