### PR TITLE
Add support for smart splitting

### PR DESCRIPTION
**Pull request by DanielAdolfsson**
#### Describe your PR, what does it fix/add?

Imagine a square or rectangular box. Picture two diagonal lines crossing each other to form an 'X' that divides the box into four equal sections or triangles. Each triangle is an equal quarter of the box.

This PR adds support for splitting depending on which section the mouse cursor is currently over. Personally, I find this slightly more intuitive.

A new configuration option has been added `dwindle:smart_split`, which has to be set to `1` in order for this functionality to be enabled.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)

Not that I know- but I'm new to the codebase so feel free to check!

#### Is it ready for merging, or does it need work?

Maybe give it a different name. "smart_split" isn't very smart ;)

Also, maybe a second option to only enabling this when *moving* a window?

### CODE REVIEW

**Review by vaxerski — COMMENTED** [review]
not formatted with clang-format

also, wouldn't this require preserve_split?

**Comment by DanielAdolfsson** [comment]
> not formatted with clang-format
Alright!

> also, wouldn't this require preserve_split?
Yeah I believe so. It will probably feel weird with it off. Maybe preserve_split should be implied when smart_split is set?

**Comment by vaxerski** [comment]
> Yeah I believe so. It will probably feel weird with it off. Maybe preserve_split should be implied when smart_split is set?

Yeah, we can do that.

**Comment by DanielAdolfsson** [comment]
This should work?

**Comment by DanielAdolfsson** [comment]
Created PR hyprwm/hyprland-wiki#266 for the option. 
Been testing this for a few hours at this point as I'm running this code live. Haven't ran into any issues yet!

**Pull request merged**
