### PR TITLE
fixed mouse dispatcher

### PR DESCRIPTION
**Pull request by Moerliy**
#### Describe your PR, what does it fix/add?
dispatcher issue that came up with the merge of https://github.com/hyprwm/Hyprland/pull/6358

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
-/-

#### Is it ready for merging, or does it need work?
needs testing but the error seems gone

### CODE REVIEW

**Comment by nonetrix** [comment]
oopsies
roblox

**Comment by gksudolol** [comment]
this busts the mouse completely :(

**Comment by Moerliy** [comment]
yeah I noticed it xD

**Comment by Moerliy** [comment]
sitting on it but my test setup is kind f'ed up so a godda do some pushing and pulling

**Comment by Moerliy** [comment]
@gksudolol can you test it again. Should work now

**Review by JoelleJS — APPROVED** [review]
The issue is fixed for me

**Comment by gksudolol** [comment]
- [x] OP is Jason Bourne?

Jesus Christ

Tested, resolved

**Review by vaxerski — APPROVED** [review]
I should stop reviewing MRs barely alive. Dunno how I missed this

**Comment by Moerliy** [comment]
I don't know how I even managed to delete that line thb O_o

**Comment by nonetrix** [comment]
Fixed for me :-)

**Pull request merged**
