### PR TITLE
core/data: Use pointer focus for DnD operations

### PR DESCRIPTION
**Pull request by vaxerski**
This is mostly to fix stuff from #7737

Cases:
 - [x] `pcmanfm-qt --desktop` -> panel
 - [x] `pcmanfm-qt` -> panel
 - [x] menu -> panel

Unsure why the last one doesn't work ATM.

### CODE REVIEW

**Comment by stefonarch** [comment]
Fine:
* DND in taskbar works now
* DND from desktop or filemanagers works
* DND from menu not
* Ctrl+DND in quicklauch (to reorder) not

**Comment by vaxerski** [comment]
what does "ctrl+dnd" do that dnd doesnt? We don't send different actions based on modifiers pressed.

**Comment by vaxerski** [comment]
menu->panel is fixed.

**Comment by vaxerski** [comment]
I'd say the reorder might be an lxqt-panel bug, I don't see what is to be done on our side. Anyways, I am happy with the state of this MR.

**Comment by stefonarch** [comment]
> what does "ctrl+dnd" do that dnd doesnt? We don't send different actions based on modifiers pressed.

Prevents accidental dragging.

**Comment by vaxerski** [comment]
I meant more like in lxqt-panel. How do you detect it's ctrl+drag and not just drag.

**Pull request merged**
