### PR TITLE
adding ubuntu 23.04 build support

### PR DESCRIPTION
**Pull request by Vertecedoc4545**
#### Describe your PR, what does it fix/add?
This pull request goes together with the pull request in hyprland docs for adding proper and easy instructions for building in ubuntu 23.04

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
https://github.com/hyprwm/Hyprland/issues/2195

#### Is it ready for merging, or does it need work?
no, needs solving the previous bug for it to work well

### CODE REVIEW

**Comment by vaxerski** [comment]
You're hardcoding some random build for ubuntu, locking deps, for an OS we don't support for obvious reasons + are not willing to support.

**Comment by Vertecedoc4545** [comment]
> You're hardcoding some random build for ubuntu, locking deps, for an OS we don't support for obvious reasons + are not willing to support.

basically are the project dependencies, and as is part of my dayly use, im willing to support, i got plenty of time for that.

then as is always a pain to look manually for the deps when they are not in a online guide.

what are your suggestions for improving this with the objective of merging

**Comment by Vertecedoc4545** [comment]
what do i need to explain/change

**Comment by vaxerski** [comment]
> what are your suggestions for improving this with the objective of merging

There is no point, as none of the maintainers are willing to support ubuntu pipelines. Feel free to make your own repo for hyprland builds or w/e is the equivalent of arch AUR/fedora COPR/alike

**Comment by Vertecedoc4545** [comment]
i mean, its simple, you dont need to, its only a documentation issue, lets only merge the hyprland wiki with the change of the script is disponible in my repo only, and if in the future hyprland starts to use a dependency which brakes ubuntu if installed i can put in the wiki that you can only build lets say until x or y version on this ubuntu version

i think is important to do this cuz ubuntu is yet a popular distro and this new version adds quite nice changes to gnome and to the system in general also the nvidia support is great, which is going to attract all kinds of users.

since is posible and fully operational but quite tedious without a guide to use and build hyprland in ubuntu 23.04

would be great to have it, with the ***clear specification that hyprland does not intend to support ubuntu pipelines***
also the message that ***this build guide can break in the future***, in the case of that im willing to maintain the instructions and put any warning or advice if needed

i personally dont see a reaon why that cannot be done

**Comment by vaxerski** [comment]
If you want a note for ubuntu with a clear warning, sure, put it under the installation wiki part where there is a big combo with all the distros:

image

And not trash the main repo with platform-dependent scripts that _we_ won't maintain.

Look at the fedora tab, and do the same for ubuntu. Make your gist, repo, whatever, and put a link to it there.

Ref: https://wiki.hyprland.org/Getting-Started/Installation/

**Comment by Vertecedoc4545** [comment]
Perfect!!, That sonds very resonable to me, and a great reason for no having ubuntu in the wiki, let me modify my pull request.

Thanks!!

**Pull request closed without merging**
