### PR TITLE
Formatter rework

### PR DESCRIPTION
**Pull request by vaxerski**
Uses `std::format` everywhere instead of the poo poo `vasnprintf`

Needs to be merged ASAP - will make a conflict with pretty much anything

### CODE REVIEW

**Comment by vaxerski** [comment]
@fufexan idk do something to the cringe gcc ver in nix or something, gcc >= 13

**Comment by memchr** [comment]
```
../src/debug/Log.hpp:56:24: warning: unused variable ‘timet’ [-Wunused-variable]
   56 |             auto       timet  = std::chrono::system_clock::to_time_t(std::chrono::system_clock:
:now());
      |                        ^~~~~
../src/debug/Log.hpp:57:24: warning: unused variable ‘MILLIS’ [-Wunused-variable]
   57 |             const auto MILLIS = std::chrono::duration_cast<std::chrono::milliseconds>(std::chro
no::system_clock::now().time_since_epoch()).count() % 1000;
```

**Comment by NotAShelf** [comment]
(nix) do all package need to be updated to gcc13? Is it just Hyprland? does hyprland-protocols need an update too?

**Comment by vaxerski** [comment]
hyprland now needs gcc >= 13 to build. hyprland-protocols doesnt even use gcc. Everything else can stay the same, but the xdph rewrite that is awaiting meson&nix from fuf will also require gcc >= 13

**Comment by NotAShelf** [comment]
I will send a patch that updates Hyprland builder to use gcc13 shortly.

**Comment by NotAShelf** [comment]
```patch
From 3dda5ff38c2f08651490670dec134f291e10b156 Mon Sep 17 00:00:00 2001
From: NotAShelf <raf@notashelf.dev>
Date: Wed, 6 Sep 2023 01:20:36 +0300
Subject: [PATCH] nix: use gcc13Stdenv in mkDerivation

Currently stdenv.mkDerivation provides gcc12 as the default. To avoid hacky overrides, we can get mkDerivation from gcc13Stdenv until nixpkgs is updated.
---
 nix/default.nix | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/nix/default.nix b/nix/default.nix
index 96fa12d7..46302e41 100644
--- a/nix/default.nix
+++ b/nix/default.nix
@@ -1,6 +1,7 @@
 {
   lib,
   stdenv,
+  gcc13Stdenv,
   pkg-config,
   makeWrapper,
   meson,
@@ -39,7 +40,7 @@
 }:
 assert lib.assertMsg (!nvidiaPatches) "The option `nvidiaPatches` has been renamed `enableNvidiaPatches`";
 assert lib.assertMsg (!hidpiXWayland) "The option `hidpiXWayland` has been removed. Please refer https://wiki.hyprland.org/Configuring/XWayland";
-  stdenv.mkDerivation {
+  gcc13Stdenv.mkDerivation {
     pname = "hyprland${lib.optionalString enableNvidiaPatches "-nvidia"}${lib.optionalString debug "-debug"}";
     inherit version;
 
-- 
2.41.0
```

This used gcc13 within the builder that builds Hyprland, and leaves the rest intact. Should fix the CI.

Tested.

**Comment by vaxerski** [comment]
applied

**Comment by NotAShelf** [comment]
Currently crashes when closing certain qt applications. The most reproducible reproduction was possible with qbittorrent. Logs: https://p.frzn.dev/7j6

**Comment by vaxerski** [comment]
that was fixed w/ x11 fix 2

**Comment by NotAShelf** [comment]
A second too late I guess. Testing again in a minute.

**Comment by NotAShelf** [comment]
Still crashes, this time while opening qt applications (such as dolphin).

**Comment by memchr** [comment]
libc++, (required for the clang build) only partially implements the `std::formater` specialisation for types in `std::chrono` types. Therefore this line won't compile

```cpp
            logMsg += std::format("[{:%T}] ", std::chrono::hh_mm_ss{std::chrono::system_clock::now() - std::chrono::floor<std::chrono::days>(std::chrono::system_clock::now())});
```

Would you mind making this change? The LLVM toolchain has no other compilation problems.

```diff
diff --git a/src/debug/Log.hpp b/src/debug/Log.hpp
index 48dc790..c155041 100644
--- a/src/debug/Log.hpp
+++ b/src/debug/Log.hpp
@@ -52,8 +52,15 @@ namespace Debug {
         ofs.open(logFile, std::ios::out | std::ios::app);
 
         // print date and time to the ofs
-        if (disableTime && !*disableTime)
+        if (disableTime && !*disableTime) {
+#ifndef _LIBCPP_VERSION
             logMsg += std::format("[{:%T}] ", std::chrono::hh_mm_ss{std::chrono::system_clock::now() - std::chrono::floor<std::chrono::days>(std::chrono::system_clock::now())});
+#else
+            auto c = std::chrono::hh_mm_ss{std::chrono::system_clock::now() - std::chrono::floor<std::chrono::days>(std::chrono::system_clock::now())};
+            logMsg += std::format("{:%H}:{:%M}:{:%S}", c.hours(), c.minutes(), c.subseconds());
+
+#endif
+        }
 
         logMsg += std::vformat(fmt, std::make_format_args(args...));
```

Thanks.

**Comment by memchr** [comment]
> ```
> getBacktrace()
> CrashReporter::createAndSaveCrash(int)
> handleUnrecoverableSignal(int)
> decltype(auto) std::basic_format_arg<std::basic_format_context<std::__format::_Sink_iter<char>, char> >::_M_visit<std::__format::_Formatting_scanner<std::__format::_Sink_iter<char>, char>::_M_format_arg(unsigned long)::{lambda(auto:1&)#1}>(std::__format::_Formatting_scanner<std::__format::_Sink_iter<char>, char>::_M_format_arg(unsigned long)::{lambda(auto:1&)#1}&&, std::__format::_Arg_t)
> std::__format::_Sink_iter<char> std::__format::__do_vformat_to<std::__format::_Sink_iter<char>, char, std::basic_format_context<std::__format::_Sink_iter<char>, char> >(std::__format::_Sink_iter<char>, std::basic_string_view<char, std::char_traits<char> >, std::basic_format_args<std::basic_format_context<std::__format::_Sink_iter<char>, char> > const&, std::locale const*) [clone .isra.0]
> std::vformat[abi:cxx11](std::basic_string_view<char, std::char_traits<char> >, std::basic_format_args<std::basic_format_context<std::__format::_Sink_iter<char>, char> >)
> void Debug::log<char*&>(LogLevel, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char*&)
> Events::listener_destroyWindow(void*, void*)
> CHyprWLListener::emit(void*)
> ```

glibc problem? Can you try building with a newer version of glibc?

**Comment by vaxerski** [comment]
@memchr pushed

**Comment by vaxerski** [comment]
logs now shouldnt crash anymore under any circumstance (logs were crashing if the formatter was failing, now it will be caught and logged)

so if checks pass I will merge

**Pull request merged**
