### PR TITLE
Tearing implementation (v3)

### LINKED ISSUE #927: Frame-perfect Games VRR (Adaptive sync) support
will there be VRR support for fullscreen apps?

### PR DESCRIPTION
**Pull request by vaxerski**
Adds tearing.

Config:
 - `general:allow_tearing` bool
 - `immediate` window rule to force tearing for an app if fullscreen (highly recommended to set it to your test client just in case it doesn't support the protocol)

tearing only kicks in if the app is fullscreen and the only surface on a monitor.

requires `env = WLR_DRM_NO_ATOMIC,1`

Closes #927

### CODE REVIEW

**Comment by FlafyDev** [comment]
Works for me in Minecraft(XWayland), I can see tearing.
I am running Hyprland on amd igpu and Minecraft on RX 6700 XT with DRI_PRIME.

**Comment by dtomvan** [comment]
I'm sorry, but I don't think I understand the point. Why would you want to intentionally introduce (albeit opt-in) tearing for your clients while over on X.org people are doing everything they can to get rid of it? Does it allow for better input latency or lower PU usage or something?

**Comment by vaxerski** [comment]
Tearing is only for select applications (games) and is there to reduce latency and stutter in fast-paced games where milliseconds count. It will never kick in for regular applications or desktop work.

**Comment by dtomvan** [comment]
Thank you for the explanation. So, should we test for example on wine games with (dx)vk, since a lot of the competitive games where every frametime and latency reduction counts (except for games like xonotic) are on windows?

**Comment by vaxerski** [comment]
you can test on any game. I tested CS2.

**Comment by jacekpoz** [comment]
RX 6800M, everything looks like this
image

+ lots of lag when rendering updates in certain regions of the screen (IDK how to explain it), at least tearing works though :D

**Comment by jacekpoz** [comment]
rebuild from `oops`, nothing changed

**Comment by jacekpoz** [comment]
weirdly enough, removing the tearing stuff from my config doesn't actually change anything, screen still squashed in half and hyprland is very reluctant to draw any updates

**Comment by vaxerski** [comment]
@jacekpoz does it go away after you remove the env for WLR_DRM_NO_ATOMIC? It's a less-tested legacy API after all and stuff like this might be an issue with it.

**Comment by jacekpoz** [comment]
missed that one, removing it fixes all of the above

**Comment by vaxerski** [comment]
yep, unlucky then.

**Comment by vaxerski** [comment]
Merging then, seems to work. Will make a wiki page shortly

**Comment by Nomz420** [comment]
I tested osu!stable (wine), osu!lazer (both xwayland and wayland) and CS2. For me they just freeze with tearing enabled...

**Comment by fufexan** [comment]
@Nomz420 really? For me lazer works just fine.

**Comment by Nomz420** [comment]
> @Nomz420 really? For me lazer works just fine. Do you have an Intel GPU?

It's a laptop with both Intel and NVIDIA GPUs.
I tried running both osu!lazer and stable with and without `prime-run`.

**Comment by dtomvan** [comment]
I don't know if it is a different bug, but cannot test because my system freezes entirely (even ctrl-alt-fN) when I try to launch a `immediate` application. I am on nvidia though, and maybe my hyperlandd.conf isn't correctly setup for this case. Will investigate later.

**Comment by vaxerski** [comment]
intel gpus dont support tearing at all IIRC.

NVIDIA might be fucky because nvidia, but it shouldn't as IIRC it does support tearing.

See the new wiki page https://wiki.hyprland.org/Configuring/Tearing/

**Comment by vaxerski** [comment]
?

**Comment by MrDuartePT** [comment]
Well I'm using a laptop with amd + nvidia and launching cs2 seems to be working.

**Comment by MrDuartePT** [comment]
Tested on amd apu:
You need to have vkcube with wayland support and add this to the config:
```windowrulev2 = immediate, title:^(vkcube)$```

With tearing enable:
https://github.com/hyprwm/Hyprland/assets/68701049/ec3481b6-49bf-493e-b032-fe836a458638

Withouth tearing:
https://github.com/hyprwm/Hyprland/assets/68701049/2b9cddbf-5a12-4fc2-9a64-3f19e152e134

Can show with nvidia because vkcube dont open with wayland support on nvidia dgpu.

**Comment by MrDuartePT** [comment]
@vityafx well let me try setting tearing on the monitor and use NVIDIA with vkcube

**Comment by MrDuartePT** [comment]
Thanks @vityafx I can confirm running cs2 with nvidia gpu that tearing is enable
image

**Comment by Edgars-Cirulis** [comment]
Anyone managed to get working on Nvidia? Im RTX 3060 user

**Comment by Edgars-Cirulis** [comment]
For me CSGO on fullscreen just hangs up. I am using a laptop.

**Comment by Edgars-Cirulis** [comment]
> > Works in QuakeLive, too. I wish I could just enable it permanently on one of my monitors or just one workspace, like for my game "gaming" workspace. No glitches, NVIDIA, non-patched hyprland. Works via gamemode, too.
> 
> > 
> 
> > FYI: One can see whether the window rule is applied and so whether it works in two ways:
> 
> > 
> 
> >     1. Check for the log and the "immediate" word. Found - check what it is applied to, and if it is the window you wanted - it is enabled.
> 
> > 
> 
> >     2. You can just run the game and see.
> 
> > 
> 
> >     3. In `hyprctl monitors`, one can see the `activelyTearing: true` if the app for which you requested tearing is currently enabled on that monitor.
> 
> > 
> 
> > 
> 
> > Now my only wish is to find a way to disable GSync on my monitor to finally use ULMB2.
> 
> > 
> 
> > Thank you @vaxerski 🥇 👍
> 
> 
> 
> @Edgars-Cirulis 



For me CS2 Just hangs on fullscreen, but only "sound is comming" the app just freezes.

**Comment by MrDuartePT** [comment]
> > > Works in QuakeLive, too. I wish I could just enable it permanently on one of my monitors or just one workspace, like for my game "gaming" workspace. No glitches, NVIDIA, non-patched hyprland. Works via gamemode, too.
> > 
> > > 
> > 
> > > FYI: One can see whether the window rule is applied and so whether it works in two ways:
> > 
> > > 
> > 
> > >     1. Check for the log and the "immediate" word. Found - check what it is applied to, and if it is the window you wanted - it is enabled.
> > 
> > > 
> > 
> > >     2. You can just run the game and see.
> > 
> > > 
> > 
> > >     3. In `hyprctl monitors`, one can see the `activelyTearing: true` if the app for which you requested tearing is currently enabled on that monitor.
> > 
> > > 
> > 
> > > 
> > 
> > > Now my only wish is to find a way to disable GSync on my monitor to finally use ULMB2.
> > 
> > > 
> > 
> > > Thank you @vaxerski 🥇 👍
> > 
> > 
> > 
> > @Edgars-Cirulis 
> 
> 
> 
> For me CS2 Just hangs on fullscreen, but only "sound is comming" the app just freezes.

Strange didn't happen to me you are not using a Intel dGPU or have a Intel igpu (I think even when using Prime I think for now Intel + Nvidia or Intel + AMD are not supported)

**Comment by Edgars-Cirulis** [comment]
> laptop have a mux)

MSI Katana GF76 11EU dosnt have MUX switch sadly, maybe if I use HDMI instead it will work?

**Comment by MrDuartePT** [comment]
> > laptop have a mux)
> 
> 
> 
> MSI Katana GF76 11EU dosnt have MUX switch sadly, maybe if I use HDMI instead it will work? 

Well if the hdmi is connected to dGPU and you launch the game on the external screen should work.

**Comment by MichaelDeets** [comment]
@vaxerski Just wondering, if I were to apply [the DRM_MODE_PAGE_FLIP_ASYNC for atomic commits](https://patchwork.kernel.org/project/dri-devel/patch/20230707224059.305474-2-andrealmeid@igalia.com/) kernel patch, would it allow tearing when using WLR_DRM_NO_ATOMIC set to 0?

I see there is a warning when it detects this configuration, but I'm not sure if that's it

Thanks

**Pull request merged**
