### PR TITLE
Add DesktopNames to hyprland.desktop

### PR DESCRIPTION
**Pull request by Vladimir-csp**
#### Describe your PR, what does it fix/add?

Adds `DesktopNames` with canonical `Hyprland` name to `hyprland.desktop`. DMs or SMs would use this to set `$XDG_CURRENT_DESKTOP`.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)

No.

#### Is it ready for merging, or does it need work?

Yes.

### CODE REVIEW

**Comment by Vladimir-csp** [comment]
Related to this and #7083, do I understand correctly that currently Hyrpland [unsets ](https://github.com/hyprwm/Hyprland/blob/main/src/Compositor.cpp#L425) `XDG_CURRENT_DESKTOP` and does not consider existing value? That might not be a good idea.

**Review by vaxerski — APPROVED** [review]
sure, though Hyprland will set the env itself

**Comment by vaxerski** [comment]
> Related to this and https://github.com/hyprwm/Hyprland/issues/7083, do I understand correctly that currently Hyrpland [unsets ](https://github.com/hyprwm/Hyprland/blob/main/src/Compositor.cpp#L425)XDG_CURRENT_DESKTOP and does not consider existing value? That might not be a good idea.

No, that's on exit. On launch it overwrites it

**Comment by Vladimir-csp** [comment]
> sure, though Hyprland will set the env itself

Compositor can be a part of some desktop environment, which can be launched by a DM or SM, which can set `XDG_CURRENT_DESKTOP` according to `DesktopNames` from entry. This is why existing value should be left as is if no explicit `env = XDG_CURRENT_DESKTOP,...` statement exists in config.

**Comment by vaxerski** [comment]
sooo... we should only set it iff it's unset/empty?

**Comment by Vladimir-csp** [comment]
Yes.

**Comment by vaxerski** [comment]
feel free to make a MR

**Comment by Vladimir-csp** [comment]
#7347

**Comment by Vladimir-csp** [comment]
#8110 resolved it

**Pull request closed without merging**
