### PR TITLE
Nix: fix build on aarch64

### LINKED ISSUE #1733: having trouble to build hyprland on a rasberrypi4
Greeting,  I'm learning the nixos-ecosystem lately. Trying to build hyprwm+nixos on a pi4 with my flake.nix.

However, some C compiler warnings forced it stop building up. How do I fix the libitoff and wrloots packages errors?

Here is my issue: https://github.com/NixOS/nixpkgs/issues/219571

And my nix config files: https://github.com/Costabo1/Nixos/blob/f4d5beaded77bc245f8dba0eefcc6c5e34642e23/flake_bkup.nix

Any guidance to install hyprland + nixos  on a pi4?

### PR DESCRIPTION
**Pull request by fufexan**
#### Describe your PR, what does it fix/add?
Fixes #1733.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
Built with no errors on my aarch64 server.
@Costabo1 for further testing.

#### Is it ready for merging, or does it need work?
Ready.

### CODE REVIEW

**Comment by Costabo1** [comment]
thanks for the effort,  I try to use fufexan/Hyprland. Then I typed nix flake update and nixos-rebuild switch --show-trace to buld hyprland. However, I got a long list off errors and failed to build the system.

did I miss sth in my configuration /flake.nix?

my error log:
https://github.com/Costabo1/Nixos/blob/main/aarch64_error_log

**Comment by fufexan** [comment]
> did I miss sth in my configuration /flake.nix?

If you have `hyprland.url = "github:fufexan/Hyprland/nix-stuff";` then no.

Also, the trace isn't complete.

**Comment by Costabo1** [comment]
Thanks for the guidance, I forgot type include nix-stuff in my previous try. I was able to build hyprland on my pi4 now. However, when I got an error when I start up Hyprland. 

[libseat] [libseat/backend/seatd.c:64] Could not connect to socket /run/seatd.sock: No such file or directory

try to fix this error with changing the variable into Hyprland of this  method, but seems not working with my situation

https://www.reddit.com/r/voidlinux/comments/mor7n5/getting_libseat_errors_when_starting_sway/

**Comment by fufexan** [comment]
@vaxerski ideas?

**Comment by vaxerski** [comment]
something's misconfigured / missing bout seatd. Looks like it's not running. Dunno for sure tho, never had issues with libseat

**Comment by Costabo1** [comment]
I tried install seatd package and run sudo seatd in the tty terminal. After that I got another error, seem missing the sort of GPU drivers for me?

Here is my log

https://github.com/Costabo1/Nixos/blob/main/aarch64_error_log

**Comment by fufexan** [comment]
That's likely a driver issue. I'll merge this, since the original problem is fixed.

**Pull request merged**
