### PR TITLE
hyprland.pc: modify include dir

### LINKED ISSUE #5896: hyprpm update - failed to install headers with error code 2
### Hyprland Version

<details> <summary>System/Version info</summary>

```
Hyprland, built from branch main at commit 1ed1ce9506e65f76fe5236194516f23d662bba0b  (internal: new shared_ptr and weak_ptr implementation (5883)).
Date: Sun May 5 18:16:00 2024
Tag: v0.40.0-9-g1ed1ce95, commits: 4615

flags: (if any)
```

</details>

### Bug or Regression?

Bug

### Description

```
[v] version returned: Hyprland, built from branch main at commit 1ed1ce9506e65f76fe5236194516f23d662bba0b  (internal: new shared_ptr and weak_ptr implementation (5883)).
Date: Sun May 5 18:16:00 2024
Tag: v0.40.0-9-g1ed1ce95, commits: 4615

flags: (if any)


[v] parsed commit 1ed1ce9506e65f76fe5236194516f23d662bba0b at branch main on Sun May 5 18:16:00 2024, commits 4615

! Cloning https://github.com/hyprwm/hyprland, this might take a moment.                                                                                                              
[v] will shallow since: dom apr 28 18:16:00 2024                                                                                                                                     

✔ cloned                                                                                                                                                                             
[v] git returned (co): Already on 'main'                                                                                                                                             
Your branch is up to date with 'origin/main'.

[v] git returned (rs): rm 'subprojects/tracy'                                                                                                                                        
HEAD is now at 1ed1ce9 internal: new shared_ptr and weak_ptr implementation (#5883)

✔ checked out to running ver                                                                                                                                                         
! configuring Hyprland                                                                                                                                                               
[v] setting PREFIX for cmake to /home/pbo/.local/share/hyprpm/headersRoot                                                                                                            

-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Gathering git info
-- Found Python3: /usr/bin/python3.12 (found version "3.12.3") found components: Interpreter
Building itab.c/itab.h...
-- Setting up wlroots
-- Found PkgConfig: /usr/bin/pkg-config (found version "2.1.1")
-- Found WaylandScanner at /usr/bin/wayland-scanner
-- Found wayland-protocols at //usr/share/wayland-protocols
-- Configuring Hyprland in Release with CMake
-- Checking deps...
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Found OpenGL: /usr/lib/libOpenGL.so  found components: GLES3
-- Checking for modules 'xkbcommon;uuid;wayland-server;wayland-client;wayland-cursor;wayland-protocols;cairo;pango;pangocairo;pixman-1;libdrm;libinput;hwdata;libseat;libdisplay-info;libliftoff;libudev;gbm;hyprwayland-scanner>=0.3.4;hyprlang>=0.3.2;hyprcursor>=0.1.7'
--   Found xkbcommon, version 1.7.0
--   Found uuid, version 2.40.0
--   Found wayland-server, version 1.22.91
--   Found wayland-client, version 1.22.91
--   Found wayland-cursor, version 1.22.91
--   Found wayland-protocols, version 1.36
--   Found cairo, version 1.18.0
--   Found pango, version 1.52.2
--   Found pangocairo, version 1.52.2
--   Found pixman-1, version 0.43.4
--   Found libdrm, version 2.4.120
--   Found libinput, version 1.25.0
--   Found hwdata, version 0.382
--   Found libseat, version 0.8.0
--   Found libdisplay-info, version 0.1.1
--   Found libliftoff, version 0.4.1
--   Found libudev, version 255
--   Found gbm, version 24.0.6-arch1.2
--   Found hyprwayland-scanner, version 0.3.4
--   Found hyprlang, version 0.5.1
--   Found hyprcursor, version 0.1.7
-- Looking for execinfo.h
-- Looking for execinfo.h - found
-- Configuration supports execinfo
-- Looking for backtrace in execinfo
-- Looking for backtrace in execinfo - not found
-- Looking for sys/timerfd.h
-- Looking for sys/timerfd.h - found
-- Checking for module 'epoll-shim'
--   Package 'epoll-shim', required by 'virtual:world', not found
-- XWAYLAND Enabled (NO_XWAYLAND not defined) checking deps...
-- Checking for modules 'xcb;xwayland;xcb-util;xcb-render;xcb-xfixes;xcb-icccm;xcb-composite;xcb-res;xcb-ewmh'
--   Found xcb, version 1.17.0
--   Found xwayland, version 21.1.99.1
--   Found xcb-util, version 0.4.1
--   Found xcb-render, version 1.17.0
--   Found xcb-xfixes, version 1.17.0
--   Found xcb-icccm, version 0.4.2
--   Found xcb-composite, version 1.17.0
--   Found xcb-res, version 1.17.0
--   Found xcb-ewmh, version 0.4.2
-- Checking for module 'xcb-errors'
--   Found xcb-errors, version 1.0.1
-- SYSTEMD support is requested (NO_SYSTEMD not defined)...
-- Setting precompiled headers
-- Setting link libraries
-- Checking for module 'tomlplusplus'
--   Found tomlplusplus, version 3.4.0
-- Configuring done (1.7s)
-- Generating done (0.0s)
-- Build files have been written to: /tmp/hyprpm/hyprland-pbo/build

[v] meson returned: The Meson build system                                                                                                                                           
Version: 1.4.0
Source dir: /tmp/hyprpm/hyprland-pbo/subprojects/wlroots-hyprland
Build dir: /tmp/hyprpm/hyprland-pbo/subprojects/wlroots-hyprland/build
Build type: native build
Project name: wlroots
Project version: 0.18.0-dev
C compiler for the host machine: cc (gcc 13.2.1 "cc (GCC) 13.2.1 20240417")
C linker for the host machine: cc ld.bfd 2.42.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wundef: YES 
Compiler for C supports arguments -Wlogical-op: YES 
Compiler for C supports arguments -Wmissing-include-dirs: YES 
Compiler for C supports arguments -Wold-style-definition: YES 
Compiler for C supports arguments -Wpointer-arith: YES 
Compiler for C supports arguments -Winit-self: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wimplicit-fallthrough=2: YES 
Compiler for C supports arguments -Wendif-labels: YES 
Compiler for C supports arguments -Wstrict-aliasing=2: YES 
Compiler for C supports arguments -Woverflow: YES 
Compiler for C supports arguments -Wmissing-prototypes: YES 
Compiler for C supports arguments -Walloca: YES 
Compiler for C supports arguments -Wno-missing-braces: YES 
Compiler for C supports arguments -Wno-missing-field-initializers: YES 
Compiler for C supports arguments -Wno-unused-parameter: YES 
Compiler for C supports arguments -fmacro-prefix-map=/prefix/to/hide=: YES 
Found pkg-config: YES (/usr/bin/pkg-config) 2.1.1
Run-time dependency wayland-server found: YES 1.22.91
Run-time dependency libdrm found: YES 2.4.120
Run-time dependency xkbcommon found: YES 1.7.0
Run-time dependency pixman-1 found: YES 0.43.4
Library m found: YES
Library rt found: YES
Run-time dependency wayland-protocols found: YES 1.36
Build-time dependency wayland-scanner found: YES 1.22.91
Program /usr/bin/wayland-scanner found: YES (/usr/bin/wayland-scanner)
Has header "linux/dma-buf.h" : YES 
Run-time dependency egl found: YES 1.5
Run-time dependency gbm found: YES 24.0.6-arch1.2
Run-time dependency glesv2 found: YES 3.2
Program ./embed.sh found: YES (/tmp/hyprpm/hyprland-pbo/subprojects/wlroots-hyprland/render/gles2/shaders/./embed.sh)
Dependency pixman-1 found: YES 0.43.4 (cached)
Dependency gbm found: YES 24.0.6-arch1.2 (cached)
Checking for function "gbm_bo_get_fd_for_plane" with dependency gbm: YES 
Run-time dependency libudev found: YES 255
Run-time dependency libseat found: YES 0.8.0
Build-time dependency hwdata found: YES 0.382
Run-time dependency libdisplay-info found: YES 0.1.1
Run-time dependency libliftoff found: YES 0.4.1
Run-time dependency libinput found: YES 1.25.0
Run-time dependency xcb found: YES 1.17.0
Run-time dependency xcb-dri3 found: YES 1.17.0
Run-time dependency xcb-present found: YES 1.17.0
Run-time dependency xcb-render found: YES 1.17.0
Run-time dependency xcb-renderutil found: YES 0.3.10
Run-time dependency xcb-shm found: YES 1.17.0
Run-time dependency xcb-xfixes found: YES 1.17.0
Run-time dependency xcb-xinput found: YES 1.17.0
Run-time dependency wayland-client found: YES 1.22.91
Run-time dependency xwayland found: YES 21.1.99.1
Dependency xcb found: YES 1.17.0 (cached)
Run-time dependency xcb-composite found: YES 1.17.0
Run-time dependency xcb-ewmh found: YES 0.4.2
Run-time dependency xcb-icccm found: YES 0.4.2
Dependency xcb-render found: YES 1.17.0 (cached)
Run-time dependency xcb-res found: YES 1.17.0
Dependency xcb-xfixes found: YES 1.17.0 (cached)
Run-time dependency xcb-errors found: YES 1.0.1
Checking for function "xcb_xfixes_set_client_disconnect_mode" with dependencies xcb, xcb-composite, xcb-ewmh, xcb-icccm, xcb-render, xcb-res, xcb-xfixes, xcb-errors: YES 
Configuring config.h using configuration
Configuring version.h using configuration
Configuring config.h using configuration
Message: Patches found. Applying...
Build targets in project: 136

wlroots 0.18.0-dev

    drm-backend     : YES
    x11-backend     : YES
    libinput-backend: YES
    xwayland        : YES
    gles2-renderer  : YES
    vulkan-renderer : NO
    gbm-allocator   : YES
    session         : YES
    xcb-errors      : YES
    egl             : YES
    libliftoff      : YES

  User defined options
    examples        : false
    renderers       : gles2

Found ninja-1.12.0 at /usr/bin/ninja
                                                 
✔ configured Hyprland                                                                                                                                                                
[v] installation will run: sed -i -e "s#PREFIX = /usr/local#PREFIX = /home/pbo/.local/share/hyprpm/headersRoot#" /tmp/hyprpm/hyprland-pbo/Makefile && cd /tmp/hyprpm/hyprland-pbo && make installheaders
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━  4 / 5  Installing sources[v] installer returned: rm -fr /home/pbo/.local/share/hyprpm/headersRoot/include/hyprland              
mkdir -p /home/pbo/.local/share/hyprpm/headersRoot/include/hyprland
mkdir -p /home/pbo/.local/share/hyprpm/headersRoot/include/hyprland/protocols
mkdir -p /home/pbo/.local/share/hyprpm/headersRoot/include/hyprland/wlroots-hyprland
mkdir -p /home/pbo/.local/share/hyprpm/headersRoot/share/pkgconfig
find src -name '*.h*' -print0 | cpio --quiet -0dump /home/pbo/.local/share/hyprpm/headersRoot/include/hyprland
cd subprojects/wlroots-hyprland/include && find . -name '*.h*' -print0 | cpio --quiet -0dump /home/pbo/.local/share/hyprpm/headersRoot/include/hyprland/wlroots-hyprland && cd ../../..
cd subprojects/wlroots-hyprland/build/include && find . -name '*.h*' -print0 | cpio --quiet -0dump /home/pbo/.local/share/hyprpm/headersRoot/include/hyprland/wlroots-hyprland && cd ../../../..
cp ./protocols/*.h /home/pbo/.local/share/hyprpm/headersRoot/include/hyprland/protocols
cp ./protocols/*.hpp /home/pbo/.local/share/hyprpm/headersRoot/include/hyprland/protocols
cp ./build/hyprland.pc /home/pbo/.local/share/hyprpm/headersRoot/share/pkgconfig
if [ -d /usr/share/pkgconfig ]; then cp ./build/hyprland.pc /usr/share/pkgconfig 2>/dev/null || true; fi
chmod -R 755 /home/pbo/.local/share/hyprpm/headersRoot/include/hyprland
chmod 755 /home/pbo/.local/share/hyprpm/headersRoot/share/pkgconfig

✖ failed to install headers with error code 2                                                                                                                                        
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5 / 5  Failed                                                                                                                   

✖ Headers missing. Please run hyprpm update to fix those.
```

### How to reproduce

`hyprpm update -v`

### Crash reports, logs, images, videos

_No response_

### PR DESCRIPTION
**Pull request by LOSEARDES77**
#### Describe your PR, what does it fix/add?
Modifyed the hyprland.pc.in to fix #5896

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
no

#### Is it ready for merging, or does it need work?
yes

### CODE REVIEW

**Comment by fufexan** [comment]
This will break normal hyprland installation. `@INCLUDEDIR@` is replaced by CMake with its own `CMAKE_INSTALL_INCLUDEDIR`, which already includes `PREFIX` in the generated path.

**Comment by LOSEARDES77** [comment]
> This will break normal hyprland installation. `@INCLUDEDIR@` is replaced by CMake with its own `CMAKE_INSTALL_INCLUDEDIR`, which already includes `PREFIX` in the generated path.

so should thid work?
`includedir=@PREFIX@/include`

**Comment by LOSEARDES77** [comment]
Befor the commit that broke it it was like this:
`includedir=${prefix}/include`
So this shoudn't break cmake commit right?

**Comment by fufexan** [comment]
That probably works but will break Nix. I'll update my PR in a bit.

**Comment by LOSEARDES77** [comment]
ill then close this

**Pull request closed without merging**
