### PR TITLE
fix NoSymbol keybinds

### LINKED ISSUE #6721: Key 248 and other NoSymbol keys not working
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit 918d8340afd652b011b937d29d5eea0be08467f5  (flake.lock: update).
Date: Tue Jun 25 12:06:02 2024
Tag: v0.41.2, commits: 4886

flags: (if any)


System Information:
System name: Linux
Node name: Murmaider
Release: 6.6.35-2-lts
Version: #1 SMP PREEMPT_DYNAMIC Fri, 21 Jun 2024 21:05:23 +0000


GPU information: 
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA104 [Geforce RTX 3070 Ti Laptop GPU] [10de:24a0] (rev a1) (prog-if 00 [VGA controller])
06:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev c7) (prog-if 00 [VGA controller])


os-release: NAME="EndeavourOS"
PRETTY_NAME="EndeavourOS"
ID="endeavouros"
ID_LIKE="arch"
BUILD_ID="2023.11.17"
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://endeavouros.com"
DOCUMENTATION_URL="https://discovery.endeavouros.com"
SUPPORT_URL="https://forum.endeavouros.com"
BUG_REPORT_URL="https://forum.endeavouros.com/c/general-system/endeavouros-installation"
PRIVACY_POLICY_URL="https://endeavouros.com/privacy-policy-2"
LOGO="endeavouros"


plugins:
```

</details>

### Description

this setting `bind = , 248, exec, grim -g "$(slurp)"` does not work for some mysterious reason (it used to a few versions back so this is some kind of regression), changing the key to a different one works, and reading another key by it's keycode instead of keysym also works, so it's like Hyprland just really does not like this specific keycode.

`wev` and `xev` both display the key properly when it's pressed (it's FN+Print on my laptop) but Hyprland will not act on it.

This is on Hyprland 1.41.2-2

On an older version of Hyprland (forgot exactly, but it was new, 1.40 at oldest, possibly as recent as 1.41.1) I was also having an issue where when I pressed this same key, many other keybinds would fire off in hyprland (volume up/down, xf86launch, brightness...) before that version the key worked completely fine on Hyprland and i've been using it for months.

The same keybind also works fine on i3.

From wev:
```
[14:     wl_keyboard] key: serial: 36238; time: 19877312; key: 248; state: 1 (pressed)
                      sym: NoSymbol     (0), utf8: ''
```

My haphazard guess would be that this issue might have something to do with the keysym being NoSymbol.

### How to reproduce

set `bind = , 248, exec, grim -g "$(slurp)"` and press that button.

### PR DESCRIPTION
**Pull request by ikalco**
#### Describe your PR, what does it fix/add?
fixes #6721

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
this should still work for #6548
if you want we can @ the guy to test

#### Is it ready for merging, or does it need work?
yes

### CODE REVIEW

**Comment by vaxerski** [comment]
ye please @ em

**Comment by ikalco** [comment]
@JaKooLit, sorry to ping but can you test this pr with plugging your charger to make sure this doesn't regress #6548

**Comment by JaKooLit** [comment]
> @JaKooLit, sorry to ping but can you test this pr with plugging your charger to make sure this doesn't regress #6548

I will try once Im off work... I will let you know

**Review by JaKooLit — APPROVED** [review]
tested. It does not affect this

https://github.com/hyprwm/Hyprland/issues/6548

**Review by vaxerski — APPROVED** [review]

**Pull request merged**
