### PR TITLE
Better multi monitor animations

### PR DESCRIPTION
**Pull request by thejch**
#### Describe your PR, what does it fix/add?
Currently there is animation when a window is moved into a monitor, but no animation when a window is moved out of a monitor. This PR adds animations for when a window is moved out of or through a monitor.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
Shouldn't affect single monitor use at all. But maybe double check for potential gpu impact on multi monitors, since there are some damage changes

#### Is it ready for merging, or does it need work?
Ready

### CODE REVIEW

**Comment by vaxerski** [comment]
what? I don't understand

**Comment by thejch** [comment]
> what? I don't understand



Before:

https://github.com/hyprwm/Hyprland/assets/66577496/dca97e09-554d-475e-8115-cd65fc5ee478



After:

https://github.com/hyprwm/Hyprland/assets/66577496/7f80bdd3-0a8a-4ddf-a19a-0e75107ebc94

**Comment by vaxerski** [comment]
right, I get you

**Review by vaxerski — APPROVED** [review]
lgtm

**Pull request merged**
