### PR TITLE
Fix the fix

### PR DESCRIPTION
**Pull request by yavko**
#### Describe your PR, what does it fix/add?
Fixes the pr

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
no

### CODE REVIEW

**Comment by vaxerski** [comment]
conflicts

**Comment by yavko** [comment]
> conflicts

resolved

**Comment by yavko** [comment]
Okay it seems that the build succeeded, sorry for the broken pr again

**Comment by vaxerski** [comment]
it's-a fine

**Pull request merged**
