### PR TITLE
Fixed wrong focus changes when moving background workspaces

### PR DESCRIPTION
**Pull request by dtop129**
#### Describe your PR, what does it fix/add?
When moving background workspaces between monitors, sometimes the focus of the active window would unexpectedly change

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
No

#### Is it ready for merging, or does it need work?
Ready

### CODE REVIEW

**Comment by vaxerski** [comment]
it would be nice to _not_ change the wlroots tag in this PR.

**Comment by dtop129** [comment]
Fixed

**Review by vaxerski — APPROVED** [review]
gangsta

**Comment by YodaEmbedding** [comment]
After this commit, `hyprctl dispatch workspace previous` seems to behave unpredictably for 3+ workspaces.

**Pull request merged**
