### PR TITLE
Schedule a frame on notification creation

### LINKED ISSUE #3552: "Hyprctl notify" notifications only appear after another input has been made
### Hyprland Version

Hyprland, built from branch  at commit 1b48642fd15c433c53876f1b933dcd46265caf8f dirty (). Tag: v0.30.0

### Bug or Regression?

Bug

### Description

I have the following lines in my hyprland.conf, to see the time and my current workspace at a glance.

`bind = $mainMod, D, exec, hyprctl notify -1 2000 0 "$(date)"`
`bind = $mainMod, W, exec, hyprctl notify -1 2000 0 "$(hyprctl activeworkspace | head -n 1)"`

My expected behaviour is that the notification would pop up instantly with the requested info.
What occurs is that the notification only appears if I immediately follow the "mainMod + D or W" input with any other input, such as moving the mouse, typing something, etc. Additionally, if I have a video or music playing, the notification behaves properly, appearing instantly.
Not sure if this is a bug or intended behaviour.

I am also open to using another tool entirely if this is not an intended use case of "hyprctl notify"

Thank you for your help!

### How to reproduce

Paste the above lines into your hyprland.conf. Input the relevant keybinding.

### Crash reports, logs, images, videos

[hyprland.log](https://github.com/hyprwm/Hyprland/files/12876056/hyprland.log)

Relevant lines start at 356.

### PR DESCRIPTION
**Pull request by FakeMichau**
#### Describe your PR, what does it fix/add?
Should resolve #3552 by manually scheduling a frame

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
no

#### Is it ready for merging, or does it need work?
It's ready

### CODE REVIEW

**Review by vaxerski — COMMENTED** [review]
`CCompositor::scheduleFrameForMonitor`

**Comment by vaxerski** [comment]
wouldn't it be better to move it to `addNotification`? this way we won't have any more bugs with the same thing elsweyr

**Comment by FakeMichau** [comment]
Yea I totally agree, don't know why I didn't think of it.

**Review by vaxerski — APPROVED** [review]
steh auf!

**Pull request merged**
