### PR TITLE
Prevent stretching when resizing window

### PR DESCRIPTION
**Pull request by phonetic112**
kinda fixes https://github.com/hyprwm/Hyprland/issues/5044. It no longer makes the surface stretch but a frame of the original surface is still visible.

### CODE REVIEW

**Review by vaxerski — COMMENTED** [review]
this is not the way to do this

**Comment by phonetic112** [comment]
how about this

**Comment by vaxerski** [comment]
also no. "reported size" is the last size the window has ACKd. in ::setWindowSize, the window has not ACKd it yet. The bug is in the renderer, not the protocol handling

**Comment by phonetic112** [comment]
third time's a charm

**Comment by vaxerski** [comment]
all three changes are wrong. I'd rather not touch this code if I were you. Give me a test client and I'll look into it.

**Comment by phonetic112** [comment]
what do you mean by test client? just resize a window

**Comment by vaxerski** [comment]
but which window?

And how?

Are windows even real?

What is a window?

**Comment by phonetic112** [comment]
Any window will work. Just resize the window to the smallest it can go and then toggle floating on it. It's easier to notice if you turn animations off

**Pull request closed without merging**
