### PR TITLE
fix fullscreen bug. #1821

### PR DESCRIPTION
**Pull request by lisuke**
fix issues: #1821

The full screen window can be resized.

### CODE REVIEW

**Comment by vaxerski** [comment]
image

nice fix?

**Comment by JustSimplyKyle** [comment]
https://github.com/hyprwm/Hyprland/commit/a9962a1abb27f33fcbe15bbc933d84a21caab415

**Comment by lisuke** [comment]
Why？Bugs still exist.

**Comment by lisuke** [comment]
The merge has no effect

**Comment by vaxerski** [comment]
what the fuck happened? I didn't merge this.

**Comment by vaxerski** [comment]
> The merge has no effect

your PR is empty

**Comment by lisuke** [comment]
> > The merge has no effect
> 
> your PR is empty

https://github.com/hyprwm/Hyprland/pull/1831

**Pull request merged**
