### PR TITLE
fixing gentoo ebuild due to lack of precompiled headrs in build env

### PR DESCRIPTION
**Pull request by brettalcox**
#### Describe your PR, what does it fix/add?
Gentoo ebuild was failing due to lack of precompiled headers in build env 

#### Is it ready for merging, or does it need work?

Ready for merge

### CODE REVIEW

**Review by vaxerski — COMMENTED** [review]
Avoid putting includes in headers... put them in .cpp wherever they are needed, please.

**Comment by brettalcox** [comment]
@vaxerski it's specifically no happy with this: https://github.com/hyprwm/Hyprland/blob/448a537615b4b0337f5dcf9c42622f8ede397a52/src/layout/IHyprLayout.hpp#L11

**Comment by vaxerski** [comment]
`class CGradientValueData;`? forward declare it

**Comment by brettalcox** [comment]
@vaxerski fixed dat here https://github.com/hyprwm/Hyprland/commit/faa1d011fe51f379ecde88514b1ba641d1c2a6ed

**Review by vaxerski — APPROVED** [review]

**Pull request merged**
