### PR TITLE
hyprctl: add modkeys to binds command

### PR DESCRIPTION
**Pull request by davc0n**
#### Describe your PR, what does it fix/add?

https://github.com/hyprwm/Hyprland/issues/8606

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)

No

#### Is it ready for merging, or does it need work?

Ready

### CODE REVIEW

**Review by vaxerski — COMMENTED** [review]
isn't that just duplicating info

**Comment by davc0n** [comment]
Not sure, that's the current output:
```
binde
	modmask: 65
	submap: 
	key: l
	keycode: 0
	catchall: false
	description: 
	dispatcher: moveactive
	arg: 20 0
```

There would be an additional line: `modkeys: SUPER SHIFT`
This information is not directly available.

Or do you mean it should be computed on the fly, rather than stored in `SKeybind` ?

**Comment by vaxerski** [comment]
> This information is not directly available

it is. See modmask.

**Comment by davc0n** [comment]
With direct I meant explicit.
Must remember which keys belongs to the given code.

Anyway if you believe that's useless just close this PR and the related issue as not planned.

**Comment by vaxerski** [comment]
> Must remember which keys belongs to the given code.

it's constant, it doesn't change.

Anyways, as suggested.

**Pull request closed without merging**
