### PR TITLE
Handle multiple keyboards with switchXKBLayoutRequest

### PR DESCRIPTION
**Pull request by leftas**
#### Describe your PR, what does it fix/add?

It fixes multiple keyboards issue (see picture below) when changing xkb layout with hyprctl.

image
 

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)

There is a problem with how CVarList parses things - it ignores quotes("). Hence when you supply the first parameter, keyboard name, with spaces (see in the picture above) it interprets the keyboard name and param wrong. So either this request has to change the separator, add a wiki note regarding this issue, or change how CVarList parses things. 

#### Is it ready for merging, or does it need work?

Yes.

### CODE REVIEW

**Comment by vaxerski** [comment]
you mean duplicated keyboard names? That's a problem in keyboard naming, not switchxkblayout.

**Comment by leftas** [comment]
> you mean duplicated keyboard names? That's a problem in keyboard naming, not switchxkblayout.

Oh yes, I agree, totally. But then either Hyprland should give a unique attribute(name/id or whatever) for all devices or iterate through all - like it was done here (I don't like this approach, tho). An additional argument for a unique attribute would be as I explained about the CVarList problem - that a lot of keyboards have spaces in their name and then it is failing to interpret the correct name and value.

**Comment by vaxerski** [comment]
spaces should not be showing anymore, update hyprland.

**Comment by vaxerski** [comment]
should be fixed with 409ac12f236c06cbb28756239e1d1536078b33bb

**Comment by leftas** [comment]
Nice, thank you:)

**Pull request closed without merging**
