### PR TITLE
CMake, Meson: suproject improvements

### PR DESCRIPTION
**Pull request by fufexan**
#### Describe your PR, what does it fix/add?

Meson: try to find udis86 through pkgconfig, fallback to subproject. Adds Nix overlay with udis86 fork -> 2 remaining subproject for Nix
Nix: re-add hyprland-protocols -> 1 remaining subprojects for nix
CMake: use hyprland-protocols from pkg-config, fallback to subproject
CMake: use udis86 from pkg-config, fallback to subproject
Meson: add tracy dependency -> no more subproject deps for nix, unless wanted

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)

Tested various toggles, subprojects/no subprojects. If anyone wants to test feel free.

#### Is it ready for merging, or does it need work?

Should be ready.

### CODE REVIEW

**Review by vaxerski — COMMENTED** [review]
are there any version differences? How should we differentiate udis outside of the pc file?

Distro packagers could include it without using the correct fork, or could be using a different fork

**Comment by fufexan** [comment]
https://repology.org/project/udis86/versions reveals that most distros use the original project, with the exception being AUR versions of canihavesomecoffee. I think we're safe. I could also add a message telling users to "MAKE SURE TO USE https://github.com/canihavesomecoffee/udis86".

**Comment by vaxerski** [comment]
sure, I guess

**Comment by vaxerski** [comment]
> reveals that most distros use the original project

doesnt mean they dont add a pc file?

**Comment by fufexan** [comment]
> > reveals that most distros use the original project
> 
> doesnt mean they dont add a pc file?

I've looked through the build files and they don't. Only Alpine uses canihavesomecoffee's fork and already patches Hyprland to make use of the system udis86 (https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/testing/hyprland/use-system-installed-udis86.patch).

**Review by vaxerski — APPROVED** [review]
pineapple 2.99

**Pull request merged**
