### PR TITLE
fix changeWindowZOrder

### PR DESCRIPTION
**Pull request by Aqa-Ib**
#### Describe your PR, what does it fix/add?
Fixes https://github.com/hyprwm/Hyprland/issues/8443

#### Is it ready for merging, or does it need work?
ready

### CODE REVIEW

**Comment by Aqa-Ib** [comment]
This was introduced in https://github.com/hyprwm/Hyprland/pull/6877
@UjinT34 do you have an insight ?

**Comment by UjinT34** [comment]
Without this commit https://github.com/hyprwm/Hyprland/pull/6877/commits/507df67fa504522bd907ad1e899fefeb5364bdf3 every click on a fullscreen floating window will result in unneeded reordering which will add damage to monitor and schedule an unwanted frame. Maybe it returns too early. `g_pHyprRenderer->damageMonitor` shouldn't be called when the clicked window is already on top and fullscreen.

**Comment by Aqa-Ib** [comment]
OK, I found that it can't return before executing `pWindow->m_bCreatedOverFullscreen = true;` because `CInputManager::mouseMoveUnified` needs that in order to work properly.

So I moved that operation before the early return. I think that this is fine in terms of performance; could it be done better or is it good enough?

**Review by vaxerski — APPROVED** [review]

**Comment by vaxerski** [comment]
@UjinT34 is this version fine? (vrr stuff)

**Comment by UjinT34** [comment]
It's fine

**Pull request merged**
