### PR TITLE
drm dumb buffers for cursors

### PR DESCRIPTION
**Pull request by vaxerski**
This adds support for aq's drm_dumb buffers to render cursors via the cpu.

For me on amd this nukes the entire system atm idk will have to debug

deps on https://github.com/hyprwm/aquamarine/pull/104

gated behind `cursor:use_cpu_buffer`

### CODE REVIEW

**Comment by Honkazel** [comment]
> gated behind `cursor:use_cpu_rendering`

Eh?
image
Also hyprland shitting itself for me too, but at least i can do tty switch

**Comment by Honkazel** [comment]
> [ERR] [AQ] atomic drm request: failed to commit: Invalid argument, flags: ATOMIC_NONBLOCK PAGE_FLIP_EVENT 
[ERR] [AQ] atomic drm request: failed to commit: Invalid argument, flags: ATOMIC_ALLOW_MODESET PAGE_FLIP_EVENT 
[ERR] [AQ] atomic drm request: failed to commit: Invalid argument, flags: ATOMIC_NONBLOCK PAGE_FLIP_EVENT 
[ERR] [AQ] atomic drm request: failed to commit: Invalid argument, flags: ATOMIC_ALLOW_MODESET PAGE_FLIP_EVENT 
[ERR] [AQ] atomic drm request: failed to commit: Invalid argument, flags: ATOMIC_NONBLOCK PAGE_FLIP_EVENT 
[ERR] [AQ] atomic drm request: failed to commit: Invalid argument, flags: ATOMIC_NONBLOCK PAGE_FLIP_EVENT 
[ERR] [AQ] atomic drm request: failed to commit: Invalid argument, flags: ATOMIC_NONBLOCK PAGE_FLIP_EVENT 
[ERR] [AQ] atomic drm request: failed to commit: Invalid argument, flags: ATOMIC_NONBLOCK PAGE_FLIP_EVENT 
[ERR] [AQ] atomic drm request: failed to commit: Invalid argument, flags: ATOMIC_NONBLOCK PAGE_FLIP_EVENT 

Eh?

**Comment by vaxerski** [comment]
can you get a drm log? I can't really when my entire kernel dies

ye option name typo

**Comment by Honkazel** [comment]
[dmesg.log](https://github.com/user-attachments/files/17691994/dmesg.log)

**Comment by vaxerski** [comment]
> Cursor dimension 0x0 not supported

huh, where did I miss this

**Comment by UjinT34** [comment]
Clearing buffer is not right. It's white.
Copying doesn't follow the required stripe size. Chunks of the texture fill the top rows of the buffer.
I don't think it is possible to copy a smaller texture in one go

**Comment by vaxerski** [comment]
> Clearing buffer is not right. It's white.

That was just for testing purposes I realize

> Copying doesn't follow the required stripe size. Chunks of the texture fill the top rows of the buffer.
I don't think it is possible to copy a smaller texture in one go

well yeah we'll loop memsets, again, I was just testing

**Comment by UjinT34** [comment]
Seems to work fine with copying fixed
https://github.com/hyprwm/Hyprland/compare/drm-copy-cursor...UjinT34:Hyprland:drm-copy-cursor

**Comment by vaxerski** [comment]
are you sure you enabled them? What gpu? Both me and honkazel get a crash

**Comment by UjinT34** [comment]
Works on nvidia.
Doesn't crash on intel, but cursor is invisible and rendering hangs for several seconds from time to time (when cursor texture changes?):
```
[LOG] Monitor eDP-1 data dump: res 2880x1920@120.00Hz, scale 1.50, transform 0, pos 0x0, 10b 0
[LOG] [CXDGOutputProtocol] updating all xdg_output heads
[hc] loadThemeStyle: loading for size 60
[hc] getShapesC: found 1 images for left_ptr
[TRACE] [AQ] atomic moveCursor
[TRACE] [AQ] CDRMOutput::scheduleFrame: reason 4, needsFrame true, isPageFlipPending true, frameEventScheduled true
[LOG] [AQ] DRM Dumb: Allocated a new buffer with primeFD 359, size [Vector2D: x: 256, y: 256] and format AR24
[LOG] [AQ] DRM Dumb: Allocated a new buffer with primeFD 360, size [Vector2D: x: 256, y: 256] and format AR24
[LOG] [AQ] Swapchain: Reconfigured a swapchain to [Vector2D: x: 256, y: 256] AR24 of length 2
[TRACE] [cursor] buffer is 256x256 = 262144, texture is 60x60 = 14400
[TRACE] [pointer] hw transformed hotspot for eDP-1: [Vector2D: x: 10, y: 10]
[TRACE] [AQ] drm: CDRMFB: plane 0 has fd 360, got handle 2
[TRACE] [AQ] drm: Using drmModeAddFB2WithModifiers to import buffer into KMS: Size [Vector2D: x: 256, y: 256] with format AR24 and mod 0
[TRACE] [AQ] drm: new buffer 271
[LOG] [AQ] drm: Cursor buffer imported into KMS with id 271
[TRACE] [AQ] CDRMOutput::scheduleFrame: reason 3, needsFrame true, isPageFlipPending true, frameEventScheduled true
[TRACE] [AQ] CDRMOutput::scheduleFrame: reason 3, needsFrame true, isPageFlipPending true, frameEventScheduled true
[TRACE] [AQ] CDRMOutput::scheduleFrame: reason 3, needsFrame true, isPageFlipPending true, frameEventScheduled true
[TRACE] [AQ] drm: Committed a buffer, updating state
[TRACE] [AQ] drm: CDRMFB: buffer has drmfb attachment with fb 5db95a9f1340
[TRACE] [AQ] atomic addConnector blobs: mode_id 23, active 22, crtc_id 20, link_status 5, content_type 0
[TRACE] [AQ] atomic addConnector values: CRTC 82, mode 0
[TRACE] [AQ] atomic drm request: adding id 241 prop 20 with value 82
[TRACE] [AQ] atomic drm request: adding id 82 prop 22 with value 1
[TRACE] [AQ] atomic drm request: adding id 82 prop 24 with value 0
[TRACE] [AQ] atomic planeProps: prop blobs: src_x 9, src_y 10, src_w 11, src_h 12, crtc_w 15, crtc_h 16, fb_id 17, crtc_id 20, crtc_x 13, crtc_y 14
[TRACE] [AQ] atomic drm request: adding id 32 prop 9 with value 0
[TRACE] [AQ] atomic drm request: adding id 32 prop 10 with value 0
[TRACE] [AQ] atomic drm request: adding id 32 prop 11 with value 188743680
[TRACE] [AQ] atomic drm request: adding id 32 prop 12 with value 125829120
[TRACE] [AQ] atomic drm request: adding id 32 prop 15 with value 2880
[TRACE] [AQ] atomic drm request: adding id 32 prop 16 with value 1920
[TRACE] [AQ] atomic drm request: adding id 32 prop 17 with value 242
[TRACE] [AQ] atomic drm request: adding id 32 prop 20 with value 82
[TRACE] [AQ] atomic drm request: adding id 32 prop 13 with value 0
[TRACE] [AQ] atomic drm request: adding id 32 prop 14 with value 0
[TRACE] [AQ] atomic drm request: adding id 32 prop 21 with value 0
[TRACE] [AQ] atomic planeProps: prop blobs: src_x 9, src_y 10, src_w 11, src_h 12, crtc_w 15, crtc_h 16, fb_id 17, crtc_id 20, crtc_x 13, crtc_y 14
[TRACE] [AQ] atomic drm request: adding id 77 prop 9 with value 0
[TRACE] [AQ] atomic drm request: adding id 77 prop 10 with value 0
[TRACE] [AQ] atomic drm request: adding id 77 prop 11 with value 0
[TRACE] [AQ] atomic drm request: adding id 77 prop 12 with value 0
[TRACE] [AQ] atomic drm request: adding id 77 prop 15 with value 0
[TRACE] [AQ] atomic drm request: adding id 77 prop 16 with value 0
[TRACE] [AQ] atomic drm request: adding id 77 prop 17 with value 271
[TRACE] [AQ] atomic drm request: adding id 77 prop 20 with value 82
[TRACE] [AQ] atomic drm request: adding id 77 prop 13 with value 18446744073709551606
[TRACE] [AQ] atomic drm request: adding id 77 prop 14 with value 18446744073709551606
[ERR] [AQ] atomic drm request: failed to commit: Invalid argument, flags:
[TRACE] [AQ] Connector blob id 272: clock 798720, 2880x1920, vrefresh 120, name: 2880x1920
[TRACE] [AQ] atomic addConnector blobs: mode_id 23, active 22, crtc_id 20, link_status 5, content_type 0
[TRACE] [AQ] atomic addConnector values: CRTC 82, mode 272
[TRACE] [AQ] atomic drm request: adding id 241 prop 20 with value 82
[TRACE] [AQ] atomic drm request: adding id 82 prop 23 with value 272
[TRACE] [AQ] atomic drm request: adding id 241 prop 5 with value 0
[TRACE] [AQ] atomic drm request: adding id 241 prop 246 with value 8
[TRACE] [AQ] atomic drm request: adding id 82 prop 22 with value 1
[TRACE] [AQ] atomic drm request: adding id 82 prop 24 with value 0
[TRACE] [AQ] atomic planeProps: prop blobs: src_x 9, src_y 10, src_w 11, src_h 12, crtc_w 15, crtc_h 16, fb_id 17, crtc_id 20, crtc_x 13, crtc_y 14
[TRACE] [AQ] atomic drm request: adding id 32 prop 9 with value 0
[TRACE] [AQ] atomic drm request: adding id 32 prop 10 with value 0
[TRACE] [AQ] atomic drm request: adding id 32 prop 11 with value 188743680
[TRACE] [AQ] atomic drm request: adding id 32 prop 12 with value 125829120
[TRACE] [AQ] atomic drm request: adding id 32 prop 15 with value 2880
[TRACE] [AQ] atomic drm request: adding id 32 prop 16 with value 1920
[TRACE] [AQ] atomic drm request: adding id 32 prop 17 with value 242
[TRACE] [AQ] atomic drm request: adding id 32 prop 20 with value 82
[TRACE] [AQ] atomic drm request: adding id 32 prop 13 with value 0
[TRACE] [AQ] atomic drm request: adding id 32 prop 14 with value 0
[TRACE] [AQ] atomic drm request: adding id 32 prop 21 with value 0
[TRACE] [AQ] atomic planeProps: prop blobs: src_x 9, src_y 10, src_w 11, src_h 12, crtc_w 15, crtc_h 16, fb_id 17, crtc_id 20, crtc_x 13, crtc_y 14
[TRACE] [AQ] atomic drm request: adding id 77 prop 9 with value 0
[TRACE] [AQ] atomic drm request: adding id 77 prop 10 with value 0
[TRACE] [AQ] atomic drm request: adding id 77 prop 11 with value 0
[TRACE] [AQ] atomic drm request: adding id 77 prop 12 with value 0
[TRACE] [AQ] atomic drm request: adding id 77 prop 15 with value 0
[TRACE] [AQ] atomic drm request: adding id 77 prop 16 with value 0
[TRACE] [AQ] atomic drm request: adding id 77 prop 17 with value 271
[TRACE] [AQ] atomic drm request: adding id 77 prop 20 with value 82
[TRACE] [AQ] atomic drm request: adding id 77 prop 13 with value 18446744073709551606
[TRACE] [AQ] atomic drm request: adding id 77 prop 14 with value 18446744073709551606
[ERR] [AQ] atomic drm request: failed to commit: Invalid argument, flags: ATOMIC_ALLOW_MODESET PAGE_FLIP_EVENT 
[WARN] state.commit() failed in CMonitor::onCommit
```

**Comment by vaxerski** [comment]
found the problem I think, pull the aq MR and check again pls!

**Comment by Honkazel** [comment]
> found the problem I think, pull the aq MR and check again pls!

Now it works for me properly

**Comment by vaxerski** [comment]
WHAT

does it lag?

**Comment by Honkazel** [comment]
> WHAT
> 
> does it lag?

...No? It should?

**Comment by vaxerski** [comment]
No, I'm just surprised my code works

**Comment by vaxerski** [comment]
@fufexan I need a flake bump + meson (aq >= 0.4.5)

**Comment by gulafaran** [comment]
its rather spammy in log with

```
[ERR] [AQ] EGL (verifyDestinationDMABUF): FAIL, format is external-only
[ERR] [AQ] EGL (blit): failed to blit: destination dmabuf unsupported
[ERR] [AQ] drm: Backend requires blit, but cursor blit failed
```

and unsure how to know if its actually HW or not on this nvidia crud lol

**Comment by vaxerski** [comment]
mgpu nvidia will implode but thats nothing new isnt it

**Comment by Agent00Ming** [comment]
pointer cursor shape in blender, seems like garbage data every time the cursor shape changes back to  pointer
image

nvidia only (no mgpu)
`cursor:no_hardware_cursors` `false`
`cursor:use_cpu_buffer` `false`

**Comment by vaxerski** [comment]
check now @Agent00Ming, if still brok give trace log

**Comment by vaxerski** [comment]
try now?

**Comment by UjinT34** [comment]
`memset(data, 128, size);` fills a semi-transparent white square. This square doesn't have any corruption in blender other than real cursor texture. Working cursors are set with something like
```
[LOG] cursorImage request: shape 9 -> text
[TRACE] [cursor] buffer is 256x256 (875713089), texture is 40x40 (875713089)
```
and blender's:
```
[LOG] cursorImage request: surface 55a745195700
[TRACE] [cursor] buffer is 256x256 (875713089), texture is 32x32 (875713089)
```

`texData` is corrupted when created from blender's surface? `texture->m_iDrmFormat` value doesn't match the real format?
The corruption looks different every time. Incorrect pointer?

**Comment by vaxerski** [comment]
hm, odd, that should fill it with zeroes. I'll make it more explicit I guess?

**Comment by vaxerski** [comment]
better?

**Comment by UjinT34** [comment]
This might remove the corruption... but the cursor will be invisible. Looks like blender tries to render the default cursor from the cursor theme. The bug is somewhere on the way to `renderHWCursorBuffer` since `texture->dataCopy()` is empty. `m_bKeepDataCopy` is not set when it should?

**Comment by gulafaran** [comment]
> better?

seems to be corrupted just running in nested session, atleast over here

**Comment by vaxerski** [comment]
is blender using server side cursors?

**Comment by Agent00Ming** [comment]
Seems like client side cursors as it tried to use the xcursor theme when I had set a mismatched hyprcursor theme.

**Comment by vaxerski** [comment]
idk whats wrong then

**Comment by vaxerski** [comment]
@fufexan nix still fails xd

**Comment by fufexan** [comment]
Arch no pch fails with the same error. You forgor an include.

**Comment by vaxerski** [comment]
honestly I'd just push this and see how many peopel actually see a problem, and try and fix it later.

@fufexan fuffie can I get a conflict fix

**Comment by Agent00Ming** [comment]
Fair enough, it's not a huge showstopper tbh. I've only seen this in blender and nowhere else and a hunch that the issue in https://github.com/hyprwm/Hyprland/pull/7110#issuecomment-2259182750 was only partially fixed at the time.

**Comment by Colt-M16A1** [comment]
i still get this issue #6962

**Comment by vaxerski** [comment]
yes this is unrelated

**Pull request merged**
