### PR TITLE
nix: add missing hwdata dependency

### PR DESCRIPTION
**Pull request by andresilva**
#### Describe your PR, what does it fix/add?

Adds missing hwdata to the nix build.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)

No

#### Is it ready for merging, or does it need work?

Yes

### CODE REVIEW

**Comment by fufexan** [comment]
I don't see it being missing. It most likely comes from `wlroots.buildInputs` already.

**Comment by andresilva** [comment]
Broken by `https://github.com/NixOS/nixpkgs/pull/292415/commits/3175915a176486dc96bcdecb752549cfea264c8b`. Maybe the proper thing to do is to propagate `nativeBuildInputs` as well?

**Comment by fufexan** [comment]
Propagating nativeBuildInputs works. Added that in a more general commit (c7fbc30b).

**Comment by fufexan** [comment]
Thanks for the explanations!

**Pull request closed without merging**
