### PR TITLE
nix: use meson

### PR DESCRIPTION
**Pull request by diniamo**
CC @fufexan

### CODE REVIEW

**Review by fufexan — APPROVED** [review]

**Comment by JohnRTitor** [comment]
I wonder why though, didn't we explicitly move from Meson to CMake? And I'll make a guess here that only one works here at any given time, presumably CMake.

**Comment by JohnRTitor** [comment]
Oh I guess CMake building of Nix package is being phased out (#7778). If it solves issues like this https://github.com/hyprwm/Hyprland/issues/7508#issuecomment-2343619191, I have no complaints.

**Comment by fufexan** [comment]
There is a possibility, but the main reason we've moved back to meson is due to the faster builds (almost twice as fast).

**Comment by diniamo** [comment]
Yes, as weird is at is, meson builds twice as fast.

**Comment by vaxerski** [comment]
sounds wrong and doesn't seem to be the case on my end. CMake builds a bit faster.

Have you tried:
 - not using ninja for cmake
 - building w/o pch

**Comment by diniamo** [comment]
@fufexan ?

**Comment by fufexan** [comment]
2 hours and a bad graph later, I'm back with some rough results
Hyprland build systems build times

Looks like we'll go back to using CMake.

**Pull request merged**
