### PR TITLE
Replace code of conduct with NCoC

### PR DESCRIPTION
**Pull request by binex-dsk**
#### Describe your PR, what does it fix/add?
Better CoC that doesn't add needless politics

### CODE REVIEW

**Comment by vaxerski** [comment]
very funny

**Comment by binex-dsk** [comment]
No discussion at all? Wow!

**Comment by Eclextic** [comment]
Ngl doesn't look that bad (The link at the bottom lol) XDDDD

**Comment by binex-dsk** [comment]
> Ngl doesn't look that bad (The link at the bottom lol) XDDDD

Very depressing that a project claiming inclusion doesn't want to switch to a CoC that is inherently more inclusive than the Contributor Covenant (aka False Covenant, the only true Covenant is that of the Lord)

**Comment by vars1ty** [comment]
It's his own project, he decides what CoC/NCoC/BingBongCoC he wants to use.

The very least you could have done is improve the pre-existing one, rather than replacing it with some URL to an external repository, because nobody is gonna it serious when you do it like that, but it's to be expected.

**Comment by binex-dsk** [comment]
> It's his own project, he decides what CoC/NCoC/BingBongCoC he wants to use.
> 
> The very least you could have done is improve the pre-existing one, rather than replacing it with some URL to an external repository, because nobody is gonna it serious when you do it like that, but it's to be expected.

"This project adheres to No Code of Conduct.  We are all adults.  We accept anyone's contributions.  Nothing else matters."

That sounds an awful lot like an improvement to the existing code of conduct.

**Comment by binex-dsk** [comment]
Matter of fact here's a better CoC.

## Contributor CoC Slop
Please do not be mean

**Comment by binex-dsk** [comment]
Actually, I have a better idea...

**Pull request closed without merging**
