### PR TITLE
Add hyprpm, a Hyprland Plugin Manager

### PR DESCRIPTION
**Pull request by vaxerski**
Adds a new plugin manager, deprecating hyprload. Better integrated, never breaking. Hopefully.

TODO:
 - [x] Wiki MR: https://github.com/hyprwm/hyprland-wiki/pull/410
 - [x] `--notify` for using `hyprctl notify` for important events
 - [x] help page

cc @fufexan 

cc plugin people @outfoxxed @Duckonaut @zakk4223 @horriblename

### CODE REVIEW

**Comment by Eclextic** [comment]
Are plugin loaders going to become first-party?

**Comment by vaxerski** [comment]
> Are plugin loaders going to become first-party?

....plugin loaders?

**Comment by Eclextic** [comment]
Manager lol...

**Comment by Duckonaut** [comment]
Looks good at a rough glance, having it integrated is gonna be a way way easier way for people to keep stuff in sync. Also gets the maintenance burden, which I've admittedly not been great at, away from me lol (though if you ever want some help on this I can contribute)

**Comment by vaxerski** [comment]
since no further comments arose I will merge this yay

**Comment by zakk4223** [comment]
My one comment here is I hate you because now I'm going to have to actually make proper releases instead of just chasing -git and not giving a shit about other people.

**Comment by vaxerski** [comment]
I mean, you still can. hyprpm is going to fetch latest git if no pins are defined in the manifest

**Pull request merged**
