### PR TITLE
fix focuswindow for fullscreen

### PR DESCRIPTION
**Pull request by shezdy**
#### Describe your PR, what does it fix/add?
Fixes the same thing as #4402. focuswindow will make the specified window fullscreen, similar to cyclenext.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
nope

#### Is it ready for merging, or does it need work?
ready

### CODE REVIEW

**Comment by vaxerski** [comment]
does it supersede #4402?

**Comment by vaxerski** [comment]
also request review when code style passes pls

**Comment by shezdy** [comment]
yes it supersedes #4402

**Comment by shezdy** [comment]
ci is passing now

**Review by vaxerski — APPROVED** [review]
ok

**Pull request merged**
