### PR TITLE
Fix Jetbrains IDE dialogs

### PR DESCRIPTION
**Pull request by PatrickTaibel**
#### Describe your PR, what does it fix/add?
Fixes the following Jetbrains IDE dialog issues:
- Wrong position / size of dialogs due to not correctly scaled `WM_SIZE_HINTS` with hidpi patch
- Floating detection ignores that size hints can be unset which is not the same as both min and max sizes being equal
- "Find in Files" dialog jumping around weirdly due to being forced to position 0/0 initially sometimes

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
- This is the first time I'm touching a window manager and looking into X11
- I only use the Jetbrains IDEs via XWayland so I can't assure that I didn't break any other X11 apps functionality
- I'm not too sure about using `goalv` in `CHyprXWaylandManager::setWindowSize`  for the position. Without it the "Find in Files" dialog gets forced to position 0/0 sometimes which it really dislikes (and also does not make sense). As far as I can see most of the calls also use the goal vector for the size, so I guess that should be fine.

#### Is it ready for merging, or does it need work?
Ready for merging

### CODE REVIEW

**Comment by vaxerski** [comment]
the wlroots hidpi patches are being staged for removal, so I am against any changes to them. If the other changes help in cases without them (either unscaled or xwayland:force_zero_scaling) then I am okay with the mr as long as the patch changes are removed

**Comment by PatrickTaibel** [comment]
Ah, I missed the new `xwayland:force_zero_scaling` option.
I've now tried it out. Problem is the issue with the dialogs is still there / made worse. First, I hoped this was again due to the size hints being scaled wrong in the geometry fetch. But, as far as I can see, the `void IHyprLayout::onWindowCreatedFloating(CWindow* pWindow) {` mixes scaled and unscaled properties (e.g. `desiredGeometry` being from XWayland scale and `PMONITOR->vecPosition` from wlroots). So that's not so easy to fix without a lot of conditions.
Wouldn't it be better to have some central place / functions for this instead of handling this on each occurence of a probably not correctly scaled XWayland property all over the code base?

**Comment by vaxerski** [comment]
it probably would be better.

**Comment by PatrickTaibel** [comment]
Fixed quite a few issues with the `xwayland:force_zero_scaling` option. Looks quite promising. I need to clean it up and then I will update this PR. This should fix most of the open issues with the new option as far as I can tell.

**Comment by BrannonKing** [comment]
Does this fix https://github.com/hyprwm/Hyprland/issues/2849 ?

**Comment by PatrickTaibel** [comment]
@BrannonKing Yes, it shoud fix this and basically all dialog size/position issues that happen in the Jetbrains IDEs with active scaling and multiple monitors / offset values. 
The current status of the PR patches the wlroots patch for this and has a few minor adjustments on top. This will never be merged, as the wlroots patch has been phased out. 
I started working on getting the `xwayland:force_zero_scaling` option working which is in https://github.com/PatrickTaibel/Hyprland/tree/fix_force_zero_scaling. That works too (but will break if you have different scale values set and is code wise pretty hacky). Problem here is that it won't be merged liked this either as @vaxerski changed quite a bit there the last two days.

**Comment by wowblvck** [comment]
Does this fix the problem #2880 ?

**Comment by h0tc0d3** [comment]
I got wlroots patches from [wlroots-hidpi](https://aur.archlinux.org/packages/wlroots-hidpi-xprop-git) because the nix patch didn't work https://github.com/hyprwm/Hyprland/issues/3055

I also applied the patch from this PR, it didn't apply completely, I looked at the code, edited it, and I got this patch.

Wayland apps run in the center and have the right size. Tested on: wine battle.net client, jetbrains ide, kicad. Dialogs and floating windows display correctly in the center.

```
diff --git a/src/managers/XWaylandManager.cpp b/src/managers/XWaylandManager.cpp
index 76f979da4b43..c1ce2287a955 100644
--- a/src/managers/XWaylandManager.cpp
+++ b/src/managers/XWaylandManager.cpp
@@ -151,7 +151,7 @@ void CHyprXWaylandManager::setWindowSize(CWindow* pWindow, Vector2D size, bool f
 
     // calculate pos
     // TODO: this should be decoupled from setWindowSize IMO
-    Vector2D windowPos = pWindow->m_vRealPosition.vec();
+    Vector2D windowPos = pWindow->m_vRealPosition.goalv();
 
     if (pWindow->m_bIsX11) {
         windowPos = windowPos - PMONITOR->vecPosition; // normalize to monitor
@@ -235,7 +235,9 @@ bool CHyprXWaylandManager::shouldBeFloated(CWindow* pWindow) {
             return true; // override_redirect
 
         const auto SIZEHINTS = pWindow->m_uSurface.xwayland->size_hints;
-        if (SIZEHINTS && (pWindow->m_uSurface.xwayland->parent || ((SIZEHINTS->min_width == SIZEHINTS->max_width) && (SIZEHINTS->min_height == SIZEHINTS->max_height))))
+        if (SIZEHINTS &&
+            (pWindow->m_uSurface.xwayland->parent ||
+             (SIZEHINTS->min_width > 0 && SIZEHINTS->min_height > 0 && SIZEHINTS->min_width == SIZEHINTS->max_width && SIZEHINTS->min_height == SIZEHINTS->max_height)))
             return true;
     } else {
         const auto PSTATE = &pWindow->m_uSurface.xdg->toplevel->current;
```

**Comment by PatrickTaibel** [comment]
Closing this as I won't continue here. There are bugs in the JBR (Jetbrains fork of the openJDK) which cause quite some issues (mostly with dialogs) opened on different screens.

**Pull request closed without merging**
