### PR TITLE
remove m_vReportedSize set for xwayland

### PR DESCRIPTION
**Pull request by phonetic112**
#### Describe your PR, what does it fix/add?
Fixes https://github.com/hyprwm/Hyprland/issues/2661#issuecomment-1872569582

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
nope

#### Is it ready for merging, or does it need work?
ready

### CODE REVIEW

**Review by vaxerski — COMMENTED** [review]
but... unmanagedSetGeometry is a client request? Why would we wait for a pong?

**Comment by phonetic112** [comment]
Steam pop-ups open themselves at size 0,0 for some reason before they request `unmanagedSetGeometry`, so setting `m_vReportedSize` like that would cause the surface to prematurely render at size 0,0 if the timing is off.

so setting `m_vPendingReportedSize` directly lets us actually wait for the pong before rendering the surface.

**Comment by vaxerski** [comment]
okay but that's _before_ and we apply `.goalv()` which should have the value requested in the event struct?

**Comment by phonetic112** [comment]
yes, with the `minsize 1 1` window rule it requests size (5, 5) first, and then the correct size afterwards (something like (100, 150))

**Comment by vaxerski** [comment]
why would this fix it then?

**Comment by phonetic112** [comment]
The surface would have no size until the pong is received

**Review by vaxerski — APPROVED** [review]
I guess if it fixes the issue, we can try that. Though I have bad feelings about this.

**Pull request merged**
