### PR TITLE
layer: don't close special ws when restoring focus

### PR DESCRIPTION
**Pull request by MightyPlaza**
same as #5308 but works for special workspaces
seems to work fine

### CODE REVIEW

**Review by vaxerski — APPROVED** [review]
tanks!

**Comment by vaxerski** [comment]
konflikt

**Comment by MightyPlaza** [comment]
can't really build main after new dependency was added yet to test, but should be fine since I just rebased and changed the function in use.

**Review by vaxerski — APPROVED** [review]
tanks!

**Pull request merged**
