### PR TITLE
Only call fclose() when we have a non-empty filepath.

### PR DESCRIPTION
**Pull request by MichaelPachec0**
#### Describe your PR, what does it fix/add?
Fix #2905 's logic error.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
Style check, tried to follow the same style that was already set in code.
#### Is it ready for merging, or does it need work?
Ready for merging.

### CODE REVIEW

**Comment by MichaelPachec0** [comment]
waiting on @maaarghk to verify if this fixes the problem.

**Comment by primalmotion** [comment]
I confirm this fixes the crash. Thanks!

**Comment by Frontear** [comment]
Yep this is fixing my crash too, rebuilt Hyprland about 30 minutes ago and viola, keymap loop -> crash.

**Comment by maaarghk** [comment]
works for me, both keyboards work, both keyboards have configured keymap.

**Review by vaxerski — APPROVED** [review]
idiots. I will merge it despite the violation of the styling just for the sake of this being fixed

**Pull request merged**
