### PR TITLE
allow specifying max size in size window rule

### PR DESCRIPTION
**Pull request by MightyPlaza**
allows specifying window max size in `size` window rule
(ex: `size <80% 900`) as a replacement for behaviour changed in https://github.com/hyprwm/Hyprland/pull/4775
seems to work fine

### CODE REVIEW

**Comment by vaxerski** [comment]
maybe add > for min as well in one MR and clean up the code?

**Comment by MightyPlaza** [comment]
done

**Review by vaxerski — APPROVED** [review]
nice nice, wiki mr needed

**Comment by MightyPlaza** [comment]
https://github.com/hyprwm/hyprland-wiki/pull/811

**Pull request merged**
