### PR TITLE
Fallback to xcursor if failed to render hyprcursor

### PR DESCRIPTION
**Pull request by SoSeDiK**
#### Describe your PR, what does it fix/add?
Fallback to xcursor as last resort. Should bandaid invisible cursors on broken themes.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
\-

#### Is it ready for merging, or does it need work?
Ready

### CODE REVIEW

**Review by vaxerski — COMMENTED** [review]
is this a good idea though? An Xcursor theme might not be in use at all - which would result in a random ugly cursor, instead of the old one staying...?

**Comment by SoSeDiK** [comment]
This is an edge case when no cursor could be found at all, so the expectation is that either the fancy cursor didn't load in the first place and mouse will be invisible without this, or something went so horribly wrong that fancy cursor is not a priority.

The proper fix is to change/repair a broken theme, but this should help those who had invisible cursor in e.g. kitty and had to hover Waybar for cursor to reappear.

**Comment by SoSeDiK** [comment]
https://github.com/hyprwm/hyprcursor/pull/31 should fix invisible cursors too during initialization. I still think *this* is a good caution in case it ever breaks during runtime.

**Comment by vaxerski** [comment]
I guess it's okay since if you dont have a left_ptr your theme is cringe

**Review by vaxerski — APPROVED** [review]

**Pull request merged**
