### PR TITLE
fix bug in previous doLater cleanup

### LINKED ISSUE #8628: Crash on an attempt to close  mpv fullscreen window
### Already reported ? *

- [X] I have searched the existing open and closed issues.

### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland 0.45.0 built from branch main at commit 6d7544458d0fafcae410c1978a0cabce2fb4a346  (cleanup: use doLater instead of adding idle event handlers (8624)).
Date: Sun Dec 1 22:14:35 2024
Tag: v0.45.0-74-g6d754445, commits: 5507
built against aquamarine 0.5.0


flags set:
debug


System Information:
System name: Linux
Node name: archbtw
Release: 6.12.1-zen1-1-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Fri, 22 Nov 2024 16:04:23 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-H GT2 [UHD Graphics] [8086:9bc4] (rev 05) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation TU116M [GeForce GTX 1660 Ti Mobile] [10de:2191] (rev a1) (prog-if 00 [VGA controller])
NVRM version: NVIDIA UNIX x86_64 Kernel Module  565.57.01  Thu Oct 10 12:29:05 UTC 2024


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:
```

</details>

### Description

Hyprland crashes during an attempt to close fullscreened mpv window.

### How to reproduce

Open a videofile with mpv, fullscreen it with an mpv keybind (f), try to close it (q)

### Crash reports, logs, images, videos

[hyprlandCrashReport1347.txt](https://github.com/user-attachments/files/17978257/hyprlandCrashReport1347.txt)
[hyprlandCrashReport18776.txt](https://github.com/user-attachments/files/17978258/hyprlandCrashReport18776.txt)

### PR DESCRIPTION
**Pull request by ikalco**
#### Describe your PR, what does it fix/add?
fixes #8628 also #8633

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
oops
edit: now that I think about it how did this not crash before...

#### Is it ready for merging, or does it need work?
yes ready

### CODE REVIEW

**Comment by vaxerski** [comment]
I reverted your shiz already man

**Comment by vaxerski** [comment]
What we need is a way to cancel doLater stuff. Maybe a SP as with other shit

**Comment by vaxerski** [comment]
altho tbh this is quite a fun solution

**Comment by ikalco** [comment]
> altho tbh this is quite a fun solution
yeah but hacky

maybe ill come up with some way to cancel we'll see

**Comment by vaxerski** [comment]
could return a SP that is cancellable by a fn call

**Pull request closed without merging**
