### PR TITLE
Simplify matrix calculations

### PR DESCRIPTION
**Pull request by Dickby**
#### Describe your PR, what does it fix/add?
Removes unnecessary matrix calculations. 

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
No

#### Is it ready for merging, or does it need work?
I think it's ready!

### CODE REVIEW

**Comment by vaxerski** [comment]
what the fuck

I know absolutely jack shit nothing about matrices here but that was how wlroots' renderer used to do it.

Are you mega sure this is correct? Have you also tested transformed displays?

**Comment by Dickby** [comment]
It's not changing anything really, just taking away the two minuses in matrixProjection infront of t[3] and t[4] ,which are the values that effect the y value of the vectors multiplicated with that matrix. look at the transforms[], 
in every transform the value pairs for 3,4 and 0,1 are :
one is zero and the other one is 1 or -1;
that basicly switches x and y for the resulting vector and multiplicates -1 for some of those transforms.
If you thing about e.g. switching x and y of a vector and multiplying x with -1 would be a rotation of 90 degrees counter clockwise. this is how rotations are done here(it's basicly the mechanism of imaginary numbers).
by multiplying t[3] and t[4] with -1 like you did, all it does is it changes the sign of the resulting y coordinate of the vectors.
With that you would end up with a image that is flipped180, to deal with that you had to multiply that matrix with your flipped180 matrix (which if you look at it does nothing but flipping the sign of the y value of the resulting vector.
I took away those sign flips in your matrixProjection, so the flipped180 is not needed anymore.

The second thing i did was just taking away the wlr_matrix_transpose(matrix,matrix) which "mirrors the matrix across the diagonal, that is because the matrices in the code are ordered the other way around as inside opengl's mechanism.
This is so common, that opengl's glUniformMatrix functions have an boolean value that controls if opengl should to that to the matrix itself (in this case it's basicly for free because it just effects how opengl copies those values).
I tested it with scaling and all 8 available transpositions.

**Comment by Dickby** [comment]
If your unsure, 
@fufexan would you be so kind and try to break this!

**Comment by fufexan** [comment]
I've been running it for half an hour, been playing games. No issues found.

**Comment by Dickby** [comment]
@fufexan thanks.

**Pull request merged**
