### PR TITLE
fix: use proper path for the XWayland sockets, fixes #7849

### LINKED ISSUE #7849: Steam nor discord starts on latest git
### Discussed in https://github.com/hyprwm/Hyprland/discussions/7845

<div type='discussions-op-text'>

<sup>Originally posted by **DockterTeagle** September 18, 2024</sup>
Howdy,
I am writing this as a discussion as I am also unable to access discord atm due to a similar issue I believe. It seems that xwayland is somehow not being loaded or something, I am sure that I have it enabled in my nix config. The error I get when I try to start steam is this:
2024-09-18T21:08:36,033994827-05:00

Also when I run discord from the command line I get this error
```
[WebContents] double crashed (reason: crashed, exitCode: 139)... RIP =(
notificationScreen.webContentsSend: win is invalid undefined.
```
i have made sure that mako is running so Idk what the issue could be for the time being I am going to revert to my previous generation, and try again this switch again in a few days to see if it has been fixed.
</div>

### PR DESCRIPTION
**Pull request by Arisa-Snowbell**
Fixes #7849

### CODE REVIEW

**Comment by Daholli** [comment]
yeah this works, tested it on my end aswell, thanks for the quick fix

**Review by vaxerski — APPROVED** [review]
woopsie

**Comment by littleblack111** [comment]
uhh... idk if this is related. but i just updated... and all xwayland apps doesnt turn on anymore... pls fix asap @vaxerski

**Comment by khaneliman** [comment]
> uhh... idk if this is related. but i just updated... and all xwayland apps doesnt turn on anymore and keep saying stuff like cant connect to X server or cant get display :0 ... pls fix asap @vaxerski
> 
> currently using hyprland-git
> 
> EDIT: now i swapped to normal extra/hyprland package from arch. and its all fine... ill be staying there for now... im gonna live a stable life :D

This was the PR to fix it

**Comment by littleblack111** [comment]
ohh i see. ill see what will happen after the release to aur..

**Pull request merged**
