### PR TITLE
fix cursor gsettings on session change

### PR DESCRIPTION
**Pull request by ikalco**
#### Describe your PR, what does it fix/add?
when changing session gsettings cursor-theme can be changed
this resets it to what we want when switching back

#### Is it ready for merging, or does it need work?
yes

### CODE REVIEW

**Comment by gulafaran** [comment]
instead of moving it all to CCursorManager when its a kinda xcursor only feature, why not just make the syncGsettings public in XCursoManager, and the function in CCursorManager does m_pXCursor->syncGsettings(..)

**Comment by ikalco** [comment]
yeah didn't look into it too far and thought it wasnt related to xcursor

**Comment by vaxerski** [comment]
wait is this ready

**Review by vaxerski — APPROVED** [review]
lgtm  bae

**Pull request merged**
