### PR TITLE
Don't render tiled windows below fullscreen windows

### PR DESCRIPTION
**Pull request by Roger-Roger-debug**
#### Describe your PR, what does it fix/add?
Stops tiled windows from being rendered on a fullscreen workspace.

#### Is it ready for merging, or does it need work?
Ready to merge

### CODE REVIEW

**Comment by vaxerski** [comment]
tiled windows are not rendered behind fullscreen ones, wdym?

**Comment by Roger-Roger-debug** [comment]
I meant maximized windows like this
image

**Comment by vaxerski** [comment]
does not happen to me and your PR will introduce a hellololalot of issues. Can you maybe rather tell me how 2 reproduce?

**Comment by Roger-Roger-debug** [comment]
Setting a window to fullscreen 1 will still render other windows on that workspace. If the maximized window is transparent you can see windows behind it.

**Comment by vaxerski** [comment]
image

Well I for sure can't

**Comment by vaxerski** [comment]
oh wait edit nvm if u disable new optim it happens yes sec

**Comment by Roger-Roger-debug** [comment]
If this doesn't solve the underlying issue I'll close it.

**Pull request closed without merging**
