### PR TITLE
Internal: Hyprland box implementation

### PR DESCRIPTION
**Pull request by vaxerski**
Cleans up some stuff, implements Hyprland boxes.

Fixes: #2402 #3511

Chonker

### CODE REVIEW

**Comment by RoootTheFox** [comment]
image
Hyprland doesn't seem to respect waybar's `exclusive` setting (windows do go behind waybar which they didn't do previously)

**Comment by vaxerski** [comment]
oops, fixed

**Comment by RoootTheFox** [comment]
another thing i noticed: it seems to render new shadows behind windows now, not sure if this is related to this MR or if that's because i just haven't updated Hyprland before in a while

before:
image
after: 
image

wanted to mention this anyway

the MR looks perfectly fine otherwise though, those are the only things i noticed

**Comment by vaxerski** [comment]
wdym, they have always been behind.

Only thing that changed is that today morning a patch was merged that draws shadows around decorations, so it doesn't render them under borders now.

**Comment by TheK0tYaRa** [comment]
image
There seems to be a scaling issue in kotatogram fullscreen view with this one.

**Comment by Vagahbond** [comment]
Weiiiiird things happening when I open a foot terminal (not with other apps that I tried). 

It opens tiny 

then when I move it it's resized to expected size.
Got:
1699115018_grim

Expected:
1699115028_grim

**Comment by vaxerski** [comment]
aren't those also present on -git? #3754

**Comment by Vagahbond** [comment]
Yes, also present on this: 
```
❯ hyprctl version 
Hyprland, built from branch  at commit 73e78f05ad5cafa20ac5bf177c94ac9ecca37097  ().
Tag: 

flags: (if any)
debug
```

**Comment by vaxerski** [comment]
so it's unrelated to this mr

**Comment by matt1432** [comment]
This branch does fix #3754

It doesn't let me build Hyprgrass though, gives me errors like this `error: 'bottomRight' was not declared in this scope`

**Comment by matt1432** [comment]
Also my cursor stays when I use my touchscreen

**Comment by vaxerski** [comment]
I'll merge this because all of yalls issues are unrelated

**Pull request merged**
