### PR TITLE
Modified the  `movefocus` dispatcher to prioritize focus change within groups. 

### PR DESCRIPTION
**Pull request by normaltaro**
#### Describe your PR, what does it fix/add?
It modifies the `movefocus` dispatcher logic to switch directional focus within groups first:
- Check if the current window is part of a Group.
- `movefocus l/r`  can now be used to switch tabs within the Group
- If the current window is the first/last tab of its group OR `movefocus u/d` is pressed, then the usual directional focus logic applies.

In other words, a sideways directional focus change is prioritized within groups first.

##### How I think it benefits users?
  + I think most users (like me) expect the directional flow of `movefocus` dispatcher to be followed within groups as it does in other window managers. I felt locked out of tabbed groups and never really used them because of this.
  + It is not possible to do so using `changegroupactive` along with `movefocus` as they require separate keybinds which do not conflict.
  + This keeps the last active index intact when focus is moved out of the group.
  + Personally, I think the overall experience with this patch is much better compared to other window managers regarding tabbed groups (like `i3`)
+ Example:
  + `mod h/j/k/l` with `movefocus l/r/u/d` is intuitive for groups too.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
I haven't found any bugs. It works as per the logic described above.

#### Is it ready for merging, or does it need work?
I have tried with all kinds of group orientations and it works good. It is a single block of 13 lines and could be merged as-is. :)

### CODE REVIEW

**Comment by vaxerski** [comment]
`hyprctl dispatch changegroupactive f | grep "next" && hyprctl dispatch movefocus r`?

**Comment by vaxerski** [comment]
should be an option, some people might not like this

**Comment by normaltaro** [comment]
how about another dispatcher, like `movefocusingroups`?

**Comment by vaxerski** [comment]
I was thinking about simply a bool flag in binds:

**Comment by normaltaro** [comment]
added bool option variable `movefocus_cycles_groupfirst` to `binds`.

**Review by vaxerski — APPROVED** [review]
thanks! just a wiki mr needed

**Comment by izmyname** [comment]
Just wanna say thanks. The only feature I missed when I switched from i3 to Hyprland.

**Comment by izmyname** [comment]
Also, some thoughts. Would it be possible to add something like tab focus cycling if a group window is the only window on a workspace? For example:  right now, if a windowgroup has 3 tabs, using 'movefocus, r' goes like 1>2>3 instead of 1>2>3>1>2>3.

**Comment by normaltaro** [comment]
> Also, some thoughts. Would it be possible to add something like tab focus cycling if a group window is the only window on a workspace? For example: right now, if a windowgroup has 3 tabs, using 'movefocus, r' goes like 1>2>3 instead of 1>2>3>1>2>3.

damn, i didn't think of that. its probably a small change in the `if` condition too. i'll try for another pr to fix/add it.

**Pull request merged**
