### PR TITLE
Implement pass binds

### PR DESCRIPTION
**Pull request by outfoxxed**
#### Describe your PR, what does it fix/add?
Pass binds run the associated dispatcher but do not prevent windows from receiving the bind. My specific use case is running a dispatcher on left click without consuming the click.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
No

#### Is it ready for merging, or does it need work?
Ready to merge

### CODE REVIEW

**Comment by outfoxxed** [comment]
Release bind issue was fixed

**Comment by vaxerski** [comment]
pass is a bad name because it would be confused with the pass dispatcher

non-consuming would be a better term imo

also wiki mr

**Comment by outfoxxed** [comment]
would `n` be a good modifier then? e.g. `bindn`

**Comment by vaxerski** [comment]
yea

**Comment by outfoxxed** [comment]
Wiki mr: hyprwm/hyprland-wiki#249

**Review by vaxerski — APPROVED** [review]
slaaay gurlll 💅

**Pull request merged**
