### PR TITLE
Buffer lock/release fixes

### LINKED ISSUE #7091: Kitty has green artifacts
### Regression?

Yes

### System Info and Version

<details> <summary>System/Version info</summary>

```sh
Hyprland, built from branch  at commit bc86afea7e177a7ad4335737417fc0e468698dc4  ().
Date: 2024-07-27
Tag: , commits: bc86afea7e177a7ad4335737417fc0e468698dc4

flags: (if any)


System Information:
System name: Linux
Node name: nixos
Release: 6.10.1
Version: #1-NixOS SMP PREEMPT_DYNAMIC Wed Jul 24 13:54:07 UTC 2024


GPU information: 
09:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] [1002:73bf] (rev c3) (prog-if 00 [VGA controller])


os-release: ANSI_COLOR="1;34"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="24.11.20240727.b73c222"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
IMAGE_ID=""
IMAGE_VERSION=""
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 24.11 (Vicuna)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="24.11 (Vicuna)"
VERSION_CODENAME=vicuna
VERSION_ID="24.11"


plugins:
  hyprsplit by shezdy ver 1.0
  dynamic-cursors by Virt ver 0.1

======Config-Start======


Config File: /home/noah/.config/hypr/hyprland.conf: Read Succeeded
exec-once = /nix/store/wbqwrp6gpf31acmdchik5lsj8zdw2z24-dbus-1.14.10/bin/dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target
plugin=/nix/store/8fb4mp0n0jd5a5sjc4m06ywdjv0a810f-hyprsplit-0.1/lib/libhyprsplit.so
plugin=/nix/store/hb97gjpw5lxzhkaxwxw3ld60563bi2li-hypr-dynamic-cursors/lib/libhypr-dynamic-cursors.so
$mod=SUPER
cursor {
  inactive_timeout=5
}

debug {
}

decoration {
  blur {
    brightness=0.700000
    enabled=true
  }
  blurls=bar-0
  blurls=bar-1
  blurls=rofi
  blurls=notifications0
  blurls=notifications1
  blurls=mpris
  col.shadow=rgba(1a1a1aaf)
  drop_shadow=true
  rounding=12
  shadow_offset=0, 40
  shadow_range=300
  shadow_render_power=4
  shadow_scale=0.900000
}

device {
  name=wacom-intuos-s-pen
}

dwindle {
  preserve_split=true
}

general {
  border_size=2
  col.active_border=rgba(f38ba8ff)
  col.inactive_border=rgba(1e1e2eff)
  gaps_in=5
  gaps_out=10
}

input {
  accel_profile=flat
  follow_mouse=1
  mouse_refocus=false
}

misc {
  disable_hyprland_logo=true
}
animation=layers, 1, 5, default, slide
bind=, XF86AudioPlay, exec, playerctl play-pause
bind=, XF86AudioNext, exec, playerctl next
bind=, XF86AudioPrev, exec, playerctl previous
bind=$mod, f11, exec, brightness-ctrl down
bind=$mod, f12, exec, brightness-ctrl up
bind=$mod SHIFT, f12, exec, brightness-ctrl full
bind=CTRL, Print, exec, satty-shot
bind=, Print, exec, hyprshot -m output -o ~/Pictures/Screenshots
bind=$mod, p, exec, wl-copy $(hyprpicker)
bind=$mod, h, movefocus, l
bind=$mod, l, movefocus, r
bind=$mod, k, movefocus, u
bind=$mod, j, movefocus, d
bind=$mod SHIFT, h, movewindow, l
bind=$mod SHIFT, l, movewindow, r
bind=$mod SHIFT, k, movewindow, u
bind=$mod SHIFT, j, movewindow, d
bind=$mod, slash, togglesplit
bind=$mod, mouse_down, split:workspace, e-1
bind=$mod, mouse_up, split:workspace, e+1
bind=alt, tab, exec, rofi -show window
bind=$mod, t, togglefloating
bind=$mod, c, killactive
bind=$mod, q, exec, shutdown-menu
bind=$mod, B, exec, firefox
bind=$mod, y, exec, kitty -e yazi
bind=alt, f4, exec, hyprctl kill
bind=$mod, Return, exec, kitty
bind=$mod, Space, exec, rofi -show drun
bind=$mod, E, exec, rofimoji
bind=$mod, a, exec, kitty -e ollama run mixtral
bind=$mod SHIFT, escape, exec, hyprlock
bind=$mod SHIFT, a, exec, llm-actions
bind=$mod, 1, split:workspace, 1
bind=$mod SHIFT, 1, split:movetoworkspace, 1
bind=$mod, 2, split:workspace, 2
bind=$mod SHIFT, 2, split:movetoworkspace, 2
bind=$mod, 3, split:workspace, 3
bind=$mod SHIFT, 3, split:movetoworkspace, 3
bind=$mod, 4, split:workspace, 4
bind=$mod SHIFT, 4, split:movetoworkspace, 4
bind=$mod, 5, split:workspace, 5
bind=$mod SHIFT, 5, split:movetoworkspace, 5
bind=$mod, 6, split:workspace, 6
bind=$mod SHIFT, 6, split:movetoworkspace, 6
bind=$mod, 7, split:workspace, 7
bind=$mod SHIFT, 7, split:movetoworkspace, 7
bind=$mod, 8, split:workspace, 8
bind=$mod SHIFT, 8, split:movetoworkspace, 8
bind=$mod, 9, split:workspace, 9
bind=$mod SHIFT, 9, split:movetoworkspace, 9
bind=$mod, 0, split:workspace, 10
bind=$mod SHIFT, 0, split:movetoworkspace, 10
binde=, XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 1%+
binde=, XF86AudioLowerVolume, exec, wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 1%-
binde=$mod CTRL, l, resizeactive, 10 0
binde=$mod CTRL, h, resizeactive, -10 0
binde=$mod CTRL, k, resizeactive, 0 -10
binde=$mod CTRL, j, resizeactive, 0 10
bindm=$mod, mouse:272, movewindow
bindm=$mod, mouse:273, resizewindow
exec-once=ags
exec-once=fcitx5
exec-once=wpaperd
exec-once=mpv --no-video --volume=150 /nix/store/ag6v7p7x8ksxirkyqjl9xfsmhzr45w31-start.wav
exec-once=/nix/store/d240ghczdgwgnnbcbarr2fr6a7svs1sw-lxqt-policykit-2.0.0/bin/lxqt-policykit-agent
layerrule=ignorealpha, bar-0
layerrule=ignorealpha, bar-1
layerrule=ignorealpha, notifications0
layerrule=ignorealpha, notifications1
layerrule=ignorealpha, mpris
layerrule=ignorealpha, rofi
layerrule=noanim,selection
monitor=DP-2, 1920x1200, 1920x0, 1
monitor=DP-1, 1920x1080@165, 0x0, 1, vrr, 1 
windowrulev2=noanim, class:^(com.gabm.satty)$
windowrulev2=size 640 360, title:(Picture-in-Picture)
windowrulev2=pin, title:^(Picture-in-Picture)$
windowrulev2=move 1906 14, title:(Picture-in-Picture)
windowrulev2=float, title:^(Picture-in-Picture)$
windowrulev2=float, title:^(Authentication Required)$

======Config-End========
```

</details>

### Description

Kitty has green artifacts when resized or etc. Used to be a bug when Aquamarine was still being merged, but seems to have appeared again somehow

### How to reproduce

1. resize it rapidly or anything in that nature
2. Observe

### Crash reports, logs, images, videos

https://github.com/user-attachments/assets/8e311027-252e-4e14-9cc0-c86a5156df20

### PR DESCRIPTION
**Pull request by vaxerski**
Fixes a few edge cases with buffer locking and releasing. Needs testing.

Fixes #7091

Possibly impacted:
 - direct scanout
 - cursors

Untested:
 - xwayland

### CODE REVIEW

**Comment by vaxerski** [comment]
also @UjinT34 looking at the nvidia dumb copy this might break this, but I am unsure. Care to test?

**Comment by vaxerski** [comment]
I need some testing, rocking this rn and all seems well

**Comment by Agent00Ming** [comment]
Cursor dumb copy crashes to tty when I hover over a client side cursor window. Trying to get the backtrace only gives

```
#0  0x00005d287978b64e in Hyprutils::Memory::CWeakPointer<IHLBuffer>::lock (this=0x0) at /usr/include/hyprutils/memory/WeakPtr.hpp:122
#1  0x00005d2879822932 in CPointerManager::renderHWCursorBuffer (this=0x5d28b4d2aa80, state=..., texture=...) at /home/ming/documents/git/hyprland/src/managers/PointerManager.cpp:433
        PDUMB = {p_ = 0x5d28b4d9fb00}
```

Direct scanout works (intel). Xwayland works.

**Comment by diniamo** [comment]
Guess I'll put it here too:
- Black borders appeared on the edge of my monitor
- XCursor shapes are wrong again

**Comment by vaxerski** [comment]
dumb copy is a bit complicated here, I'll see what I can do... the way it's been working right now was technically wrong

**Comment by vaxerski** [comment]
@Agent00Ming pls test dumb

**Comment by Agent00Ming** [comment]
crashes on start [bt.txt](https://github.com/user-attachments/files/16431253/bt.txt)

**Comment by vaxerski** [comment]
can you compile hyprutils with asan and get a trace?

**Comment by Agent00Ming** [comment]
dunno if I did it right [asan.txt](https://github.com/user-attachments/files/16431938/asan.txt)

**Comment by vaxerski** [comment]
now?

**Comment by Agent00Ming** [comment]
no, it still crashes on start

**Comment by vaxerski** [comment]
why does it not on my end :/ trace still the same?

**Comment by Agent00Ming** [comment]
slightly different [asan-1.txt](https://github.com/user-attachments/files/16432535/asan-1.txt)

**Comment by vaxerski** [comment]
try now

**Comment by vaxerski** [comment]
woo cursed fixed

**Comment by vaxerski** [comment]
try no

**Comment by Agent00Ming** [comment]
hmm, cursor is invisible in blender but appears normally elsewhere.
[hyprlandd.log](https://github.com/user-attachments/files/16433407/hyprlandd.log)

**Comment by vaxerski** [comment]
try n

**Comment by Agent00Ming** [comment]
crash on client side cursor [bt.txt](https://github.com/user-attachments/files/16433485/bt.txt)

**Comment by vaxerski** [comment]
yeeeaaa this is a problem ugh

**Comment by vaxerski** [comment]
architecture kinda sucks in this scenario

**Comment by Agent00Ming** [comment]
it works now but direct scanout is left and entered for every frame in minecraft (xwayland) and it causes the same for the very first frame that the cursor hovers over vkcube-wayland in direct scanout

**Comment by vaxerski** [comment]
can you bisect that one to make sure it's not something that should be fixed here

**Comment by Agent00Ming** [comment]
first bad commit: [682865632fe986d179ca07e45ae89e65b8058b33] xwayland: fix high cpu idle usage
[bisect_xwl_ds.log](https://github.com/user-attachments/files/16434171/bisect_xwl_ds.log)

**Comment by vaxerski** [comment]
ok its unrelated to this then, will merge tomorrow. Thanks, you can open another issue I guess

**Comment by Beyley** [comment]
Can confirm this PR fixes #7103 for me. However it seems to introduce a crash when closing Minecraft (only when running under gamescope) which did not happen before. This could be an unrelated crash caused by external changes though.
[hyprlandCrashReport127343.txt](https://github.com/user-attachments/files/16434920/hyprlandCrashReport127343.txt)

**Comment by vaxerski** [comment]
get a debug stacktrace please

**Comment by vaxerski** [comment]
I'll wait a few hours more, otherwise I am merging and that crash can be opened as an issue, if anyone can repro

**Comment by gulafaran** [comment]
> I'll wait a few hours more, otherwise I am merging and that crash can be opened as an issue, if anyone can repro

compiling atm, il fire up my trusty bg3, and various xwl things see if i can reproduce. heh

> I'll wait a few hours more, otherwise I am merging and that crash can be opened as an issue, if anyone can repro


> I'll wait a few hours more, otherwise I am merging and that crash can be opened as an issue, if anyone can repro

gamescope -f vkcube

```
#0  0x00007ffff70a159c in pthread_kill () at /usr/lib64/libc.so.6
#1  0x00007ffff704449a in raise () at /usr/lib64/libc.so.6
#2  0x00007ffff70284ed in abort () at /usr/lib64/libc.so.6
#3  0x0000555555691f73 in handleUnrecoverableSignal (sig=11) at ../hyprland-9999/src/Compositor.cpp:72
#4  0x00007ffff7044530 in <signal handler called> () at /usr/lib64/libc.so.6
#5  std::vector<Hyprutils::Memory::CWeakPointer<CWLSubsurfaceResource>, std::allocator<Hyprutils::Memory::CWeakPointer<CWLSubsurfaceResource> > >::size (this=0x348) at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/vector:113
#6  std::erase_if<Hyprutils::Memory::CWeakPointer<CWLSubsurfaceResource>, std::allocator<Hyprutils::Memory::CWeakPointer<CWLSubsurfaceResource> >, CWLSurfaceResource::bfHelper(std::vector<Hyprutils::Memory::CSharedPointer<CWLSurfaceResource> >, std::function<void(Hyprutils::Memory::CSharedPointer<CWLSurfaceResource>, const Hyprutils::Math::Vector2D&, void*)>, void*)::<lambda(const auto:56&)> > (__cont=<error reading variable: Cannot access memory at address 0x350>, __pred=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/vector:117
#7  CWLSurfaceResource::bfHelper (this=this@entry=0x555556c47120, nodes=std::vector of length 6, capacity 6 = {...}, fn=..., data=data@entry=0x7fffffffcdf0) at ../hyprland-9999/src/protocols/core/Compositor.cpp:261
#8  0x00005555558ec5aa in CWLSurfaceResource::bfHelper (this=this@entry=0x555556c47120, nodes=std::vector of length 1, capacity 1 = {...}, fn=..., data=data@entry=0x7fffffffcdf0) at ../hyprland-9999/src/protocols/core/Compositor.cpp:294
#9  0x00005555558ec861 in CWLSurfaceResource::breadthfirst (this=0x555556c47120, fn=..., data=0x7fffffffcdf0) at ../hyprland-9999/src/protocols/core/Compositor.cpp:300
#10 0x000055555593898a in CHyprRenderer::renderWindow (this=<optimized out>, pWindow=..., pMonitor=0x5555568e50d0, time=<optimized out>, decorate=true, mode=RENDER_PASS_ALL, ignorePosition=false, ignoreAllGeometry=false) at ../hyprland-9999/src/render/Renderer.cpp:619
#11 0x00005555559305c2 in CHyprOpenGLImpl::makeWindowSnapshot (this=<optimized out>, pWindow=...) at ../hyprland-9999/src/render/OpenGL.cpp:2327
#12 0x000055555576e5ef in Events::listener_unmapWindow (owner=<optimized out>, data=<optimized out>) at ../hyprland-9999/src/events/Windows.cpp:611
#13 0x0000555555753daa in operator() (__closure=0x555556a6c240, d=std::any [no contained value]) at ../hyprland-9999/src/desktop/Window.cpp:68
#14 std::__invoke_impl<void, CWindow::CWindow(Hyprutils::Memory::CSharedPointer<CXDGSurfaceResource>)::<lambda(std::any)>&, std::any> (__f=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/invoke.h:61
#15 std::__invoke_r<void, CWindow::CWindow(Hyprutils::Memory::CSharedPointer<CXDGSurfaceResource>)::<lambda(std::any)>&, std::any> (__fn=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/invoke.h:111
#16 std::_Function_handler<void(std::any), CWindow::CWindow(Hyprutils::Memory::CSharedPointer<CXDGSurfaceResource>)::<lambda(std::any)> >::_M_invoke(const std::_Any_data &, std::any &&) (__functor=..., __args#0=<optimized out>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/std_function.h:290
#17 0x00007ffff7c56fcc in Hyprutils::Signal::CSignalListener::emit(std::any) () at /usr/lib64/libhyprutils.so.1
#18 0x00007ffff7c5753e in Hyprutils::Signal::CSignal::emit(std::any) () at /usr/lib64/libhyprutils.so.1
#19 0x00005555558dc829 in operator() (d=std::any [no contained value], __closure=0x555556af70d0) at ../hyprland-9999/src/protocols/XDGShell.cpp:338
#20 std::__invoke_impl<void, CXDGSurfaceResource::CXDGSurfaceResource(Hyprutils::Memory::CSharedPointer<CXdgSurface>, Hyprutils::Memory::CSharedPointer<CXDGWMBase>, Hyprutils::Memory::CSharedPointer<CWLSurfaceResource>)::<lambda(std::any)>&, std::any> (__f=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/invoke.h:61
#21 std::__invoke_r<void, CXDGSurfaceResource::CXDGSurfaceResource(Hyprutils::Memory::CSharedPointer<CXdgSurface>, Hyprutils::Memory::CSharedPointer<CXDGWMBase>, Hyprutils::Memory::CSharedPointer<CWLSurfaceResource>)::<lambda(std::any)>&, std::any> (__fn=...)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/invoke.h:111
#22 std::_Function_handler<void(std::any), CXDGSurfaceResource::CXDGSurfaceResource(Hyprutils::Memory::CSharedPointer<CXdgSurface>, Hyprutils::Memory::CSharedPointer<CXDGWMBase>, Hyprutils::Memory::CSharedPointer<CWLSurfaceResource>)::<lambda(std::any)> >::_M_invoke(const std::_Any_data &, std::any &&) (__functor=..., __args#0=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/std_function.h:290
#23 0x00007ffff7c56fcc in Hyprutils::Signal::CSignalListener::emit(std::any) () at /usr/lib64/libhyprutils.so.1
#24 0x00007ffff7c5753e in Hyprutils::Signal::CSignal::emit(std::any) () at /usr/lib64/libhyprutils.so.1
#25 0x00005555558e977a in CWLSurfaceResource::destroy (this=0x555556c47120) at ../hyprland-9999/src/protocols/core/Compositor.cpp:159
#26 0x0000555555973031 in std::function<void(CWlSurface*)>::operator() (this=0x555556c470c0, __args#0=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/std_function.h:591
#27 CWlSurface::onDestroyCalled (this=0x555556c46f60) at protocols/wayland.cpp:2031
#28 _CWlSurface__DestroyListener (l=<optimized out>, d=<optimized out>) at protocols/wayland.cpp:1853
#29 0x00007ffff7e610d4 in ??? () at /usr/lib64/libwayland-server.so.0
#30 0x00007ffff7e651c3 in wl_client_destroy () at /usr/lib64/libwayland-server.so.0
#31 0x00007ffff7e655d8 in ??? () at /usr/lib64/libwayland-server.so.0
#32 0x00007ffff7e646b3 in ??? () at /usr/lib64/libwayland-server.so.0
#33 0x00007ffff7e65509 in wl_display_run () at /usr/lib64/libwayland-server.so.0
#34 0x00005555557fc6f5 in CEventLoopManager::enterLoop (this=0x555555bfe290) at ../hyprland-9999/src/managers/eventLoop/EventLoopManager.cpp:52
#35 0x000055555564c77e in main (argc=<optimized out>, argv=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/unique_ptr.h:193
```

**Comment by vaxerski** [comment]
thanks :)

**Comment by vaxerski** [comment]
try now

**Comment by gulafaran** [comment]
> try now

yeah works now

**Comment by vaxerski** [comment]
top, merging then, thanks!

**Pull request merged**
