### PR TITLE
meson: install wlroots headers

### PR DESCRIPTION
**Pull request by fufexan**
#### Describe your PR, what does it fix/add?
Installs wlroots headers using Meson. Follow-up to #2201.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
No

#### Is it ready for merging, or does it need work?
Ready.

### CODE REVIEW

**Comment by fufexan** [comment]
@eli-schwartz I've followed your instructions in the other PR but I'm getting this error
```sh
Initialized empty Git repository in /home/mihai/Documents/code/git/Hyprland/subprojects/wlroots/.git/
remote: Enumerating objects: 476, done.
remote: Counting objects: 100% (476/476), done.
remote: Compressing objects: 100% (459/459), done.
remote: Total 476 (delta 29), reused 170 (delta 8), pack-reused 0
Receiving objects: 100% (476/476), 763.12 KiB | 1.07 MiB/s, done.
Resolving deltas: 100% (29/29), done.
From https://gitlab.freedesktop.org/wlroots/wlroots
 * branch            6830bfc17fd94709e2cdd4da0af989f102a26e59 -> FETCH_HEAD
HEAD is now at 6830bfc render/pixman: implement render pass API
Applying diff file "wlroots-meson-build.patch"

meson.build:42:10: ERROR: Diff file "/home/mihai/Documents/code/git/Hyprland/subprojects/packagefiles/wlroots-meson-build.patch" does not exist

A full log can be found at /home/mihai/Documents/code/git/Hyprland/build/meson-logs/meson-log.txt
```
Here's the log as well [meson-log.txt](https://github.com/hyprwm/Hyprland/files/11460553/meson-log.txt)

**Comment by droc12345** [comment]
I have a (perhaps silly) question.

At the point where hyprland is built including subprojects, ie the install portion of the meson file.
Why are you not copying the wlroots headers from subproj, as the 1st thing to do in the install portion of meson?

Meson is extremely picky about adding a patch to a subproj that it downloads, it used to not be possible, but 
I haven't kept up with the very latest on that front.

**Comment by eli-schwartz** [comment]
> I've followed your instructions in the other PR but I'm getting this error

One of them is called "wlroots-build-meson" and the other is called "wlroots-meson-build". The file that is specified in the wrap file genuinely does not exist. :)

**Comment by vaxerski** [comment]
if we're patching wlroots, maybe we can also patch the sover to xx032 that cmake uses to avoid .so conflicts?

**Comment by fufexan** [comment]
> > I've followed your instructions in the other PR but I'm getting this error
> 
> One of them is called "wlroots-build-meson" and the other is called "wlroots-meson-build". The file that is specified in the wrap file genuinely does not exist. :)

My stupidity is starting to amaze me.

**Comment by fufexan** [comment]
I think the revision will need manual updating, unless I can make the `bump inputs` action also rewrite the wrap file.

**Comment by fufexan** [comment]
Okay, revision updating is taken care of.

**Review by vaxerski — APPROVED** [review]
coolio, this should also install wlr/config.h afaik so it should be alr

**Comment by fufexan** [comment]
> coolio, this should also install wlr/config.h afaik so it should be alr

Currently it installs it in `include/wlr`, not `include/hyprland/wlroots`. Should I try to change that?

**Comment by vaxerski** [comment]
absolutely, otherwise headers are invalid

**Comment by fufexan** [comment]
I believe it's done. The result after `meson install`
```
/usr/local/include
└── hyprland
   ├── protocols
   ├── src
   └── wlroots
   ```

**Comment by droc12345** [comment]
Not seeing wlroots show up in include/hyprland, this is all I see.

include/
include/hyprland
include/hyprland/src
include/hyprland/src/config
include/hyprland/src/debug
include/hyprland/src/events
include/hyprland/src/helpers
include/hyprland/src/hyprerror
include/hyprland/src/init
include/hyprland/src/layout
include/hyprland/src/managers
include/hyprland/src/managers/input
include/hyprland/src/plugins
include/hyprland/src/protocols
include/hyprland/src/render
include/hyprland/src/render/decorations
include/hyprland/src/render/shaders
include/hyprland/src/wlrunstable
include/hyprland/protocols

I don't even see in meson.build where it tries to copy the wlroots include files.

**Comment by fufexan** [comment]
@droc12345 Yeah, I need to update the wiki instructions. You need to do `meson subprojects update --reset` before `meson setup build`. That'll apply the patch before building.

**Comment by droc12345** [comment]
In my case, I  am on gentoo and had skip-subprojects set for meson install, without that it looks ok

I now see the wlr include dir. 

Sorry for the noise

**Comment by fufexan** [comment]
No problem, you reminded me to update the wiki.

**Pull request merged**
