### PR TITLE
Master layout: add dispatchers rollnext and rollprev

### LINKED ISSUE #1300: Master layout ability to cycle through stack
Add a new option to switch master window with the next or previous on stack. 
But keep the focus on master.

Consider the following example layout with * denoting the currently focused window:
Next window on stack
```
+-----------+-----------+
|           |     B     |
|           +-----------+
|     A*    |     C     |
|           +-----------+
|           |     D     |
+-----------+-----------+
```

Next window on stack
```
+-----------+-----------+
|           |     C     |
|           +-----------+
|     B*    |     D     |
|           +-----------+
|           |     A     |
+-----------+-----------+

```
Next window on stack
```
+-----------+-----------+
|           |     D     |
|           +-----------+
|     C*    |     A     |
|           +-----------+
|           |     B     |
+-----------+-----------+
```

Previous window on stack
```
+-----------+-----------+
|           |     C     |
|           +-----------+
|     B*    |     D     |
|           +-----------+
|           |     A     |
+-----------+-----------+
```

### PR DESCRIPTION
**Pull request by thejch**
#### Describe your PR, what does it fix/add?
Closes #1300 

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
No

#### Is it ready for merging, or does it need work?
Ready

### CODE REVIEW

**Comment by ibrahimkettaneh** [comment]
Great work!

**Review by vaxerski — APPROVED** [review]
cool, just needs a wiki mr

**Comment by ibrahimkettaneh** [comment]
Nice, progress much faster than I expected! :)
I suggest defining these dispatchers like this:
```
| rollnext | rotates the stack forward, maintaining focus on the master |
| rollprev | rotates the stack backwards, maintaining focus on the master |
```
Line 48 is one sensible place for this addition
As you know since you often contribute to it, the file is at https://github.com/hyprwm/hyprland-wiki/blob/main/pages/Configuring/Master-Layout.md?plain=1
Thank you both very much! :grin:

**Comment by thejch** [comment]
> cool, just needs a wiki mr

Added

**Comment by PsyNyde** [comment]
Yay :D

**Pull request merged**
