### PR TITLE
Fixup double rendering cases with special

### LINKED ISSUE #3888: Transparency difference on special workspace
### Hyprland Version

Hyprland, built from branch makepkg at commit 8b57a1973ea8b242783069e9a3e3d31e3cd939a8 dirty (internal: Allow floating windows on special (3872)). Tag: v0.32.3-34-g8b57a197

### Bug or Regression?

Bug

### Description

Semi-Transparent windows are less transparent if they are in a special workspace.

### How to reproduce

Well, open a semitransparent window on a non-special, memorize how transparent it is, and then move it to a special workspace and compare

### Crash reports, logs, images, videos

_No response_

### PR DESCRIPTION
**Pull request by vaxerski**
Aims to fix #3888 #3916 #3889

let me know if it works @Dickby @thejch

### CODE REVIEW

**Comment by Dickby** [comment]
There seems to be only blur on regular-workspace-windows if the special workspace is visible.
With hidden special-ws the stuff that should be blured is just black

**Comment by Dickby** [comment]
With either new_optimizations or xray enabled, blur works as expected, but both set to false leads to the problem is discribed above

**Comment by vaxerski** [comment]
new_optimizations should be removed as it should NEVER be disabled. Code has expected it to be the case for a while now. Unrelated to this MR, anyways

**Comment by Dickby** [comment]
So a tiled window that moves above another tiled window should never be visible in the blured alpha?

**Comment by vaxerski** [comment]
tiled windows should not overlap.

**Comment by Dickby** [comment]
But they do while window move animations

**Comment by vaxerski** [comment]
that's an edge case that I don't want to fix for the sake of performance. It's barely noticeable, anyways.

**Comment by vaxerski** [comment]
at any rate, that's unrelated to this MR. Lmk if it fixes your open issues.

**Comment by Dickby** [comment]
I notice it very much and i would prefer to have that option, but it's your choice.
In that case the problem seems fixed, let's see if thejch finds something.

**Comment by Dickby** [comment]
Wait there is still some double rendering while the special-ws is sliding in

**Comment by vaxerski** [comment]
the thing that made it black for you is aedcade68dd0615fd919a7249633a554d0accd81

I can fix that later.

**Comment by vaxerski** [comment]
> Wait there is still some double rendering while the special-ws is sliding in

on the special ws or regular ws? floating?

**Comment by Dickby** [comment]
The special, it's not always the case. The active regular workspace has to be non_fullscreen. 
Newly created windows on the special-ws will be rendered at least twice while the special workspace is sliding in.
if the regular-ws is then fullscreened and the special workspace is activated again, the problem is gone even if the regular-ws window is unfullscreened again.
If you create a new window on that special however, that window will have that problem while siliding in, while the old window will be fine during the sliding animations.

**Comment by thejch** [comment]
Yeah there's still occasional double rendering when the window slides in, especially when you have a maximized window open in the regular workspace. But it doesn't always happen. I'll try and find a consistent way to reproduce that.
Other than that it seems fixed.

**Comment by thejch** [comment]
So it happens when I open special, create a window, close special, create a window in regular, fullscreen it, and then toggle special. Now the special window gets double rendered during the animation. Not sure if it's the same thing described by dickby, because in their case it says
> the active regular workspace has to be non_fullscreen.

which is the opposite of mine

**Comment by Eclextic** [comment]
> So it happens when I open special, create a window, close special, create a window in regular, fullscreen it, and then toggle special. Now the special window gets double rendered during the animation. Not sure if it's the same thing described by dickby, because in their case it says
> 
> > the active regular workspace has to be non_fullscreen.
> 
> which is the opposite of mine

Probably is then exactly the same (Some kind of bool that should be reset/toggled, isn't getting toggled )

**Comment by vaxerski** [comment]
fixed @thejch any other issues?

**Comment by thejch** [comment]
I don't notice any on my end.

**Comment by vaxerski** [comment]
@Dickby is your issue fixed?

**Comment by vaxerski** [comment]
been running this myself for a while, seems to be working to me.

**Pull request merged**
