### PR TITLE
s/pkgs.system/pkgs.hostPlatform.system/g

### PR DESCRIPTION
**Pull request by colemickens**
#### Describe your PR, what does it fix/add?

I have aliases disabled ever since a user of one of my repos sent a PR for it... so now I'm paying it forward I guess.

Thanks for hyprland... I think... still getting the initial config going.

### CODE REVIEW

**Comment by vaxerski** [comment]
@fufexan

**Comment by fufexan** [comment]
Thanks for this.

Mind explaining what the benefit of using `hostPlatform` is? It's not directly clear to me.

**Comment by colemickens** [comment]
`pkgs.system` is wrong in some scenarios, like cross-compiling. Also, is just doesn't exist for me, since I have these aliases disabled (forces me to notice things like this, keep up with tech rot/debt, etc).

In this case, when I cross-compile `pkgs.system` is going to be `x86_64-linux`, but `pkgs.hostPlatform.system` is going to be `riscv64-linux`, etc.

**Comment by fufexan** [comment]
Ah, okay. That makes sense. Thanks for the explanation.

**Comment by fufexan** [comment]
Btw `prev.system` exists in the overlay inside flake.nix. Shouldn't that be changed as well?

**Comment by colemickens** [comment]
Okay, I tested, you're right, it was necessary if I forced the use of the overlay with nixpkgs.config.allowAliases = false. Tested with the change, it fixes eval. Should be good to go now.

**Comment by fufexan** [comment]
Thank you!

**Pull request merged**
