### PR TITLE
feat: dispatcher, add workspace renaming

### PR DESCRIPTION
**Pull request by cyrinux**
Hi, thanks for this cool project !

This PR add a dispatcher to rename temporary a workspace with hyprctl / or over socket.

```
$ hyprctl dispatcher renameworkspace 2 aaaaa
ok
```

I use waybar  (AUR waybar-hyprland-git) and I well see the workspace name changing with the module `wlr/workspaces`.
The name is also well propagate in `hyprctl workspaces -j`.

It is working for me.

record_1673131215

Regards,

### CODE REVIEW

**Comment by maximbaz** [comment]
Thanks! 🥳  This will help implementing [sway-like autoname-workspaces](https://github.com/swaywm/sway/blob/master/contrib/autoname-workspaces.py), and also help with https://github.com/hyprwm/Hyprland/issues/665!

**Comment by cyrinux** [comment]
Thanks for the @vaxerski , it should be better now 👍🏻

**Comment by cyrinux** [comment]
Following the last commit, after chatting with @maximbaz you are interested too, we can now rename with an empty name.
Ready for review.

**Comment by vaxerski** [comment]
add a pr to the wiki pls

**Pull request merged**
