### PR TITLE
update example hyprland.conf

### PR DESCRIPTION
**Pull request by memchr**
#6479 replace master:new_is_master with master:new_status

### CODE REVIEW

**Review by fufexan — APPROVED** [review]

**Comment by fufexan** [comment]
https://github.com/hyprwm/Hyprland/blob/main/src/config/defaultConfig.hpp#L141 should also be updated.

**Review by fufexan — APPROVED** [review]

**Comment by noahfraiture** [comment]
What is the point except break config ?

**Comment by TSmigielski** [comment]
I don't mind such changes, but a heads up in the changelog about a breaking config update would be nice.

**Comment by onyasumi** [comment]
> What is the point except break config ?

not much, it seems

**Pull request merged**
