### PR TITLE
some minor fd/socket cleanups and make logging thread safe

### PR DESCRIPTION
**Pull request by gulafaran**
the logger change is something i kinda made apparent on my own by placing various Debug::log() in places to figure things out and suddenly i hit bad things, so make it thread safe and only open file once on start and close it on exit.

the rest is a few fd/socket leaks and closing already closed or closing -1 fd's making valgrind a bit spammy.

also change the way bezier loops over getYForPoint,

looping a float and incrementing it can cause subtle precision errors like looping 8 times or 10 times depending on how it turns out. god willing it does it right. so loop 9 iterations and get the float value from that instead

### CODE REVIEW

**Review by vaxerski — APPROVED** [review]
danke

**Comment by vaxerski** [comment]
no pch failed

**Comment by gulafaran** [comment]
> no pch failed

ah yeah just noticed, fixing. uno minuto.

**Comment by gulafaran** [comment]
> no pch failed

fixed.

**Review by vaxerski — APPROVED** [review]
sehr schoen

**Pull request merged**
