### PR TITLE
Replace $(nproc) with $(shell nproc).

### PR DESCRIPTION
**Pull request by Dickby**
#### Describe your PR, what does it fix/add?
At least on my end, just $(nproc) doesn't set the number.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
I don't really know why this is, check if it's the same on your setup.

#### Is it ready for merging, or does it need work?
If it has no different behavior elsewhere, it can be merged.

### CODE REVIEW

**Comment by vaxerski** [comment]
`command not found: shell`

you mean `/bin/sh`?

**Comment by Dickby** [comment]
Hmm, this works for me!
With /bin/sh it doesn't.
I don't have time now, but i'll research later what the issue is.

**Comment by Dickby** [comment]
But is it working for you as it is right now?

**Comment by Dickby** [comment]
Do you get that error when compiling, or did you just test it in a terminal?
In a terminal i get the same error.

**Comment by vaxerski** [comment]
term, but I wouldnt risk it

**Comment by Dickby** [comment]
A small search later, i know that it's the way to use shell command in makefiles:
https://stackoverflow.com/questions/10024279/how-to-use-shell-commands-in-makefile

**Comment by Dickby** [comment]
Or more official:
https://www.gnu.org/software/make/manual/html_node/Shell-Function.html

**Comment by vaxerski** [comment]
alr then

**Pull request merged**
