### PR TITLE
Hide cursor on leave

### PR DESCRIPTION
**Pull request by vaxerski**
Hides the hw cursor plane when it leaves the output.

Ref #7412

needs testing

### CODE REVIEW

**Comment by drammelt** [comment]
The hiding part works for moving screens, however when the mouse moves over any window decorations it still appears for a split second then disappears again.

I think it maybe the call from CInputManager::processMouseRequest to CPointerManager::setCursorBuffer as that calls updateCursorBackend -> attemptHardwareCursor which sets the buffer bypassing the screen checks.

**Comment by vaxerski** [comment]
should be fixed, try now

**Comment by drammelt** [comment]
So close, only one thing happening now. when the cursor transitions from one monitor to another and immediately encounters a window decoration or something like waybar the previous screens cursor remains until the current screens cursor leave the decoration/input area.

IMG_20240916_200629_691

**Comment by leiserfg** [comment]
@drammelt That's two cursors for the price of one.

**Comment by vaxerski** [comment]
I'd say that's minor and overall better than main so I'll merge this

**Pull request merged**
