### PR TITLE
do not overwrite existing `hyprland.desktop`

### PR DESCRIPTION
**Pull request by NotAShelf**
#### Describe your PR, what does it fix/add?
Implements a "fix" for the long-standing issue of desktop files being overwritten on each `make install` by copying only if `hyprland.desktop` does not exist. Also removes `cleaninstall` option because it is obsolete with this PR.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
N/A

#### Is it ready for merging, or does it need work?
Tested on my own desktop, worked. If it does not work on your machine, your system is haunted.

### CODE REVIEW

**Comment by NotAShelf** [comment]
I will make a PR to the wiki if this looks ready to merge.

**Comment by vaxerski** [comment]
firstly, don't remove cleaninstall, deprecate it. Aka, just echo "deprecated blah blah" and run make install

secondly, wiki pr

thirdly, this wont fix the packages (which is most of people), but cool i guess.

**Comment by NotAShelf** [comment]
> firstly, don't remove cleaninstall, deprecate it. Aka, just echo "deprecated blah blah" and run make install
Pretty sure I was the only one using that, but sure. I'll make it echo something and run make install instead

> secondly, wiki pr
The PR is ready to be made, it was just awaiting confirmation

> thirdly, this wont fix the packages (which is most of people), but cool i guess.
it *should* fix those packages, don't those use install in the PKGBUILD? (didn't read the PKGBUILD how could you tell)

**Comment by vaxerski** [comment]
nope they don't cuz they can't. They run in a sandbox.

**Comment by NotAShelf** [comment]
darn, maybe I can patch the PKGBUILDs with some workaround

in the meantime I'll fix this PR and send the wiki PR your way

**Comment by NotAShelf** [comment]
...and I forgot to mention, this PR also does move the copy function for the desktop file below the binaries because we don't want to have a desktop file that doesn't work if binaries don't work for some reason

shouldn't matter anyway

**Comment by NotAShelf** [comment]
Should be good now, wiki PR made over [#79](https://github.com/hyprwm/hyprland-wiki/pull/79)

**Pull request merged**
