### PR TITLE
Remove dependency on cc from the hooksystem

### PR DESCRIPTION
**Pull request by vaxerski**
Removes the step where we'd call `cc` with raw assembly on a string.

I have briefly tested it and seems to work, but needs more testing probably.

cc @outfoxxed (hy3) @DreamMaoMao (hycov) @fufexan (cuz he's cute)

### CODE REVIEW

**Review by fufexan — APPROVED** [review]

**Comment by vaxerski** [comment]
thanks, I'll wait for input from outfoxxed and dreammaomao before merging though, wanna make sure all is working

**Comment by outfoxxed** [comment]
LGTM, my hooks still work.

**Comment by DreamMaoMao** [comment]
no problem ,still work

**Comment by vaxerski** [comment]
Thanks!

**Pull request merged**
