### PR TITLE
Added moveCursor dispatcher

### PR DESCRIPTION
**Pull request by mekb-turtle**
#### Describe your PR, what does it fix/add?
Adds a dispatcher to warp the cursor to a location

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
It doesn't return an error if it is out of bounds

#### Is it ready for merging, or does it need work?
Might need to be changed with returning errors

### CODE REVIEW

**Comment by vaxerski** [comment]
why?

**Comment by vaxerski** [comment]
I still am not sure whether allowing simulating user input that easily should be a thing

**Comment by mekb-turtle** [comment]
It's already possible with things like `wtype` but that's only text, I don't see why allowing user input would be an issue

**Comment by vaxerski** [comment]
fair enough, please make an accompanying wiki mr then

**Review by vaxerski — APPROVED** [review]

**Comment by mekb-turtle** [comment]
done, hyprwm/hyprland-wiki#196

**Pull request merged**
