### PR TITLE
Fix workspace rule loops

### PR DESCRIPTION
**Pull request by thejch**
#### Describe your PR, what does it fix/add?
Addressess https://github.com/hyprwm/Hyprland/pull/5340#issuecomment-2038081538
Merge the rules before returning.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
breaking API change again smfh, but this wasnt the best design to begin with

#### Is it ready for merging, or does it need work?
ready

### CODE REVIEW

**Comment by vaxerski** [comment]
is pineapple an animal

**Comment by thejch** [comment]
> I think the processing of onCreatedEmptyExecuted needs to use a vectorized version. Although I guess it depends on which behavior is wanted.
> 
> Before this PR it used the vectorized version and ran every rule that matched. Now it runs the last one. I kinda feel like running them all is more intuitive, but it didn't work that way prior to 0.38 anyways soooo
> 
> It might be ok to leave getWorkspaceRulesFor since removing it is going to break anyone that converted their code for 0.38. But that's not up to me ;)

first point makes sense to me
second point i'll wait for vaxry's input

**Comment by vaxerski** [comment]
> It might be ok to leave getWorkspaceRulesFor since removing it is going to break anyone that converted their code for 0.38. But that's not up to me ;)

do I look like a person that cares that much about this one lmao

I am still waiting on input regarding my previous question

**Comment by zakk4223** [comment]
pineapples are only animals if they scream when you cut them open

**Review by vaxerski — APPROVED** [review]
lgtm

**Pull request merged**
