### PR TITLE
Allow headless mode in hyprland

### PR DESCRIPTION
**Pull request by thejch**
#### Describe your PR, what does it fix/add?
Fixes https://github.com/hyprwm/Hyprland/issues/1917
Allow headless mode in hyprland
Doesn't change any behavior when not in headless

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
This PR does not claim to provide complete or full support for headless mode, but does unbreak it so that it could run. Any potential issues in headless mode may still exist

#### Is it ready for merging, or does it need work?
Ready

### CODE REVIEW

**Comment by thejch** [comment]
@vaxerski thoughts on this?

**Comment by Eclextic** [comment]
Wasn't there an MR where it was discussed that Hyprland isn't the WM that was designed for this use case? And that a different Compositor would be better suited? (e.g. Weston)

**Comment by thejch** [comment]
> Wasn't there an MR where it was discussed that Hyprland isn't the WM that was designed for this use case? And that a different Compositor would be better suited? (e.g. Weston)

I dont know what your'e talking about. This feature comes out of the box with wlroots and all I did was unbreak it.

**Review by vaxerski — APPROVED** [review]
lgtm

**Comment by fxzxmicah** [comment]
This change is no longer valid after hyprland drops wlroots.

**Pull request merged**
