### PR TITLE
[WIP] Wobbly windows effect

### PR DESCRIPTION
**Pull request by TheSunCat**
#### Describe your PR, what does it fix/add?
This PR adds an optional wobble simulation to windows when they are moved. It implements #1184.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
I need help rendering the effect as I am unsure how I could deform an entire window in Renderer.cpp without making the code a mess. My own code also requires a lot of cleanup, as it is heavily based on [this](https://github.com/soreau/wobbly) C implementation and thus missing a lot of C++ niceties and style.
This is also missing configuration support, as it is enabled for all windows at the moment.
I will keep working this and adding commits.

#### Is it ready for merging, or does it need work?
This is not functional yet, but the base simulation is there.

### CODE REVIEW

**Comment by vaxerski** [comment]
Any usage of `new` and `delete` is strictly banned from the codebase.

Make configurable options: `enabled`, `only floating` and windowrules.

**Comment by TheSunCat** [comment]
Done :)

**Comment by TheSunCat** [comment]
I'm unsure how to approach the windowrule, but I think we should make sure this works before fleshing out the config. It will also need some configurable factors for the simulation (that together control wobblyness).

**Comment by vaxerski** [comment]
don't make wobble into a separate category, why?

**Comment by TheSunCat** [comment]
You said to name it `enabled`, and that can't go into `animations` as it would conflict with `animations:enabled`. We can rename it to `animations:enable_wobble` if you think that fits better.

**Comment by vaxerski** [comment]
wobble_enabled
wobble_other
wobble_stuff

**Comment by TheSunCat** [comment]
done

**Comment by TheSunCat** [comment]
Is there anything else I can do to help out with implementation of rendering?
I was thinking of making a separate shader for wobbly windows that take the simulation's parameters as input and in a geometry shader subdivide the four-vertex quad into the wobbled grid of verts it needs to be (taking the UVs with it). As for damage, it needs to be between the model's `m_vTopLeft` and `m_vBottomRight` vectors, which are updated every time the model is so it should contain the whole window.

**Comment by vaxerski** [comment]
the problem is with decorations, e.g. shadows. Wobbly windows in hyprland would require a major rewrite and probably would slow down computers noticeably, as how I am seeing it right now, would require drawing to a separate fbo, applying the wobble and then back to the main fbo, which will add up to 2 additional drawcalls per window.

I am still not convinced this is a good idea.

**Comment by TheSunCat** [comment]
Do you think we could make the extra drawcalls an optional control path, only if wobbly windows (or potential other effects that would require it) are enabled? I think a user enabling wobbly windows would be conscious that this can have a noticeable performance impact.
As for drawing to a separate framebuffer, yes this is a possibility, but why not just apply a geometry shader to the quads we already draw for windows (and presumably decorations; I'm unfamiliar with that part of the code)? This would only add zero draw calls: just using the different shader (and setting the uniforms).

**Comment by TheSunCat** [comment]
From my understanding of geometry shaders, this is exactly the kind of drawcall we can deform with a single glUseShader:
[Borders rendering with glDrawArrays](https://github.com/hyprwm/Hyprland/blob/71602a11ca45ae20ecd084d007b55fac6f569af4/src/render/OpenGL.cpp#L1011).

**Comment by vaxerski** [comment]
we could of course but this is likely to get ugly.

buddy the shadow is one quad, we're not subdividing it. Besides, many decos might draw multiple things (e.g. groupbar)

**Comment by TheSunCat** [comment]
It's the same glDrawArrays call which is easily deformed alongside the surface itself + borders by a shader. No additional code would be required on the CPU side.

**Comment by vaxerski** [comment]
feel free to attempt

**Comment by TheSunCat** [comment]
It would take me a lot of time to familiarize myself with the way Hyprland's rendering code works, as well as the many macros I see it uses. This is why I did not even try to implement rendering... I was hoping you might give it a try. I can make the necessary shader (just porting the calc geometry function to glsl) but integrating it into the renderer sounds like I'll just write even more spaghetti à la bolognaise than usual.

**Comment by vaxerski** [comment]
I can clean it up later, but I am not willing to write the impl.

**Comment by TheSunCat** [comment]
Understood. I will implement it when I find the time in that case, but expect a large portion of spaghetti.

**Comment by TheSunCat** [comment]
I'm reading through the code and it seems that, though Hyprland is using OpenGL ES 3.2, it has an optional OpenGL ES 2.0 backend. If I were to use a geometry shader, I would be unable to support that backend. Is this a problem, or is it okay for some features to be exclusive to OpenGL ES 3.2?

**Comment by taylor85345** [comment]
That would be the legacy renderer, and I believe there are already features in Hyprland which don't support the legacy renderer.

**Comment by TheSunCat** [comment]
Got it! I'll wrap the wobble rendering in ifdefs, then.

**Comment by TheSunCat** [comment]
Nope, any help would be highly appreciated!

**Comment by TheSunCat** [comment]
The simulation needs to be rendered. Currently there is no visual effect (just a jello simulation attached to each window).

**Comment by Aesop7** [comment]
Been looking forward to this...   Happy to help test if needed!

**Comment by yavko** [comment]
> Been looking forward to this... Happy to help test if needed!

Nothing to test, no actual implementation atm.

**Comment by TheSunCat** [comment]
I think this might be better implemented as a plugin. I don't currently have the time to rewrite it, nor implement rendering at the moment. If anyone wants to pick this up, please do. The simulation itself is finished and seems to work fine, it's just missing the rendering.
The basic idea is to give each window its own framebuffer to draw to, and then deform the framebuffer itself when drawing to the actual monitor.

**Comment by exoess** [comment]
what's the status on this?

**Comment by vaxerski** [comment]
safe to say the MR is abandoned

**Comment by exoess** [comment]
sadge, what is this btw? i assumed it was hyprland because it was on the wiki but it has the wobbly workspace switching (https://media.discordapp.net/attachments/810799100940255260/1032846469855727656/ezgif.com-gif-maker19.gif)

**Comment by vaxerski** [comment]
I am not sure but IIRC it's hyprland

**Comment by exoess** [comment]
any idea how it was made? also mind if i msg you on discord about it?

**Comment by vaxerski** [comment]
looks like an overshot curve. Don't dm me on discord, come to our discord server and talk there :)

**Comment by exoess** [comment]
already part of the server lol

**Comment by TheSunCat** [comment]
> safe to say the MR is abandoned

I am indeed not working on this at the moment. The simulation is functional (I think), but it is not being rendered. Anyone is welcome to pick this up from me!

**Comment by ThatOneCalculator** [comment]
> I am not sure but IIRC it's hyprland

This is my screen recording. It's just an overshoot curve, with the infinity-mirroring from OBS giving it an optical illusion of wobbling.

**Comment by yavko** [comment]
Maybe the new code in https://github.com/hyprwm/Hyprland/commit/92311d260ab25c11adab05678663bdccaff11fa6 can be used?

**Comment by TheSunCat** [comment]
I will be looking into this once I get some time! Can likely base it off of this demo impl of just rotating rainbow windows that vaxry shared:
```cpp
#define WLR_USE_UNSTABLE

#include <unistd.h>

#include <hyprland/src/Compositor.hpp>
#include <hyprland/src/Window.hpp>
#include <hyprland/src/config/ConfigManager.hpp>
#include <hyprland/src/plugins/PluginAPI.hpp>
#include <hyprland/src/render/OpenGL.hpp>
#include <vector>

inline HANDLE PHANDLE = nullptr;

// Do NOT change this function.
APICALL EXPORT std::string PLUGIN_API_VERSION() { return HYPRLAND_API_VERSION; }

class CWindowTransformer : public IWindowTransformer {
   public:
    virtual CFramebuffer* transform(CFramebuffer* in);
    virtual void preWindowRender(SRenderData* pRenderData);

   private:
    float rot = 0;
    float hue = 0;
};

std::vector<CWindowTransformer*> ptrs;

typedef struct {
    double r;  // ∈ [0, 1]
    double g;  // ∈ [0, 1]
    double b;  // ∈ [0, 1]
} rgb;

typedef struct {
    double h;  // ∈ [0, 360]
    double s;  // ∈ [0, 1]
    double v;  // ∈ [0, 1]
} hsv;

rgb hsv2rgb(hsv HSV) {
    rgb RGB;
    double H = HSV.h, S = HSV.s, V = HSV.v, P, Q, T, fract;

    (H == 360.) ? (H = 0.) : (H /= 60.);
    fract = H - floor(H);

    P = V * (1. - S);
    Q = V * (1. - S * fract);
    T = V * (1. - S * (1. - fract));

    if (0. <= H && H < 1.)
        RGB = (rgb){.r = V, .g = T, .b = P};
    else if (1. <= H && H < 2.)
        RGB = (rgb){.r = Q, .g = V, .b = P};
    else if (2. <= H && H < 3.)
        RGB = (rgb){.r = P, .g = V, .b = T};
    else if (3. <= H && H < 4.)
        RGB = (rgb){.r = P, .g = Q, .b = V};
    else if (4. <= H && H < 5.)
        RGB = (rgb){.r = T, .g = P, .b = V};
    else if (5. <= H && H < 6.)
        RGB = (rgb){.r = V, .g = P, .b = Q};
    else
        RGB = (rgb){.r = 0., .g = 0., .b = 0.};

    return RGB;
}

Vector2D oldPos, newPos;

void renderTex(wlr_box monbox, CTexture& tex, float rot, rgb tint) {
    if (g_pHyprOpenGL->m_RenderData.damage.empty()) return;

    wlr_box newBox = monbox;
    scaleBox(&newBox, g_pHyprOpenGL->m_RenderData.renderModif.scale);
    newBox.x += g_pHyprOpenGL->m_RenderData.renderModif.translate.x;
    newBox.y += g_pHyprOpenGL->m_RenderData.renderModif.translate.y;

    // get transform
    const auto TRANSFORM = wlr_output_transform_invert(WL_OUTPUT_TRANSFORM_NORMAL);
    float matrix[9];
    wlr_matrix_project_box(matrix, &newBox, TRANSFORM, rot, g_pHyprOpenGL->m_RenderData.pMonitor->output->transform_matrix);

    float glMatrix[9];
    wlr_matrix_multiply(glMatrix, g_pHyprOpenGL->m_RenderData.projection, matrix);

    CShader* shader = &g_pHyprOpenGL->m_RenderData.pCurrentMonData->m_shRGBA;

    glActiveTexture(GL_TEXTURE0);
    glBindTexture(tex.m_iTarget, tex.m_iTexID);

    glUseProgram(shader->program);

#ifndef GLES2
    glUniformMatrix3fv(shader->proj, 1, GL_TRUE, glMatrix);
#else
    wlr_matrix_transpose(glMatrix, glMatrix);
    glUniformMatrix3fv(shader->proj, 1, GL_FALSE, glMatrix);
#endif
    glUniform1i(shader->tex, 0);

    glUniform1i(shader->applyTint, 1);
    glUniform3f(shader->tint, std::clamp(0.2 + tint.r, 0.0, 1.0), std::clamp(0.2 + tint.g, 0.0, 1.0), std::clamp(0.2 + tint.b, 0.0, 1.0));

    const auto TOPLEFT = Vector2D(newBox.x, newBox.y);
    const auto FULLSIZE = Vector2D(newBox.width, newBox.height);

    glUniform2f(shader->topLeft, TOPLEFT.x, TOPLEFT.y);
    glUniform2f(shader->fullSize, FULLSIZE.x, FULLSIZE.y);
    glUniform1f(shader->radius, 0);

    glUniform1i(shader->discardOpaque, 0);
    glUniform1i(shader->discardAlpha, 0);

    glUniform1f(shader->alpha, 1);

    glVertexAttribPointer(shader->posAttrib, 2, GL_FLOAT, GL_FALSE, 0, fullVerts);
    glVertexAttribPointer(shader->texAttrib, 2, GL_FLOAT, GL_FALSE, 0, fullVerts);

    glEnableVertexAttribArray(shader->posAttrib);
    glEnableVertexAttribArray(shader->texAttrib);

    for (auto& RECT : g_pHyprOpenGL->m_RenderData.damage.getRects()) {
        g_pHyprOpenGL->scissor(&RECT);
        glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);
    }

    g_pHyprOpenGL->scissor((wlr_box*)nullptr);

    glDisableVertexAttribArray(shader->posAttrib);
    glDisableVertexAttribArray(shader->texAttrib);

    glBindTexture(tex.m_iTarget, 0);
}

void CWindowTransformer::preWindowRender(SRenderData* pRenderData) {
    oldPos = {(double)pRenderData->x, (double)pRenderData->y};

    pRenderData->x = pRenderData->pMonitor->vecSize.x / 2.f - pRenderData->w / 2.f;
    pRenderData->y = pRenderData->pMonitor->vecSize.y / 2.f - pRenderData->h / 2.f;

    newPos = {(double)pRenderData->x, (double)pRenderData->y};
}

CFramebuffer* CWindowTransformer::transform(CFramebuffer* in) {
    static CFramebuffer off;

    if (!off.isAllocated() || off.m_vSize != in->m_vSize) {
        off.release();
        off.alloc(in->m_vSize.x, in->m_vSize.y);
    }

    off.bind();
    g_pHyprOpenGL->clear(CColor(0, 0, 0, 0));

    wlr_box monbox = {(int)(oldPos.x - newPos.x), (int)(oldPos.y - newPos.y), (int)g_pHyprOpenGL->m_RenderData.pMonitor->vecTransformedSize.x,
                      (int)g_pHyprOpenGL->m_RenderData.pMonitor->vecTransformedSize.y};

    hsv cur{hue, 1, 1};
    rgb col = hsv2rgb(cur);

    renderTex(monbox, in->m_cTex, rot, col);

    rot += 0.01;
    hue += 1.29;
    if (hue > 360) hue -= 360;

    return &off;
}

void onNewWindow(void* self, std::any data) {
    // data is guaranteed
    auto* const PWINDOW = std::any_cast<CWindow*>(data);

    ptrs.push_back(static_cast<CWindowTransformer*>(PWINDOW->m_vTransformers.emplace_back(std::make_unique<CWindowTransformer>()).get()));
}

APICALL EXPORT PLUGIN_DESCRIPTION_INFO PLUGIN_INIT(HANDLE handle) {
    PHANDLE = handle;

    HyprlandAPI::registerCallbackDynamic(PHANDLE, "openWindow", [&](void* self, SCallbackInfo& info, std::any data) { onNewWindow(self, data); });

    HyprlandAPI::addNotification(PHANDLE, "[fun-plugin] Initialized successfully!", CColor{0.2, 1.0, 0.2, 1.0}, 5000);

    return {"fun-plugin", "fun", "Vaxry", "1.0"};
}

APICALL EXPORT void PLUGIN_EXIT() {
    for (auto& w : g_pCompositor->m_vWindows) {
        std::erase_if(w->m_vTransformers, [&](const std::unique_ptr<IWindowTransformer>& other) {
            return std::find_if(ptrs.begin(), ptrs.end(), [&](const auto& p) { return static_cast<IWindowTransformer*>(p) == other.get(); }) !=
                   ptrs.end();
        });
    }
}
```
Good excuse to learn to write Hyprland plugins :)

**Comment by yavko** [comment]
> I will be looking into this once I get some time! Can likely base it off of this demo impl of just rotating rainbow windows that vaxry shared:
> 
> ```c++
> #define WLR_USE_UNSTABLE
> 
> #include <unistd.h>
> 
> #include <hyprland/src/Compositor.hpp>
> #include <hyprland/src/Window.hpp>
> #include <hyprland/src/config/ConfigManager.hpp>
> #include <hyprland/src/plugins/PluginAPI.hpp>
> #include <hyprland/src/render/OpenGL.hpp>
> #include <vector>
> 
> inline HANDLE PHANDLE = nullptr;
> 
> // Do NOT change this function.
> APICALL EXPORT std::string PLUGIN_API_VERSION() { return HYPRLAND_API_VERSION; }
> 
> class CWindowTransformer : public IWindowTransformer {
>    public:
>     virtual CFramebuffer* transform(CFramebuffer* in);
>     virtual void preWindowRender(SRenderData* pRenderData);
> 
>    private:
>     float rot = 0;
>     float hue = 0;
> };
> 
> std::vector<CWindowTransformer*> ptrs;
> 
> typedef struct {
>     double r;  // ∈ [0, 1]
>     double g;  // ∈ [0, 1]
>     double b;  // ∈ [0, 1]
> } rgb;
> 
> typedef struct {
>     double h;  // ∈ [0, 360]
>     double s;  // ∈ [0, 1]
>     double v;  // ∈ [0, 1]
> } hsv;
> 
> rgb hsv2rgb(hsv HSV) {
>     rgb RGB;
>     double H = HSV.h, S = HSV.s, V = HSV.v, P, Q, T, fract;
> 
>     (H == 360.) ? (H = 0.) : (H /= 60.);
>     fract = H - floor(H);
> 
>     P = V * (1. - S);
>     Q = V * (1. - S * fract);
>     T = V * (1. - S * (1. - fract));
> 
>     if (0. <= H && H < 1.)
>         RGB = (rgb){.r = V, .g = T, .b = P};
>     else if (1. <= H && H < 2.)
>         RGB = (rgb){.r = Q, .g = V, .b = P};
>     else if (2. <= H && H < 3.)
>         RGB = (rgb){.r = P, .g = V, .b = T};
>     else if (3. <= H && H < 4.)
>         RGB = (rgb){.r = P, .g = Q, .b = V};
>     else if (4. <= H && H < 5.)
>         RGB = (rgb){.r = T, .g = P, .b = V};
>     else if (5. <= H && H < 6.)
>         RGB = (rgb){.r = V, .g = P, .b = Q};
>     else
>         RGB = (rgb){.r = 0., .g = 0., .b = 0.};
> 
>     return RGB;
> }
> 
> Vector2D oldPos, newPos;
> 
> void renderTex(wlr_box monbox, CTexture& tex, float rot, rgb tint) {
>     if (g_pHyprOpenGL->m_RenderData.damage.empty()) return;
> 
>     wlr_box newBox = monbox;
>     scaleBox(&newBox, g_pHyprOpenGL->m_RenderData.renderModif.scale);
>     newBox.x += g_pHyprOpenGL->m_RenderData.renderModif.translate.x;
>     newBox.y += g_pHyprOpenGL->m_RenderData.renderModif.translate.y;
> 
>     // get transform
>     const auto TRANSFORM = wlr_output_transform_invert(WL_OUTPUT_TRANSFORM_NORMAL);
>     float matrix[9];
>     wlr_matrix_project_box(matrix, &newBox, TRANSFORM, rot, g_pHyprOpenGL->m_RenderData.pMonitor->output->transform_matrix);
> 
>     float glMatrix[9];
>     wlr_matrix_multiply(glMatrix, g_pHyprOpenGL->m_RenderData.projection, matrix);
> 
>     CShader* shader = &g_pHyprOpenGL->m_RenderData.pCurrentMonData->m_shRGBA;
> 
>     glActiveTexture(GL_TEXTURE0);
>     glBindTexture(tex.m_iTarget, tex.m_iTexID);
> 
>     glUseProgram(shader->program);
> 
> #ifndef GLES2
>     glUniformMatrix3fv(shader->proj, 1, GL_TRUE, glMatrix);
> #else
>     wlr_matrix_transpose(glMatrix, glMatrix);
>     glUniformMatrix3fv(shader->proj, 1, GL_FALSE, glMatrix);
> #endif
>     glUniform1i(shader->tex, 0);
> 
>     glUniform1i(shader->applyTint, 1);
>     glUniform3f(shader->tint, std::clamp(0.2 + tint.r, 0.0, 1.0), std::clamp(0.2 + tint.g, 0.0, 1.0), std::clamp(0.2 + tint.b, 0.0, 1.0));
> 
>     const auto TOPLEFT = Vector2D(newBox.x, newBox.y);
>     const auto FULLSIZE = Vector2D(newBox.width, newBox.height);
> 
>     glUniform2f(shader->topLeft, TOPLEFT.x, TOPLEFT.y);
>     glUniform2f(shader->fullSize, FULLSIZE.x, FULLSIZE.y);
>     glUniform1f(shader->radius, 0);
> 
>     glUniform1i(shader->discardOpaque, 0);
>     glUniform1i(shader->discardAlpha, 0);
> 
>     glUniform1f(shader->alpha, 1);
> 
>     glVertexAttribPointer(shader->posAttrib, 2, GL_FLOAT, GL_FALSE, 0, fullVerts);
>     glVertexAttribPointer(shader->texAttrib, 2, GL_FLOAT, GL_FALSE, 0, fullVerts);
> 
>     glEnableVertexAttribArray(shader->posAttrib);
>     glEnableVertexAttribArray(shader->texAttrib);
> 
>     for (auto& RECT : g_pHyprOpenGL->m_RenderData.damage.getRects()) {
>         g_pHyprOpenGL->scissor(&RECT);
>         glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);
>     }
> 
>     g_pHyprOpenGL->scissor((wlr_box*)nullptr);
> 
>     glDisableVertexAttribArray(shader->posAttrib);
>     glDisableVertexAttribArray(shader->texAttrib);
> 
>     glBindTexture(tex.m_iTarget, 0);
> }
> 
> void CWindowTransformer::preWindowRender(SRenderData* pRenderData) {
>     oldPos = {(double)pRenderData->x, (double)pRenderData->y};
> 
>     pRenderData->x = pRenderData->pMonitor->vecSize.x / 2.f - pRenderData->w / 2.f;
>     pRenderData->y = pRenderData->pMonitor->vecSize.y / 2.f - pRenderData->h / 2.f;
> 
>     newPos = {(double)pRenderData->x, (double)pRenderData->y};
> }
> 
> CFramebuffer* CWindowTransformer::transform(CFramebuffer* in) {
>     static CFramebuffer off;
> 
>     if (!off.isAllocated() || off.m_vSize != in->m_vSize) {
>         off.release();
>         off.alloc(in->m_vSize.x, in->m_vSize.y);
>     }
> 
>     off.bind();
>     g_pHyprOpenGL->clear(CColor(0, 0, 0, 0));
> 
>     wlr_box monbox = {(int)(oldPos.x - newPos.x), (int)(oldPos.y - newPos.y), (int)g_pHyprOpenGL->m_RenderData.pMonitor->vecTransformedSize.x,
>                       (int)g_pHyprOpenGL->m_RenderData.pMonitor->vecTransformedSize.y};
> 
>     hsv cur{hue, 1, 1};
>     rgb col = hsv2rgb(cur);
> 
>     renderTex(monbox, in->m_cTex, rot, col);
> 
>     rot += 0.01;
>     hue += 1.29;
>     if (hue > 360) hue -= 360;
> 
>     return &off;
> }
> 
> void onNewWindow(void* self, std::any data) {
>     // data is guaranteed
>     auto* const PWINDOW = std::any_cast<CWindow*>(data);
> 
>     ptrs.push_back(static_cast<CWindowTransformer*>(PWINDOW->m_vTransformers.emplace_back(std::make_unique<CWindowTransformer>()).get()));
> }
> 
> APICALL EXPORT PLUGIN_DESCRIPTION_INFO PLUGIN_INIT(HANDLE handle) {
>     PHANDLE = handle;
> 
>     HyprlandAPI::registerCallbackDynamic(PHANDLE, "openWindow", [&](void* self, SCallbackInfo& info, std::any data) { onNewWindow(self, data); });
> 
>     HyprlandAPI::addNotification(PHANDLE, "[fun-plugin] Initialized successfully!", CColor{0.2, 1.0, 0.2, 1.0}, 5000);
> 
>     return {"fun-plugin", "fun", "Vaxry", "1.0"};
> }
> 
> APICALL EXPORT void PLUGIN_EXIT() {
>     for (auto& w : g_pCompositor->m_vWindows) {
>         std::erase_if(w->m_vTransformers, [&](const std::unique_ptr<IWindowTransformer>& other) {
>             return std::find_if(ptrs.begin(), ptrs.end(), [&](const auto& p) { return static_cast<IWindowTransformer*>(p) == other.get(); }) !=
>                    ptrs.end();
>         });
>     }
> }
> ```
> 
> Good excuse to learn to write Hyprland plugins :)

any progress? would be sick to have

**Comment by TheSunCat** [comment]
I'm having a lot of trouble staying on Hyprland due to the mouse lag issue (#3490) and lack of Unreal Engine compatibility (#2127). If these get resolved I'll be able to continue using Hyprland and implement this, but at the moment I have to use GNOME for work.

**Comment by Eclextic** [comment]
> I'm having a lot of trouble staying on Hyprland due to the mouse lag issue (#3490) and lack of Unreal Engine compatibility (#2127). If these get resolved I'll be able to continue using Hyprland and implement this, but at the moment I have to use GNOME for work.

# Unrelated/Only for GameDevs
As a GameDev I can relate lol
All major game engines still don't have any Wayland support (Godot being the earliest to probably implement it)

I recently have heard about Xwayland rootful mode (run an X11 server inside Wayland, resulting in behavior similar to a Virtual Machine)

I still haven't tried it, but maybe one can open these multi window applications inside of that...

**Comment by daUnknownCoder** [comment]
any updates on this?

**Comment by nonetrix** [comment]
Merge conflicts I would have to imagine this would need to be pretty much redone with everything that has changed since with rewrite as well

**Comment by vaxerski** [comment]
I have no plans of accepting this into core, this is better suited as a plugin

**Comment by nonetrix** [comment]
I guess their is no reason to keep this PR open then, hope someone can add it as plugin then. I personally disagree with your philosophy around plugins and what should and shouldn't be one though, this seems like feature that would make a lot of sense to be a core feature considering the focus of this project. If you want to avoid bloat, why not strip everything and make everything a plugin? Blur, animations? Why are these not plugins? Why is auto hiding a cursor not a plugin? Make everything a plugin and make base version just DWM with extra steps. I am just personally confused, seems random at best honestly. But that is just my opinion

**Comment by ThatOneCalculator** [comment]
Even though I'm no longer a Hyprland user, in all fairness, wobbly windows isn't really a core feature. I don't see more than a few dozen people legitimately daily driving this (not just enabling it once, saying "oh that's funny" and turning it off) – given the size of Hyprland as a project, keeping what has to be maintained down to a reasonable level is more than valid. Probably a ton of Hyprland users (even the majority!) use blur and animations. Wobbly windows? Not so much.

**Comment by ThatOneCalculator** [comment]
I think that's definitely a minority userbase preference, KDE and Hyprland have fairly different goals in terms of long-term development, and I think a plugin would be best for this feature. However, don't take my words as representative of @vaxerski 's opinion, especially since I'm no longer involved with the project or even a user anymore.

**Comment by TheSunCat** [comment]
Yes, this should be moved into a plugin. Perhaps I'll tackle it as I have some time this month, I'll close the MR now as there's no point keeping it open here. If I do make a plugin, I'll post a comment here linking to it for anyone still watching the MR.

**Pull request closed without merging**
