### PR TITLE
config: don't crash when getenv HOME returns null

### PR DESCRIPTION
**Pull request by PaideiaDilemma**
#### Describe your PR, what does it fix/add?

No crash when homeless.
Same as https://github.com/hyprwm/hyprlock/pull/398

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)

No.

#### Is it ready for merging, or does it need work?

Ready.

### CODE REVIEW

**Review by vaxerski — COMMENTED** [review]
should config-less be allowed? hl will be unusable without keybinds.

**Comment by fufexan** [comment]
> should config-less be allowed? hl will be unusable without keybinds.

Should simply error out and quit. I'll work on adding XDG_CONFIG_DIR support and add the config to the package(s) directly, so hl can begin looking in `/usr/share/hypr/hyprland.conf` if XDG_CONFIG_HOME is not present. Should also fix #1040.

**Comment by PaideiaDilemma** [comment]
Nice. So something like this?
If config file does not exist in `"$XDG_CONFIG_HOME"/hypr` or `"$HOME"/hypr`, search for a system config in `"$XDG_CONFIG_DIRS"/**hypr`. If that does not yield any results, only then write `AUTOCONFIG`?

Would be nice to have for hyprlock and hypridle as well for consistency.

I guess you will have to rewrite that function anyways I guess.
Just close this if you don't want this preliminary fix. Or I could make `getConfigDir` return an optional or something.

**Comment by fufexan** [comment]
> If config file does not exist in `"$XDG_CONFIG_HOME"/hypr` or `"$HOME"/hypr`, search for a system config in `"$XDG_CONFIG_DIRS"/**hypr`. If that does not yield any results, only then write `AUTOCONFIG`?

That's the plan, yes.

> Just close this if you don't want this preliminary fix.

I will merge it as it is a good step in that direction.

**Comment by fufexan** [comment]
I believe it needs a `clang format`.

**Comment by PaideiaDilemma** [comment]
Uhm check main. Code Style failure was not introduced by this change.

**Comment by PaideiaDilemma** [comment]
Clang format version specific it seems
```
[main][~/desk/Hyprland]$ clang-format --version                                      
clang-format version 17.0.6
[main][~/desk/Hyprland]$ meson --internal clangformat ./src ./build --check
[main][~/desk/Hyprland]$ echo $?
0
```
but
```
[main][~/desk/Hyprland]$ clang-format --version                            
clang-format version 18.1.8
[main][~/desk/Hyprland]$ meson --internal clangformat ./src ./build --check
src/config/ConfigDataValues.hpp:23:25: error: code should be clang-formatted [-Wclang-format-violations]
    CGradientValueData(){};
                        ^
src/config/ConfigDataValues.hpp:27:34: error: code should be clang-formatted [-Wclang-format-violations]
    virtual ~CGradientValueData(){};
                                 ^
src/config/ConfigDataValues.hpp:70:57: error: code should be clang-formatted [-Wclang-format-violations]
    CCssGapData() : top(0), right(0), bottom(0), left(0){};
                                                        ^
src/config/ConfigDataValues.hpp:71:91: error: code should be clang-formatted [-Wclang-format-violations]
    CCssGapData(int64_t global) : top(global), right(global), bottom(global), left(global){};
                                                                                          ^
src/config/ConfigDataValues.hpp:72:125: error: code should be clang-formatted [-Wclang-format-violations]
    CCssGapData(int64_t vertical, int64_t horizontal) : top(vertical), right(horizontal), bottom(vertical), left(horizontal){};
                                                                                                                            ^
src/config/ConfigDataValues.hpp:73:129: error: code should be clang-formatted [-Wclang-format-violations]
    CCssGapData(int64_t top, int64_t horizontal, int64_t bottom) : top(top), right(horizontal), bottom(bottom), left(horizontal){};
                                                                                                                                ^
src/config/ConfigDataValues.hpp:74:127: error: code should be clang-formatted [-Wclang-format-violations]
    CCssGapData(int64_t top, int64_t right, int64_t bottom, int64_t left) : top(top), right(right), bottom(bottom), left(left){};
                                                                                                                              ^
src/helpers/MiscFunctions.cpp:652:18: error: code should be clang-formatted [-Wclang-format-violations]
        CTL_KERN,
                 ^
src/helpers/MiscFunctions.cpp:653:19: error: code should be clang-formatted [-Wclang-format-violations]
        KERN_PROC,
                  ^
src/helpers/MiscFunctions.cpp:654:23: error: code should be clang-formatted [-Wclang-format-violations]
        KERN_PROC_PID,
                      ^
src/helpers/MiscFunctions.cpp:657:28: error: code should be clang-formatted [-Wclang-format-violations]
        sizeof(KINFO_PROC),
                           ^
src/macros.hpp:43:23: error: code should be clang-formatted [-Wclang-format-violations]
#define HYPRATOM(name)                                                                                                                                    
                         \
                      ^
src/macros.hpp:44:6: error: code should be clang-formatted [-Wclang-format-violations]
    { name, 0 }
     ^
src/macros.hpp:44:14: error: code should be clang-formatted [-Wclang-format-violations]
    { name, 0 }
             ^
src/managers/PointerManager.cpp:237:68: error: code should be clang-formatted [-Wclang-format-violations]
        currentCursorImage.hyprListener_destroyBuffer.initCallback(
                                                                   ^
src/managers/input/TextInput.cpp:44:51: error: code should be clang-formatted [-Wclang-format-violations]
        hyprListener_textInputEnable.initCallback(
                                                  ^
src/managers/input/TextInput.cpp:47:51: error: code should be clang-formatted [-Wclang-format-violations]
        hyprListener_textInputCommit.initCallback(
                                                  ^
src/managers/input/TextInput.cpp:50:52: error: code should be clang-formatted [-Wclang-format-violations]
        hyprListener_textInputDisable.initCallback(
                                                   ^
src/managers/input/InputManager.cpp:1627:48: error: code should be clang-formatted [-Wclang-format-violations]
    PNEWDEV->hyprListener_destroy.initCallback(
                                               ^
src/protocols/Tablet.cpp:218:42: error: code should be clang-formatted [-Wclang-format-violations]
    frameSource = wl_event_loop_add_idle(
                                         ^
src/render/Renderbuffer.cpp:61:45: error: code should be clang-formatted [-Wclang-format-violations]
    hyprListener_destroyBuffer.initCallback(
                                            ^
```

**Comment by fufexan** [comment]
Well if it's broken on main it don't matter.

**Review by fufexan — APPROVED** [review]
LGTM

**Pull request merged**
