### PR TITLE
Fix bad link in /example/hyprland.conf

### PR DESCRIPTION
**Pull request by Damianu**
#### Describe your PR, what does it fix/add?

Same as in https://github.com/hyprwm/hyprland-wiki/pull/828

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)

I was unsure if I should leave trailing slash, links below had it so I left it.

#### Is it ready for merging, or does it need work?

It's a simple almost meaningless change :)

### CODE REVIEW

**Review by vaxerski — COMMENTED** [review]
needs a change in config/defaultConfig.hpp too

**Comment by adamnejm** [comment]
README and GUIDELINES too
https://github.com/search?q=repo%3Ahyprwm%2FHyprland+https%3A%2F%2Fwiki.hyprland.org%2FConfiguring%2FConfiguring-Hyprland&type=code

**Comment by Damianu** [comment]
Okay, will update in a sec.

@adamnejm those too

**Comment by Damianu** [comment]
Well this time I cloned the repo and replaced all occurrences instead of using web editor so that should be all. Amended my commit.

**Review by vaxerski — APPROVED** [review]
lgtm thanks!

**Pull request merged**
