### PR TITLE
Use ${PREFIX} rather than /usr directly in Makefile, and force the build to attempt compilation even if the user does not have ${PREFIX}/lib write permissions

### PR DESCRIPTION
**Pull request by Froggo8311**
#### Describe your PR, what does it fix/add?
This uses PREFIX rather than installing to /usr directly, and attempts to build even if the user does not have permission to write to /usr/lib

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
I built it and it seems to work properly.

#### Is it ready for merging, or does it need work?
It is ready for review.

### CODE REVIEW

**Comment by vaxerski** [comment]
y

**Comment by primalmotion** [comment]
because $PREFIX is not always /usr ? :)

**Comment by vaxerski** [comment]
I mean yeah, but why would anyone want to install somewhere else?

**Comment by primalmotion** [comment]
some people like /usr/local. Also AUR uses a different PREFIX to perform the packaging

**Comment by vaxerski** [comment]
fair enough

**Review by vaxerski — APPROVED** [review]
el gee tee em

**Pull request merged**
