### PR TITLE
Fix incorrect rendering when manually moving a window when its being created

### PR DESCRIPTION
**Pull request by thejch**
#### Describe your PR, what does it fix/add?
ref: https://github.com/hyprwm/Hyprland/issues/5139#issuecomment-2002346554

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
No

#### Is it ready for merging, or does it need work?
Ready

### CODE REVIEW

**Review by vaxerski — COMMENTED** [review]
shouldn't we also change animation style to windowsMove in this case?

**Comment by vaxerski** [comment]
maybe make a func in CWindow as in `changeAnimationsToMove`

**Comment by thejch** [comment]
> shouldn't we also change animation style to windowsMove in this case?

The windowsMove setting doesn't seem to be doing anything right now. I tried setting it to popin and it's the same. Are you saying the func should be added to fix that? This PR is only a fix for when moving between monitors though

**Comment by vaxerski** [comment]
windowsMove is for all animations that are not open/close. AKA... move.

**Comment by thejch** [comment]
> shouldn't we also change animation style to windowsMove in this case?

As far as I can tell, windowsMove is being set, no? Did some debugging and as soon as I create a new window the [setAnimToMove](https://github.com/hyprwm/Hyprland/blob/4ffcdc41ff8233a92f02c633475ac3472b0998df/src/events/Windows.cpp#L33) gets called from [here](https://github.com/hyprwm/Hyprland/blob/4ffcdc41ff8233a92f02c633475ac3472b0998df/src/events/Windows.cpp#L613)

**Comment by vaxerski** [comment]
if you use popin it won't be, only on the end of the animation.

**Comment by thejch** [comment]
> if you use popin it won't be, only on the end of the animation.

I see what you mean now. I'll add that stuff in a minute

**Comment by thejch** [comment]
> shouldn't we also change animation style to windowsMove in this case?

Added

**Review by vaxerski — APPROVED** [review]

**Pull request merged**
