### PR TITLE
Move CMonitor to SP

### PR DESCRIPTION
**Pull request by vaxerski**
#6475 this time it should work tho

needs testing

cc @fufexan @Honkazel

### CODE REVIEW

**Comment by Ciel-MC** [comment]
Launched, didn't crash. Will continue normal usage

**Comment by VirtCode** [comment]
Crashing for me when trying to capture screen with OBS. Here's a bt I captured with gdb:
```
#0  0x00005863cea2e146 in std::_Tuple_impl<0ul, CCompositor*, std::default_delete<CCompositor> >::_M_head (__t=...) at /usr/include/c++/14.2.1/tuple:296
#1  0x00005863cea2e131 in std::__get_helper<0ul, CCompositor*, std::default_delete<CCompositor> > (__t=...) at /usr/include/c++/14.2.1/tuple:2433
#2  0x00005863cea2e117 in std::get<0ul, CCompositor*, std::default_delete<CCompositor> > (__t=std::tuple containing = {...}) at /usr/include/c++/14.2.1/tuple:2450
#3  0x00005863cea2e0da in std::__uniq_ptr_impl<CCompositor, std::default_delete<CCompositor> >::_M_ptr (this=0x5863d0d38cd0 <g_pCompositor>) at /usr/include/c++/14.2.1/bits/unique_ptr.h:193
#4  0x00005863cea2e0c0 in std::unique_ptr<CCompositor, std::default_delete<CCompositor> >::get (this=0x5863d0d38cd0 <g_pCompositor>) at /usr/include/c++/14.2.1/bits/unique_ptr.h:464
#5  0x00005863cea2e0a6 in std::unique_ptr<CCompositor, std::default_delete<CCompositor> >::operator-> (this=0x5863d0d38cd0 <g_pCompositor>) at /usr/include/c++/14.2.1/bits/unique_ptr.h:457
#6  0x00005863cf03822f in CPointerManager::lockSoftwareForMonitor (this=0x5120000091c0, Monitor=...) at /home/joshua/Project/hypr/Hyprland/src/managers/PointerManager.cpp:55
#7  0x00005863cf03835a in CPointerManager::lockSoftwareForMonitor (this=0x5120000091c0, Monitor=...) at /home/joshua/Project/hypr/Hyprland/src/managers/PointerManager.cpp:57
#8  0x00005863cf03835a in CPointerManager::lockSoftwareForMonitor (this=0x5120000091c0, Monitor=...) at /home/joshua/Project/hypr/Hyprland/src/managers/PointerManager.cpp:57
#9  0x00005863cf03835a in CPointerManager::lockSoftwareForMonitor (this=0x5120000091c0, Monitor=...) at /home/joshua/Project/hypr/Hyprland/src/managers/PointerManager.cpp:57
#10 0x00005863cf03835a in CPointerManager::lockSoftwareForMonitor (this=0x5120000091c0, Monitor=...) at /home/joshua/Project/hypr/Hyprland/src/managers/PointerManager.cpp:57
#11 0x00005863cf03835a in CPointerManager::lockSoftwareForMonitor (this=0x5120000091c0, Monitor=...) at /home/joshua/Project/hypr/Hyprland/src/managers/PointerManager.cpp:57
#12 0x00005863cf03835a in CPointerManager::lockSoftwareForMonitor (this=0x5120000091c0, Monitor=...) at /home/joshua/Project/hypr/Hyprland/src/managers/PointerManager.cpp:57
#13 0x00005863cf03835a in CPointerManager::lockSoftwareForMonitor (this=0x5120000091c0, Monitor=...) at /home/joshua/Project/hypr/Hyprland/src/managers/PointerManager.cpp:57
#14 0x00005863cf03835a in CPointerManager::lockSoftwareForMonitor (this=0x5120000091c0, Monitor=...) at /home/joshua/Project/hypr/Hyprland/src/managers/PointerManager.cpp:57
#15 0x00005863cf03835a in CPointerManager::lockSoftwareForMonitor (this=0x5120000091c0, Monitor=...) at /home/joshua/Project/hypr/Hyprland/src/managers/PointerManager.cpp:57
#16 0x00005863cf03835a in CPointerManager::lockSoftwareForMonitor (this=0x5120000091c0, Monitor=...) at /home/joshua/Project/hypr/Hyprland/src/managers/PointerManager.cpp:57
#17 0x00005863cf03835a in CPointerManager::lockSoftwareForMonitor (this=0x5120000091c0, Monitor=...) at /home/joshua/Project/hypr/Hyprland/src/managers/PointerManager.cpp:57
#18 0x00005863cf03835a in CPointerManager::lockSoftwareForMonitor (this=0x5120000091c0, Monitor=...) at /home/joshua/Project/hypr/Hyprland/src/managers/PointerManager.cpp:57
#19 0x00005863cf03835a in CPointerManager::lockSoftwareForMonitor (this=0x5120000091c0, Monitor=...) at /home/joshua/Project/hypr/Hyprland/src/managers/PointerManager.cpp:57
```

Interestingly, the last line of the bt seems to repeat seemingly forever, so I don't know whether something else is wrong with this bt.

**Comment by Honkazel** [comment]
image

Huh?

**Comment by Xanazf** [comment]
looks good so far

**Comment by vaxerski** [comment]
image
me when the oops

**Comment by vaxerski** [comment]
fixed

**Comment by vaxerski** [comment]
anything els

**Comment by Agent00Ming** [comment]
there might be a direct scanout related crash. getting a stack trace

**Comment by vaxerski** [comment]
unrelated to this, mergin, thanks ppl

**Pull request merged**
