### PR TITLE
pointer-constraints: keep constraint alive until actual destruction

### PR DESCRIPTION
**Pull request by Trimutex**
#### Describe your PR, what does it fix/add?
Current constraint deactivation kills the constraint even if it tries to reactivate due to lifetime check always being true. Removing this fixes refocusing of windows not actually restarting constraint, requiring a recreation of the constraints by the program.
- Ex: Minecraft will not recreate constraint until menu is opened in game, so swapping to another window and back rapidly will kill the constraint without recreation, leaving pointer to roam free.

Possible fix for #5900 but can not recreate issue myself to test.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
No problems with usage as proper destruction gets called anyways later when actually necessary. Perhaps a better option is to change the default lifetime of the pointer constraint, but I'm not too knowledgeable the implications of that.

#### Is it ready for merging, or does it need work?
Ready for merging

### CODE REVIEW

**Comment by vaxerski** [comment]
tag me when ready

**Comment by Trimutex** [comment]
@vaxerski should already be ready? this still fixes the Minecraft example already. Sorry if I didn't make that clear

**Comment by vaxerski** [comment]
why not just set the properties in the appropriate constructors like I've obviously forgotten to? xD

**Comment by vaxerski** [comment]
should be fixed.

**Comment by Trimutex** [comment]
because I missed it too lol. this does fix it properly, thanks!

**Pull request closed without merging**
