### PR TITLE
Nix: add hwdata overlay

### PR DESCRIPTION
**Pull request by fufexan**
#### Describe your PR, what does it fix/add?
Fixes CI

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
Hope it builds cuz I ain't building systemd and all that myself.

#### Is it ready for merging, or does it need work?
See above.

### CODE REVIEW

**Comment by vaxerski** [comment]
why tf is it building for >30 mins

**Comment by fufexan** [comment]
@vaxerski cuz I pulled the hwdata file from a PR which has to rebuild this many packages.
image

**Comment by vaxerski** [comment]
why tf

nix???

**Comment by fufexan** [comment]
Because it's so low-level and so many packages depend on it, they have to be rebuilt along with anything that depends on them... and so on.

**Comment by vaxerski** [comment]
when will it be merged into nix so we can avoid this ordeal?

**Comment by fufexan** [comment]
image
knowing how staging works, it'll be in unstable in max 2 weeks.

**Comment by fufexan** [comment]
Rest assured tho, the rebuild won't take this long everytime. This first run will be cached in Cachix and pulled on subsequent builds.

**Comment by vaxerski** [comment]
k

**Pull request merged**
