### PR TITLE
meson: add man pages

### PR DESCRIPTION
**Pull request by viperML**
#### Describe your PR, what does it fix/add?

Adds the manpages to be built with meson.

**Disabled by default**, enabled for the nix builds.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)

Maybe pandoc is too fat, and it would be nice to use a different program.

Also pinging for second look:
- @volitank implemented man pages in #379 
- @sp1ritCS wrote the meson files

#### Is it ready for merging, or does it need work?

If CI succeeds

### CODE REVIEW

**Comment by vaxerski** [comment]
yeah using something that isnt as fat, and additionally doesnt depend on 400MB of shit would be nice.

**Comment by viperML** [comment]
Not that much
```
$ nix path-info -sh (nix build --no-link --print-out-paths --inputs-from github:hyprwm/Hyprland nixpkgs#pandoc)
/nix/store/i56xxnck0qjpqpaafk7x30vy0lwyf17d-pandoc-2.17.1.1      167.8M
```

But I will check for alternatives

**Review by fufexan — APPROVED** [review]
LGTM, waiting for the other reviews.

**Comment by sp1ritCS** [comment]
since you are not using the normal `install_man` function and instead use the `install_dir` arg of `custom_target`, you'll want to add `install_tag: 'man'` arg to your taget too.

See https://mesonbuild.com/Installing.html#installation-tags

**Comment by viperML** [comment]
python-docutils seems nice, but produces bad formatting. And I have no idea about RST to fix it

**Comment by volitank** [comment]
@viperML python-docutils is what I originally wrote the man pages for, but we didn't want to depend on python.

If it's decided that we want to go this route then I can change the formatting. It should be in the PR how the formatting should be.

Alternatively to keep them light we could use them how they are with pandoc, and have the converted groff version as well, and that one would actually be used during build time, and only run pandoc when they need updating. Just a thought though, this way would require no extra dependencies during build time.

**Comment by viperML** [comment]
> but we didn't want to depend on python

`docutils` is certainly smaller, at just 3M. It depends on python, but the user probably already has python installed (and it is a runtime dependency of meson....)

```
% nix path-info -shr $(nix build --no-link --print-out-paths --inputs-from github:hyprwm/Hyprland nixpkgs#docutils) | tail -n2
/nix/store/rc9cz7z4qlgmsbwvpw2acig5g2rdws46-python3-3.10.5                82.5M
/nix/store/ncnx31fvf8bvy6rfbkl2amhxrrv112wh-python3.10-docutils-0.19       3.2M
```

**Comment by epsilon-0** [comment]
It is possible to just write the man pages in mdoc language (which is an extremely simplified version of the man language). This way there is no dependency on anything to _build_ man pages, they are straight usable by just copying.

The wf-recorder and some other wayfire utilities use this format - https://github.com/ammen99/wf-recorder/blob/master/manpage/wf-recorder.1

I can volunteer to do the change if you think it's a good idea.

**Comment by vaxerski** [comment]
that looks ugly af lol

but I guess it wouldn't be THAT bad of an idea, no?

**Comment by viperML** [comment]
I'd rather have the man pages pre-compiled on repo, and have a github action watch for changes in the man sources to compile them to a commit

**Comment by vaxerski** [comment]
fair solution as well

**Comment by epsilon-0** [comment]
> that looks ugly af lol
> 
> but I guess it wouldn't be THAT bad of an idea, no?

LOL, yea, they take a bit of getting used too the first time. I've kind of become used to writing them, they're quite a lot like latex.



> I'd rather have the man pages pre-compiled on repo, and have a github action watch for changes in the man sources to compile them to a commit

This would be the next best solution.

**Pull request closed without merging**
