### PR TITLE
Add a fit-for-purpose code of conduct

### PR DESCRIPTION
**Pull request by powermoneyfame**
It is clear now that everyone agrees a code of conduct is absolutely necessary to protect minorities from harms within this community. However, one must notice that the code of conduct suggested in #3366 seems to only seek to protect specific, popular interests deemed necessary to "put out the fire." The purpose of a code of conduct should be to protect those vulnerable and empower everyone to participate in the community, not to tick boxes. My code of conduct ensures that ALL relevant harms are dealt with, not the minimum number necessary to please a blogger.

Please keep discussion about the PR, if you want to debate philosophy do it without silencing the voice of minorities.

### CODE REVIEW

**Comment by vaxerski** [comment]
with all due respect, your CoC is grotesque. About half or even more of the clauses are pointless, and the other half would be included in the original CoC's 3 sentences.

All of that even ignoring the fact your CoC is contradicting itself, is not even enforcable, and many other issues.

> My code of conduct ensures that ALL relevant harms are dealt with

laughable statement

> if you want to debate philosophy do it without silencing the voice of minorities.

??

**Comment by vaxerski** [comment]
Examples regarding pointlessness / impossible enforcement:

> Historical Context

We're not history teachers.

> Prioritize the holistic well-being of community members.

We prioritize code, not your well-being. This is not a mental support center.

> Anti-Colonial Practices

Again, we're not history teachers, nor do those topics belong in a _wayland compositor's github repo_ anyways.

> Maintain scientific rigor and intellectual honesty in discussions related to research or technical topics.

This is not a university.

> Recognize and address economic disparities

I am not a government giving grants

> Encourage and support educational initiatives within our community

Again, this is not a university.

Re: Anything with "strive to create opportunities for all members"

We do not strive to create opportunities. This is not a talent seeker show. We accept contributions. Nobody should go out of their way to specifically search and give opportunities to people. We provide a level playing ground for whoever wants to participate.

How does your CoC contradict itself? Simple. It's not accessible, yet you claim it should be. ("Accessibility and Accommodation")

I am surprised you are not able to see those issues yourself.

Safe to say this will not be merged.

**Comment by NordGeit** [comment]
> I'm _so_ hoping this is satirical.
The worst part is that there's a piece within me that doubts this is a jest... I've seen how demanding people can be...

**Comment by fufexan** [comment]
With all due respect, I ain't reading all that.

**Comment by NordGeit** [comment]
> I'm sorry if you thought my suggestion was demanding, that was not my intention. I am aware of the patronizing tone of many around this topic, like Drew's post, and I want to avoid it.

I didn't even read it, I just read the replies, and I could _tell_ that this is incredibly demanding and most of all, unsustainable, and would add immense overhead as extra energy and resources is spent trying to follow it, which is not very environmentally friendly...
Those joules and kilobytes of drive space is better spent elsewhere.
As a supporter of `SHUT UP WE COOOODE`, an environmentally friendly alternative that very heavily discourages non-technical discussion not pertaining to the software in question, I strongly stand against your suggestion.
While it does cost extra energy to uphold in comparison to no CoC, the energy costs are way less counting the joules, than a CoC like yours.
I believe in these times of need we need to take care of the environment around us. And that means eliminating as many distractions as possible when working with software development, even if it costs extra energy on each person to exercise restraint.

**Comment by fufexan** [comment]
That's not what this is. Abiding to the current CoC should not pose any problems to anyone, including marginalized folks. We do not need a wall of text to look at every time we want to speak.

**Comment by NotAShelf** [comment]
Even though I have a hard time believing this PR is genuine, I am going to assume your good faith and speak accordingly.

I think you are striving towards many positive values, which is good, great even but with *so little thought* that it appears disingenuine or even satirical. There are many software communities on the internet, some backed by much more powerful organization and even governments. If you are willing to make the aforementioned changes, reach out those software creators and try to get them to make a move. So little of what you have asked for is within the scope of Hyprland organiztion  (yet so much of that little is already covered by the now implemented Code of Conduct) but I'm sure you can find a place where your ideas are fitting. This proposal is, and excuse me for being crass, **piss poor** at what it's meant to do: ensure a civil community space that nobody is afraid to speak up. 

I suggest you review your words carefully (this includes your comments because you lost me within seconds with your first reply) and maybe take this proposal to somewhere else.

Should you be trolling with this entire post (which is equally, if not more likely, than that you are genuine), well, you know where that somewhere else is.

**Comment by fufexan** [comment]
Ok. If you ever have a problem in the community, please signal it.

**Comment by vaxerski** [comment]
> I place no value on your perspective after your earlier comments, to be clear.

aaand you break your own CoC.

At any rate, there is no point in further discussion, it's pretty clear this will not be merged and the discussion is just collectively wasting time of both us and you.

**Comment by vaxerski** [comment]
great, your choice.

**Comment by Lenny5125** [comment]
Window managers in 2033 are going to require me to pass a history exam to start using it.

**Pull request closed without merging**
