### PR TITLE
move screencopy and toplevel export to hyprwayland-scanner

### PR DESCRIPTION
**Pull request by ikalco**
#### Describe your PR, what does it fix/add?
moves the screencopy and toplevel export protocol impls to hyprwayland scanner

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
i can split screencopy and toplevel into different PRs if you want cause this is pretty big

#### Is it ready for merging, or does it need work?
yes

### CODE REVIEW

**Comment by ikalco** [comment]
btw I saw high mem usage in this pr but i realized it was from last commit
forgot to free the surface after texturing it

```diff
diff --git a/src/render/OpenGL.cpp b/src/render/OpenGL.cpp
index 5e52403d..39f6614e 100644
--- a/src/render/OpenGL.cpp
+++ b/src/render/OpenGL.cpp
@@ -2610,6 +2610,8 @@ void CHyprOpenGLImpl::createBackgroundTexture(const std::string& texPath) {
     }
 #endif
     glTexImage2D(GL_TEXTURE_2D, 0, glIFormat, m_pBackgroundTexture->m_vSize.x, m_pBackgroundTexture->m_vSize.y, 0, glFormat, glType, DATA);
+
+    cairo_surface_destroy(CAIROSURFACE);
 }
 
 void CHyprOpenGLImpl::createBGTextureForMonitor(CMonitor* pMonitor) {
```

**Comment by vaxerski** [comment]
lelo thanks will commit that one

**Review by vaxerski — COMMENTED** [review]
I do not have the capacity to test this atm, can you test @fufexan ?

Code looks alr at a glance

**Comment by fufexan** [comment]
Idk what I'm supposed to test tbh. Works normally to me.

**Comment by vaxerski** [comment]
whether sharing works (window, screen, region)

**Comment by fufexan** [comment]
Yeah all working fine.

**Comment by vaxerski** [comment]
thanks

**Pull request merged**
