### PR TITLE
makes active windoe consistient with client json

### PR DESCRIPTION
**Pull request by yavko**
#### Describe your PR, what does it fix/add?
Basically i forgot to apply the changes I made to the active window json (changing the int to bool)

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
no

#### Is it ready for merging, or does it need work?
probably, no real testing, i just copy pasted

### CODE REVIEW

**Comment by vaxerski** [comment]
zjsowwh

**Comment by yavko** [comment]
@vaxerski unmerge its broken

**Comment by vaxerski** [comment]
asshole

**Comment by yavko** [comment]
> asshole

i fixed it in a new commit

**Comment by vaxerski** [comment]
make a new pr

**Comment by yavko** [comment]
okay

**Pull request merged**
