### PR TITLE
Wayland Protocol impl improvements

### PR DESCRIPTION
**Pull request by vaxerski**
Stuff to ease development down the line

more might come

cc @TheSunCat he always seems to be crashing 
cc @fufexan for review

### CODE REVIEW

**Comment by TheSunCat** [comment]
Crashing randomly on window close with this patch applied.

Crash report:
```ini
[apm@apg ~]$ cat .cache/hyprland/hyprlandCrashReport7001.txt 
--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
Vaxry is going to be upset.

Hyprland received signal 6 (Aborted)

Version: 126792584fa4eb25f6c8e3b3eb6bfb00b58a787a
Tag: v0.28.0-28-g12679258

System info:
	System name: Linux
	Node name: apg
	Release: 6.4.8-201.fsync.fc38.x86_64
	Version: #1 SMP PREEMPT_DYNAMIC Sat Aug  5 23:34:20 UTC 2023

GPU:
	03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6650 XT / 6700S / 6800S] [1002:73ef] (rev c2) (prog-if 00 [VGA controller])
37:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev c7) (prog-if 00 [VGA controller])


os-release:
	NAME="Arch Linux"
	PRETTY_NAME="Arch Linux"
	ID=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://archlinux.org/"
	DOCUMENTATION_URL="https://wiki.archlinux.org/"
	SUPPORT_URL="https://bbs.archlinux.org/"
	BUG_REPORT_URL="https://bugs.archlinux.org/"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=archlinux-logo
	


Backtrace:
	#0 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x75e) [0x5580798c909e]
		??
		??:0
	#1 | Hyprland(_Z25handleUnrecoverableSignali+0x3c) [0x55807986143c]
		??
		??:0
	#2 | /usr/lib/libc.so.6(+0x3e710) [0x7f6c7d83e710]
		??
		??:0
	#3 | /usr/lib/libc.so.6(+0x8e83c) [0x7f6c7d88e83c]
		??
		??:0
	#4 | /usr/lib/libc.so.6(raise+0x18) [0x7f6c7d83e668]
		??
		??:0
	#5 | /usr/lib/libc.so.6(abort+0xd7) [0x7f6c7d8264b8]
		??
		??:0
	#6 | /usr/lib/libc.so.6(+0x27390) [0x7f6c7d827390]
		??
		??:0
	#7 | /usr/lib/libc.so.6(+0x987b7) [0x7f6c7d8987b7]
		??
		??:0
	#8 | /usr/lib/libc.so.6(+0x9a66e) [0x7f6c7d89a66e]
		??
		??:0
	#9 | /usr/lib/libc.so.6(free+0x73) [0x7f6c7d89d7b3]
		??
		??:0
	#10 | Hyprland(+0x1b960e) [0x55807997860e]
		??
		??:0
	#11 | Hyprland(+0x1b9810) [0x558079978810]
		??
		??:0
	#12 | /usr/lib/libffi.so.8(+0x74f6) [0x7f6c7d5364f6]
		??
		??:0
	#13 | /usr/lib/libffi.so.8(+0x3f5e) [0x7f6c7d532f5e]
		??
		??:0
	#14 | /usr/lib/libffi.so.8(ffi_call+0x123) [0x7f6c7d535b73]
		??
		??:0
	#15 | /usr/lib/libwayland-server.so.0(+0x8ada) [0x7f6c7e63dada]
		??
		??:0
	#16 | /usr/lib/libwayland-server.so.0(+0xd180) [0x7f6c7e642180]
		??
		??:0
	#17 | /usr/lib/libwayland-server.so.0(wl_event_loop_dispatch+0xa2) [0x7f6c7e640ae2]
		??
		??:0
	#18 | /usr/lib/libwayland-server.so.0(wl_display_run+0x27) [0x7f6c7e6412d7]
		??
		??:0
	#19 | Hyprland(main+0xa91) [0x558079851461]
		??
		??:0
	#20 | /usr/lib/libc.so.6(+0x27cd0) [0x7f6c7d827cd0]
		??
		??:0
	#21 | /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7f6c7d827d8a]
		??
		??:0
	#22 | Hyprland(_start+0x25) [0x5580798612e5]
		??
		??:0


Log tail:
[LOG] Window got assigned a surfaceTreeNode 0
[LOG] Registered signal for owner 55807b3ddd80: 55807b3dd5c0 -> 55807b3ddd80 (owner: XDG Window Late)
[LOG] Registered signal for owner 55807b3ddd80: 55807b3ddc30 -> 55807b3ddf20 (owner: XDG Window Late)
[LOG] Registered signal for owner 55807b3ddd80: 55807b3dd800 -> 55807b3de058 (owner: XDG Window Late)
[LOG] Registered signal for owner 55807b3ddd80: 55807b3ddbc0 -> 55807b3de190 (owner: XDG Window Late)
[LOG] Registered signal for owner 55807b3ddd80: 55807b3ddbe0 -> 55807b3de128 (owner: XDG Window Late)
[LOG] Registered signal for owner 55807b3ddd80: 55807b3ddbf0 -> 55807b3de0c0 (owner: XDG Window Late)
[LOG] Registered signal for owner 55807b3ddd80: 55807b3ddc00 -> 55807b3de1f8 (owner: XDG Window Late)
[LOG] Registered signal for owner 55807b3ddd80: 55807b3ddbd0 -> 55807b3ddff0 (owner: XDG Window Late)
[LOG] Registered signal for owner 55807af564e0: 55807b3dd5f0 -> 55807af56558 (owner: SurfaceTreeNode)
[LOG] Registered signal for owner 55807af564e0: 55807b3dd5c0 -> 55807af565c0 (owner: SurfaceTreeNode)
[LOG] Registered signal for owner 55807af564e0: 55807b3dd600 -> 55807af56628 (owner: SurfaceTreeNode)
[LOG] Added a new subsurface 55807b3df690
[LOG] Registered signal for owner 55807b3c3450: 55807b3df530 -> 55807b3c3468 (owner: Subsurface)
[LOG] Registered signal for owner 55807b3c3450: 55807b3df540 -> 55807b3c34d0 (owner: Subsurface)
[LOG] Registered signal for owner 55807b3c3450: 55807b3df710 -> 55807b3c3538 (owner: Subsurface)
[LOG] Creating a surfaceTree Root! (pWindow: 55807b3ddd80)
[LOG] Map request dispatched, monitor eDP-2, xywh: 1030.000000 68.000000 1011.000000 1205.000000
[LOG] Keybind triggered, calling dispatcher (64, , 120)
[LOG] Window 55807b3ddd80 unmapped (class foot)
[LOG] Unregistered late callbacks XDG
[LOG] Callback 55807b3ddda8 -> 55807b3ddda0, XDG Window Late removed.
[LOG] Callback 55807b3ddf48 -> 55807b3ddf40, XDG Window Late removed.
[LOG] Callback 55807b3de080 -> 55807b3de078, XDG Window Late removed.
[LOG] Callback 55807b3de1b8 -> 55807b3de1b0, XDG Window Late removed.
[LOG] Callback 55807b3de150 -> 55807b3de148, XDG Window Late removed.
[LOG] Callback 55807b3de0e8 -> 55807b3de0e0, XDG Window Late removed.
[LOG] Callback 55807b3de220 -> 55807b3de218, XDG Window Late removed.
[LOG] Callback 55807b3de018 -> 55807b3de010, XDG Window Late removed.
[LOG] Framebuffer created, status 36053
[LOG] On closed window, new focused candidate is 55807b3d5e60
[LOG] Set keyboard focus to surface 55807b3bf6c0, with window name: foot
[LOG] Destroying the SubSurface tree of unmapped window 55807b3ddd80
[LOG] Callback 55807b3c3560 -> 55807b3c3558, Subsurface removed.
[LOG] Callback 55807b3c3490 -> 55807b3c3488, Subsurface removed.
[LOG] Callback 55807b3c34f8 -> 55807b3c34f0, Subsurface removed.
[LOG] Callback 55807af565e8 -> 55807af565e0, SurfaceTreeNode removed.
[LOG] Callback 55807af56650 -> 55807af56648, SurfaceTreeNode removed.
[LOG] Callback 55807af56580 -> 55807af56578, SurfaceTreeNode removed.
[LOG] SurfaceTree Node removed
[LOG] Callback 55807b3de3c0 -> 55807b3de3b8, Toplevel removed.
[LOG] Callback 55807b3de358 -> 55807b3de350, Toplevel removed.
[LOG] Callback 55807b3de428 -> 55807b3de420, Toplevel removed.
[LOG] Callback 55807b3de5d0 -> 55807b3de5c8, CWLSurface removed.
[LOG] CWLSurface 55807b3de5a0 called destroy()
[LOG] Callback 55807b3dde78 -> 55807b3dde70, CWindow removed.
[LOG] Window 55807b3ddd80 destroyed, queueing. (class )
[LOG] Callback 55807b3dde10 -> 55807b3dde08, XDG Window removed.
[LOG] Callback 55807b3ddee0 -> 55807b3dded8, XDG Window removed.
[ERR] onWindowRemovedTiling node null?
```

**Review by fufexan — APPROVED** [review]

**Comment by vaxerski** [comment]
@TheSunCat check now, doesnt seem to crash for me anymore

**Comment by TheSunCat** [comment]
The peck, building this caused Hyprland to crash. *Building this*.
But hey after building it from tty it doesn't seem to crash!

**Comment by vaxerski** [comment]
ready to review & merge 

cc @fufexan for code
cc @TheSunCat for crash testing

**Review by fufexan — DISMISSED** [review]

**Comment by TheSunCat** [comment]
we crashin my man
```ini
--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
This was an accident, I swear!

Hyprland received signal 11 (Segmentation fault)

Version: 3f7f4207a6dd8bd217c01514ea40e9e4b9b7874a
Tag: v0.28.0-34-g3f7f4207

System info:
	System name: Linux
	Node name: apg
	Release: 6.4.8-201.fsync.fc38.x86_64
	Version: #1 SMP PREEMPT_DYNAMIC Sat Aug  5 23:34:20 UTC 2023

GPU:
	03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6650 XT / 6700S / 6800S] [1002:73ef] (rev c2) (prog-if 00 [VGA controller])
37:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev c7) (prog-if 00 [VGA controller])


os-release:
	NAME="Arch Linux"
	PRETTY_NAME="Arch Linux"
	ID=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://archlinux.org/"
	DOCUMENTATION_URL="https://wiki.archlinux.org/"
	SUPPORT_URL="https://bbs.archlinux.org/"
	BUG_REPORT_URL="https://bugs.archlinux.org/"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=archlinux-logo
	


Backtrace:
	#0 | Hyprland(_Z12getBacktracev+0x48) [0x55ffc69c2c78]
		??
		??:0
	#1 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x76e) [0x55ffc6992a6e]
		??
		??:0
	#2 | Hyprland(_Z25handleUnrecoverableSignali+0x3c) [0x55ffc692a50c]
		??
		??:0
	#3 | /usr/lib/libc.so.6(+0x3e710) [0x7fb9ffe3e710]
		??
		??:0
	#4 | /usr/lib/libwayland-server.so.0(wl_resource_post_event+0xab) [0x7fba00b3cdab]
		??
		??:0
	#5 | Hyprland(_ZN18CXDGOutputProtocol19updateOutputDetailsEP10SXDGOutput+0x68) [0x55ffc6a42e28]
		??
		??:0
	#6 | Hyprland(+0x1bc58b) [0x55ffc6a4358b]
		??
		??:0
	#7 | Hyprland(_ZN18CHookSystemManager4emitEPKSt6vectorI14SCallbackFNPtrSaIS1_EESt3any+0x2e0) [0x55ffc69f5cd0]
		??
		??:0
	#8 | Hyprland(_ZN14CConfigManager20performMonitorReloadEv+0x245) [0x55ffc696c225]
		??
		??:0
	#9 | Hyprland(_ZN13CHyprRenderer13renderMonitorEP8CMonitor+0xf35) [0x55ffc6a5c425]
		??
		??:0
	#10 | Hyprland(_Z13handleWrappedP11wl_listenerPv+0x3c) [0x55ffc69d187c]
		??
		??:0
	#11 | /usr/lib/libwayland-server.so.0(wl_signal_emit_mutable+0x7e) [0x7fba00b3c01e]
		??
		??:0
	#12 | /home/apm/Hyprland/subprojects/wlroots/build/libwlroots.so.12032(+0x57fa8) [0x7fba00bdcfa8]
		??
		??:0
	#13 | /usr/lib/libdrm.so.2(drmHandleEvent+0xff) [0x7fba00b0b9af]
		??
		??:0
	#14 | /home/apm/Hyprland/subprojects/wlroots/build/libwlroots.so.12032(+0x5a519) [0x7fba00bdf519]
		??
		??:0
	#15 | /usr/lib/libwayland-server.so.0(wl_event_loop_dispatch+0xa2) [0x7fba00b3dae2]
		??
		??:0
	#16 | /usr/lib/libwayland-server.so.0(wl_display_run+0x27) [0x7fba00b3e2d7]
		??
		??:0
	#17 | Hyprland(main+0xa91) [0x55ffc691a531]
		??
		??:0
	#18 | /usr/lib/libc.so.6(+0x27cd0) [0x7fb9ffe27cd0]
		??
		??:0
	#19 | /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7fb9ffe27d8a]
		??
		??:0
	#20 | Hyprland(_start+0x25) [0x55ffc692a3b5]
		??
		??:0


Log tail:
[LOG] Callback 55ffc90615f0 -> 55ffc90615e8, SurfaceTreeNode removed.
[LOG] Callback 55ffc9061520 -> 55ffc9061518, SurfaceTreeNode removed.
[LOG] SurfaceTree Node removed
[LOG] Callback 55ffc906c420 -> 55ffc906c418, Toplevel removed.
[LOG] Callback 55ffc906c3b8 -> 55ffc906c3b0, Toplevel removed.
[LOG] Callback 55ffc906c488 -> 55ffc906c480, Toplevel removed.
[LOG] Callback 55ffc906c630 -> 55ffc906c628, CWLSurface removed.
[LOG] CWLSurface 55ffc906c600 called destroy()
[LOG] Callback 55ffc906bed8 -> 55ffc906bed0, CWindow removed.
[LOG] Window 55ffc906bde0 destroyed, queueing. (class )
[LOG] Callback 55ffc906be70 -> 55ffc906be68, XDG Window removed.
[LOG] Callback 55ffc906bf40 -> 55ffc906bf38, XDG Window removed.
[ERR] onWindowRemovedTiling node null?
[LOG] Registered signal for owner 55ffc904e120: 55ffc9062090 -> 55ffc904e300 (owner: layerSurface)
[LOG] Registered signal for owner 55ffc904e120: 55ffc9092850 -> 55ffc904e1c8 (owner: layerSurface)
[LOG] Registered signal for owner 55ffc904e120: 55ffc90620a0 -> 55ffc904e230 (owner: layerSurface)
[LOG] Registered signal for owner 55ffc904e120: 55ffc90620b0 -> 55ffc904e298 (owner: layerSurface)
[LOG] Registered signal for owner 55ffc904e120: 55ffc9092860 -> 55ffc904e368 (owner: layerSurface)
[LOG] LayerSurface 55ffc9092790 (namespace gtk-layer-shell layer 2) created on monitor eDP-2
[LOG] LayerSurface 55ffc8d5e150 arranged: x: 0 y: 0 w: 2048 h: 1280 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] LayerSurface 55ffc9043630 arranged: x: -1 y: 0 w: 2050 h: 69 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] Monitor eDP-2 layers arranged: reserved: 0.000000 0.000000 0.000000 0.000000
[LOG] Socket 2 accepted a new client at FD 89
[LOG] Socket 2 accepted a new client at FD 145
[LOG] Socket 2 accepted a new client at FD 153
[LOG] Socket 2 accepted a new client at FD 155
[LOG] LayerSurface 55ffc9092790 mapped
[LOG] Registered signal for owner 55ffc904e140: 55ffc90620d0 -> 55ffc904e148 (owner: CWLSurface)
[LOG] CWLSurface 55ffc904e140 called init()
[LOG] LayerSurface 55ffc8d5e150 arranged: x: 0 y: 0 w: 2048 h: 1280 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] LayerSurface 55ffc9043630 arranged: x: -1 y: 0 w: 2050 h: 69 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] Monitor eDP-2 layers arranged: reserved: 0.000000 0.000000 0.000000 0.000000
[LOG] Socket 2 accepted a new client at FD 157
[LOG] Registered signal for owner 55ffc90692e0: 55ffc9068390 -> 55ffc90694c0 (owner: layerSurface)
[LOG] Registered signal for owner 55ffc90692e0: 55ffc904dcc0 -> 55ffc9069388 (owner: layerSurface)
[LOG] Registered signal for owner 55ffc90692e0: 55ffc90683a0 -> 55ffc90693f0 (owner: layerSurface)
[LOG] Registered signal for owner 55ffc90692e0: 55ffc90683b0 -> 55ffc9069458 (owner: layerSurface)
[LOG] Registered signal for owner 55ffc90692e0: 55ffc904dcd0 -> 55ffc9069528 (owner: layerSurface)
[LOG] LayerSurface 55ffc904dc00 (namespace gtk-layer-shell layer 3) created on monitor eDP-2
[LOG] LayerSurface 55ffc8d5e150 arranged: x: 0 y: 0 w: 2048 h: 1280 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] LayerSurface 55ffc9043630 arranged: x: -1 y: 0 w: 2050 h: 69 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] LayerSurface 55ffc9040920 arranged: x: -1 y: 1279 w: 2050 h: 1 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] Monitor eDP-2 layers arranged: reserved: 0.000000 0.000000 0.000000 0.000000
[LOG] Hyprctl: keyword monitor : eDP-2,addreserved,61,0,0,0
[LOG] Applying monitor rule for eDP-2
[LOG] Not applying a new rule to eDP-2 because it's already applied!
[LOG] LayerSurface 55ffc8d5e150 arranged: x: 0 y: 0 w: 2048 h: 1280 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] LayerSurface 55ffc9043630 arranged: x: -1 y: 0 w: 2050 h: 69 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] LayerSurface 55ffc9040920 arranged: x: -1 y: 1279 w: 2050 h: 1 with margins: t: 0 l: 0 r: 0 b: 0
[LOG] Monitor eDP-2 layers arranged: reserved: 0.000000 61.000000 0.000000 0.000000

```

**Comment by vaxerski** [comment]
try now @TheSunCat

**Comment by TheSunCat** [comment]
Not crashing here!

**Comment by vaxerski** [comment]
nice speed

**Comment by vaxerski** [comment]
@fufexan ready for review

**Comment by fufexan** [comment]
@vaxerski don't you need to fix the conflict before I review?

**Comment by vaxerski** [comment]
the conflict is just git being confused

**Review by fufexan — APPROVED** [review]

**Pull request merged**
