### PR TITLE
renderer: fix uvBR calculation

### LINKED ISSUE #1462: Incorrect chromium wayland uv while resizing window
This issue seems to occur with Chrome windows at 2x scaling.  Issue doesn't occur on sway.  See this video for a demo:

https://user-images.githubusercontent.com/9124077/215848089-2769c549-2ee2-4464-9b1f-86e9700f02bb.mp4

### PR DESCRIPTION
**Pull request by PaideiaDilemma**
#### Describe your PR, what does it fix/add?

Fixes #1462 I think

This looked odd to me, so i added the parenthesis and then the resizing stretches in electron apps disappeared.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)

~May conflict with #7499 I will check~
Does not conflict with #7499

#### Is it ready for merging, or does it need work?

Needs confirmation that this is (more) correct and someone testing

### CODE REVIEW

**Comment by fybx** [comment]
looks fine on my end. tested chromium and obsidian with and without `--enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform-hint=auto`

**Review by vaxerski — COMMENTED** [review]
uhhh I don't know if this is right? unsure. Needs testing

**Comment by John-Paul-R** [comment]
I can confirm that this definitely appears like a substantially more correct scaling.

## Before

https://github.com/user-attachments/assets/6636ff83-4b7c-43f1-8b6d-b826e1ad6f1c

## After

https://github.com/user-attachments/assets/5f19aa9d-3f89-4f70-8613-f9f7f98dfff4

---

I am experiencing substantial stutter overall (not just window rescaling) on the locally-built version, but given the nature of the change, I suspect that's more an artifact this being my first install not via package manager, and I've borked something.

**Comment by vaxerski** [comment]
I realize chromium is better but are other things not broken xd

chromium popups, gtk apps, etc

I think gtk disables shadows now that we sent maximize, so add this patch to revert that one and check native wl gtk aspps

[patch.txt](https://github.com/user-attachments/files/17237123/patch.txt)

(don't actually use it it's just for testing)

**Comment by PaideiaDilemma** [comment]
Ran it today and also just tested gtk 3 and 4 apps with the patch.
Did not find any issues so far.

**Comment by vaxerski** [comment]
alright, thanks then

**Review by vaxerski — APPROVED** [review]

**Pull request merged**
