### PR TITLE
Trigger layout recalcuation on deco position/size change

### PR DESCRIPTION
**Pull request by zakk4223**
#### Describe your PR, what does it fix/add?
Trigger layout recalculation for windows when the deco extents/reserved area are updated.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
lol one line PR

### CODE REVIEW

**Comment by vaxerski** [comment]
you can remove window.cpp@206-207 tho with this cant you?

**Comment by vaxerski** [comment]
image
moment

**Comment by zakk4223** [comment]
I gotta stop using git clang-format, lol. I'm sure as soon as I do it'll reformat an entire file I touched one line in...

**Review by vaxerski — APPROVED** [review]
lgtm

**Pull request merged**
