### PR TITLE
refactor(binds): avoid onWindowRemoved & onWindowCreated when group has one member

### PR DESCRIPTION
**Pull request by memchr**
Make moveWindowOutOfGroup behave like toggleGroup on a group with single
member, this prevents the window from moving around unpredictably.

### CODE REVIEW

**Review by vaxerski — DISMISSED** [review]
alright, thanks!

**Comment by vaxerski** [comment]
conflict tho I believe from your other mr

**Comment by memchr** [comment]
resolved.

**Review by vaxerski — APPROVED** [review]
g

**Pull request merged**
