### PR TITLE
Replace starchart.cc with star-history.com

### PR DESCRIPTION
**Pull request by endigma**
There was some sort of rate limit issue, this one looks better too.

### CODE REVIEW

**Comment by vaxerski** [comment]
"looks better" is subjective. I think it looks like hot garbage

**Comment by endigma** [comment]
well at least it doesn't render rate limiting errors

image

**Comment by vaxerski** [comment]
image

although yes I've seen that a couple times, that's a better argument

**Comment by endigma** [comment]
Do you wanna merge this or close it as not planned or idk anything

**Comment by vaxerski** [comment]
probably close, as star-history also will err on too many requests.

**Pull request closed without merging**
