### PR TITLE
Fix resize artifacts (stretching, bumps)

### PR DESCRIPTION
**Pull request by vaxerski**
WIP

Fixes resize artifacts notably when using the mouse to resize apps to _larger_ sizes (stretching etc)

ref #7475

### CODE REVIEW

**Comment by vaxerski** [comment]
ready for review

**Comment by diniamo** [comment]
Um, I don't see a difference.

**Comment by vaxerski** [comment]
well I surely do, mind to get a recording?

**Comment by MahouShoujoMivutilde** [comment]
Definitely see the improvement.

https://github.com/user-attachments/assets/8ec2f609-88be-47fc-9472-aa8ffe7a78dd

And with patch

https://github.com/user-attachments/assets/15fabbe8-bfa1-45cb-85af-376d97a020ba

Notice no bg flash on the left window.

**Comment by diniamo** [comment]
Oh, that's the only thing I wasn't looking at. A lot of the other problems are still there though.

**Comment by vaxerski** [comment]
image
this frame is odd, as the patch should expand the texture along the edges. What's that terminal and what settings?

**Comment by MahouShoujoMivutilde** [comment]
It's because its 1.25 monitor scale, can't reproduce on 1

Foot on defaults (with my bindings and colors), and hyprland now with [hdefault-min.conf.txt](https://github.com/user-attachments/files/16740234/hdefault-min.conf.txt)

**Comment by ferrreo** [comment]
This patch does this to my wallpaper at 1.25 scaling:
image

Other than that and not fixing Electron resizing artifacts it does seem to fix stretching etc overall when resizing other things.

**Comment by vaxerski** [comment]
looks very nice.

**Comment by vaxerski** [comment]
can't repro, what wallpaper daemon?

**Comment by ferrreo** [comment]
> can't repro, what wallpaper daemon?

hyprpaper

**Comment by Agent00Ming** [comment]
Used it for a while, can't really tell the difference tbh. No noticeable problems have come up either.

**Comment by MahouShoujoMivutilde** [comment]
Can also see this effect https://github.com/hyprwm/Hyprland/pull/7499#issuecomment-2308849961 with nested sway and cage

<details><summary>With patch</summary>
<p>



</p>
</details> 

<details><summary>Without</summary>
<p>



</p>
</details> 

Latest git aqua / hl

**Comment by vaxerski** [comment]
I should revisit this mr some day

**Comment by diniamo** [comment]
> some day

😭

**Comment by vaxerski** [comment]
some fixes including for those stretched things, but if I launch two terminals quickly they kinda wonkily stretch still

**Comment by vaxerski** [comment]
any1?

**Comment by PaideiaDilemma** [comment]
I think even with animations this is a clear improvement.
Here is how it looks on my config.
OLD:


https://github.com/user-attachments/assets/fe10ac87-8c0f-4d1c-bea9-97945601890c


NEW:


https://github.com/user-attachments/assets/6659bffc-aa2d-49ca-97be-80fb076bb656

**Comment by MahouShoujoMivutilde** [comment]
Nested sway/cage issue is fixed.

This https://github.com/hyprwm/Hyprland/pull/7499#issuecomment-2308755431 still happens 

<details><summary>Details</summary>
<p>

scale 1.25, slowed down

https://github.com/user-attachments/assets/a9c7f547-2a80-4d1e-b9dc-aadff7dcd20f


https://github.com/user-attachments/assets/55df78e2-f81c-43ce-ab7f-0b58f3a278bc

scale 1, normal speed


https://github.com/user-attachments/assets/22c33c08-d99e-455f-80e7-b0c3a0b3758d


https://github.com/user-attachments/assets/4ff0d16a-1561-4163-873c-fb24dd4ceb3d



</p>
</details>

**Comment by vaxerski** [comment]
it's still better than main no? Lmk if there are any important bugs. The quick open bug is one that is annoying to me but I can live with it.

Basically, open two kitty terminals in quick succession, the first one will kinda squeeze, which looks odd.

@MahouShoujoMivutilde I am unsure why your one happens

**Comment by MahouShoujoMivutilde** [comment]
It's definitely better. I don't see any other bugs, nor do I see any problem with kitty.

<details><summary>Details</summary>
<p>


https://github.com/user-attachments/assets/df7fcff7-6277-4c23-a744-5a715fa8072a



</p>
</details>

**Comment by vaxerski** [comment]
https://github.com/user-attachments/assets/f17e88cc-c585-4407-83aa-ed0919484be5

clearly visible here

**Comment by MahouShoujoMivutilde** [comment]
Oh, yeah, I see now. I just had my

```
    bezier = cst, 0.84, 0.37, 0.2, 0.62
    animation = windows, 1, 7, cst
    animation = windowsMove, 1, 2, default
    animation = windowsOut, 1, 3, default, popin 80%
```

so it wasn't visible to me.

With `animation = windows, 1, 7, cst`, if I open another terminal during about midpoint of the opening animation of the first, this I can reproduce the similar effect, but in the form of a vertical stretching, for both kitty and foot.

<details><summary>Details</summary>
<p>


https://github.com/user-attachments/assets/38b9b834-2322-4d17-b463-f81c39fb4a5b



</p>
</details>

**Comment by MahouShoujoMivutilde** [comment]
Hold on, does xwayland work for you?

Xorg is dead for me with this patch.

**Comment by vaxerski** [comment]
magic

**Comment by MahouShoujoMivutilde** [comment]
Most likely, xwayland crashed for me the same reason https://github.com/hyprwm/Hyprland/issues/7936 happens.

Idk what triggered it first two times, but it's unrelated to the patch.

**Comment by vaxerski** [comment]
with @PaideiaDilemma's fix the resize bug is gone. Happy with merging this. Thanks everyone

**Pull request merged**
