### PR TITLE
[WIP] text-input-v1 support

### PR DESCRIPTION
**Pull request by vaxerski**
Adds support for tiv1

Doesn't seem to work yet due to chromium being weird...?

@fufexan for meson / nix (protocol added)

### CODE REVIEW

**Comment by vaxerski** [comment]
hm, so far so good, but something's off. Chromium insta-crashes on any text input from IME lol

**Comment by vaxerski** [comment]
Chromium doesn't crash most of the times now, oddly I can type entire sentences but the moment I try to type ！ after a 乾杯 it dies.

**Comment by vaxerski** [comment]
awright fixed crashes

**Comment by vaxerski** [comment]
@dragove can you test this as the original reporter for the issue

**Comment by I-Want-ToBelieve** [comment]
image

**Comment by q234rty** [comment]
Tested this a bit on arch:

```
electron19 --enable-wayland-ime --ozone-platform=wayland https://github.com # doesn't work, same symptom as the comment above
electron20 --enable-wayland-ime --ozone-platform=wayland https://github.com # ditto
electron21 --enable-wayland-ime --ozone-platform=wayland https://github.com # works
electron22 --enable-wayland-ime --ozone-platform=wayland https://github.com # works
```

VSCode is currently using electron19, so I guess the electron/chromium behavior changed in recent versions of electron/chromium.

**Comment by q234rty** [comment]
However, afaik all of the above works in weston and kwin, so there must be something that could be done by hyprland as well.

**Comment by I-Want-ToBelieve** [comment]
https://github.com/electron/electron/releases/tag/v21.0.0-alpha.1

> Added support for --ozone-platform-hint flag on Linux. https://github.com/electron/electron/pull/34937 (Also in https://github.com/electron/electron/pull/35015, https://github.com/electron/electron/pull/35014)

**Comment by vaxerski** [comment]
> And the positioning of the candidate word panel is always in the upper left corner

Odd, as the client should send the cursor box. If it doesn't, then maybe hl doesn't send some event it expects?

Although if it works with electron >=21 I'd say it's a minor issue.

I'd rather push this (because it generally works) and work on that minor problem as time goes on. Seems stable to me, so no harm in doing that.

Feel free to open another issue for that. 

Thanks for the feedback!

**Pull request merged**
