### PR TITLE
Improve hyprctl help pages

### PR DESCRIPTION
**Pull request by Micovec**
#### Describe your PR, what does it fix/add?

References #4300 

I hope I didn't miss anything. There's a lot of stuff hyprctl is capable of and some of the stuff isn't documented so I had to check for it in the code. Few descriptions are copy-pasted from the wiki.

As all help pages these are limited to 80 columns.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)

Some commands have several arguments which with their description didn't fit into the help page somewhat nicely so I replaced them with three dots. You can use `hyprctl [command] --help` to print additional help for the command. I'm not sure if it's the best solution but it was the most optimal I came up with.

#### Is it ready for merging, or does it need work?

Ready for merging

### CODE REVIEW

**Review by fufexan — COMMENTED** [review]
The `[]` everywhere should be replaced with `<>` where required, and `[]` where optional, just like most other help texts. This will also make the `(opt)` redundant, thus freeing some visual space.

**Comment by fufexan** [comment]
Sure, that sounds good.

**Comment by Micovec** [comment]
Done. Changed brackets.

**Comment by khaneliman** [comment]
Love the update, thanks for doing this.

**Pull request merged**
