### PR TITLE
Hw cursors fix for nvidia

### PR DESCRIPTION
**Pull request by UjinT34**
#### Describe your PR, what does it fix/add?
Adds an option `cursor:allow_dumb_copy` to allow dumb copy from cursor resource buffer to gbm buffer if rendering to gbm fails.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
Works for me for the most part. Lacks some features (scaling at least). Only meant as a workaround to get hw cursors which is required to test direct scanout, vrr with hw cursors and explicit sync. Probably needs a better way of copying.

#### Is it ready for merging, or does it need work?
Requires https://github.com/hyprwm/aquamarine/pull/12

### CODE REVIEW

**Comment by vaxerski** [comment]
as I've said in the AQ MR, I'd rather use drm_dumb buffers for this if possible. Should be faster than a dataptr.

**Comment by UjinT34** [comment]
I don't know how to use them and you don't seem to have enough time to deal with this issue.
Better to have somewhat slow solution than a missing feature which blocks other features.

**Comment by vaxerski** [comment]
fair enough

**Review by vaxerski — APPROVED** [review]

**Comment by gulafaran** [comment]
@UjinT34 any chance we could get scaling into this?

**Comment by UjinT34** [comment]
@gulafaran worked on https://github.com/hyprwm/Hyprland/pull/7040

I don't have access to nvidia hardware atm. And I am not really interested in HW cursors without VRR https://github.com/hyprwm/Hyprland/discussions/7386
These workarounds are mostly meant for testing direct scanout and VRR. Don't really see a point in a proper implementation without working VRR.

**Pull request merged**
