### PR TITLE
default/config: move shadow options to decoration:shadow

### PR DESCRIPTION
**Pull request by Kam1k4dze**
#### Is it ready for merging, or does it need work?
Yes

### CODE REVIEW

**Comment by izmyname** [comment]
Is this gonna break existing configs?

**Comment by Kam1k4dze** [comment]
No, It just fixes the default config. After https://github.com/hyprwm/Hyprland/commit/d1638a09bacd84b994de3f77746b74f427b9d41e, it gives errors because shadow options have now moved to `decoration:shadow`.

**Review by vaxerski — APPROVED** [review]
right, forgot. Thanks!

**Comment by cowboyai** [comment]
it totally breaks existing configs that auto-populate hyprland.conf, such as stylix.
see [Stylix PR](https://github.com/danth/stylix/pull/623)

**Comment by vaxerski** [comment]
that is their problem, not ours, no?

**Comment by cowboyai** [comment]
indeed it is, but it does break existing things without issuing a warning of the change first and supporting both models during the transition. For Nix, this seems to be a worthwhile model, if you detect the old model in Nix, convert it to the new model and issue a warning for a version or two. I see this in most things supporting nixpkgs.

**Comment by vaxerski** [comment]
supporting both would be a PITA. You can always query version with `hyprctl version` :)

**Pull request merged**
