### PR TITLE
Comments in configs folder and template handler function

### PR DESCRIPTION
**Pull request by JassonCordones**
#### Describe your PR, what does it fix/add?
Comments to config and added a template function that encapsulates the common logic for handling commands in the config manager.

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
No

#### Is it ready for merging, or does it need work?
Yes

### CODE REVIEW

**Review by fufexan — CHANGES_REQUESTED** [review]
Includes shouldn't be removed, otherwise the no PCH build fails (see CI).

**Comment by fufexan** [comment]
There's a conflict.

**Comment by JassonCordones** [comment]
> There's a conflict.

I'll check again

**Comment by JassonCordones** [comment]
Done

**Comment by JassonCordones** [comment]
This is ready

**Comment by fufexan** [comment]
Looks like there's yet another conflict.

**Comment by JassonCordones** [comment]
solved

**Pull request closed without merging**
